/home/jonwebb/Code_Dev/C/c_libs/c_libs/include/print.c File Reference
#include `print.h`
Functions
void print_short (short x)
void print_ushort (unsigned short x)
void print_int (int x)
void print_uint (unsigned int x)
void print_long (long int x)
void print_ulong (unsigned long int x)
void print_llong (long long int x)
void print_ullong (unsigned long long int x)
void print_float (float x)
void print_double (double x)
void print_longdouble (long double x)
void print_char (char x)
void print_uchar (unsigned char x)
void print_bool (bool x)
void print_string (char *x)
void print_vshort (Short x)
void print_vushort (UShort x)
void print_vint (Int x)
void print_vuint (UInt x)
void print_vlint (LInt x)
void print_vulint (ULInt x)
void print_vllint (LLInt x)
void print_vullint (ULLInt x)
void print_vfloat (Flt x)
void print_vdble (Dble x)
void print_vldble (LDble x)
void print_achar (Char x)
void print_vbool (Bool x)
void print_vstring (String x)
Function Documentation
print_achar()
void print_achar (Char x)
Definition at line 275 of file print.c.
                         {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_char(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_char(x.array[x.active_length - 1]);
    printf(" ]");
}
References print_char(), and PRNT_LENGTH.
print_bool()
void print_bool (bool x)
Definition at line 31 of file print.c.
{ printf(x ? "true" : "false"); }
Referenced by print_vbool().
print_char()
void print_char (char x)
Definition at line 29 of file print.c.
{ printf("%c", x); }
Referenced by print_achar().
print_double()
void print_double (double x)
Definition at line 27 of file print.c.
{ printf("%lf", x); }
Referenced by print_vdble().
print_float()
void print_float (float x)
Definition at line 26 of file print.c.
{ printf("%f", x); }
Referenced by print_vfloat().
print_int()
void print_int (int x)
Definition at line 20 of file print.c.
{ printf("%d", x); }
Referenced by print_vint().
print_llong()
void print_llong (long long int x)
Definition at line 24 of file print.c.
{ printf("%lld", x); }
Referenced by print_vllint().
print_long()
void print_long (long int x)
Definition at line 22 of file print.c.
{ printf("%ld", x); }
Referenced by print_vlint().
print_longdouble()
void print_longdouble (long double x)
Definition at line 28 of file print.c.
{ printf("%Lf", x); }
Referenced by print_vldble().
print_short()
void print_short (short x)
Definition at line 18 of file print.c.
{ printf("%hd", x); }
Referenced by print_vshort().
print_string()
void print_string (char * x)
Definition at line 32 of file print.c.
{ printf("%s", x); }
Referenced by print_vstring().
print_uchar()
void print_uchar (unsigned char x)
Definition at line 30 of file print.c.
{ printf("%hhu", x); }
print_uint()
void print_uint (unsigned int x)
Definition at line 21 of file print.c.
{ printf("%u", x); }
Referenced by print_vuint().
print_ullong()
void print_ullong (unsigned long long int x)
Definition at line 25 of file print.c.
{ printf("%llu", x); }
Referenced by print_vullint().
print_ulong()
void print_ulong (unsigned long int x)
Definition at line 23 of file print.c.
{ printf("%lu", x); }
Referenced by print_vulint().
print_ushort()
void print_ushort (unsigned short x)
Definition at line 19 of file print.c.
{ printf("%hu", x); }
Referenced by print_vushort().
print_vbool()
void print_vbool (Bool x)
Definition at line 297 of file print.c.
                         {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_bool(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_bool(x.array[x.active_length - 1]);
    printf(" ]");
}
References print_bool(), and PRNT_LENGTH.
print_vdble()
void print_vdble (Dble x)
Definition at line 231 of file print.c.
                         {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_double(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_double(x.array[x.active_length - 1]);
    printf(" ]");
}
References print_double(), and PRNT_LENGTH.
print_vfloat()
void print_vfloat (Flt x)
Definition at line 209 of file print.c.
                         {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_float(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_float(x.array[x.active_length - 1]);
    printf(" ]");
}
References print_float(), and PRNT_LENGTH.
print_vint()
void print_vint (Int x)
Definition at line 81 of file print.c.
                       {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_int(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_int(x.array[x.active_length - 1]);
    printf(" ]");
}
References print_int(), and PRNT_LENGTH.
print_vldble()
void print_vldble (LDble x)
Definition at line 253 of file print.c.
                           {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_longdouble(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_longdouble(x.array[x.active_length - 1]);
    printf(" ]");
}
References print_longdouble(), and PRNT_LENGTH.
print_vlint()
void print_vlint (LInt x)
Definition at line 121 of file print.c.
                         {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_long(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_long(x.array[x.active_length - 1]);
    printf(" ]");
}
References print_long(), and PRNT_LENGTH.
print_vllint()
void print_vllint (LLInt x)
Definition at line 165 of file print.c.
                           {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_llong(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_llong(x.array[x.active_length - 1]);
    printf(" ]");
}
References print_llong(), and PRNT_LENGTH.
print_vshort()
void print_vshort (Short x)
Definition at line 37 of file print.c.
                           {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_short(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_short(x.array[x.active_length - 1]);
    printf(" ]");
}
References print_short(), and PRNT_LENGTH.
print_vstring()
void print_vstring (String x)
Definition at line 319 of file print.c.
                             {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_string(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_string(x.array[x.active_length - 1]);
    printf(" ]");
}
References String::active_length, String::array, print_string(), and PRNT_LENGTH.
print_vuint()
void print_vuint (UInt x)
Definition at line 103 of file print.c.
                         {
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_uint(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_uint(x.array[x.active_length - 1]);
    printf(" ]");
}
References print_uint(), and PRNT_LENGTH.
print_vulint()
void print_vulint (ULInt x)
Definition at line 143 of file print.c.
                           {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_ulong(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_ulong(x.array[x.active_length - 1]);
    printf(" ]");
}
References print_ulong(), and PRNT_LENGTH.
print_vullint()
void print_vullint (ULLInt x)
Definition at line 187 of file print.c.
                             {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_ullong(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_ullong(x.array[x.active_length - 1]);
    printf(" ]");
}
References print_ullong(), and PRNT_LENGTH.
print_vushort()
void print_vushort (UShort x)
Definition at line 59 of file print.c.
                             {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_ushort(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_ushort(x.array[x.active_length - 1]);
    printf(" ]");
}
References print_ushort(), and PRNT_LENGTH.