/home/jonwebb/Code_Dev/C/c_libs/c_libs/include/vector.h File Reference
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include `swap.h`
Classes
struct String
Macros
#define VECTOR_STRUCT(type, dtype) typedef struct {type *array; size_t allocated_length; size_t active_length; mem_type dat_type; } dtype
#define INIT_VECTOR(T, length)
#define INIT_ARRAY(T, arr, aloc_len, active_len)
#define TRIM(T)
Enumerations
enum mem_type { DYNAMIC
, STATIC
 }
enum sort_order { FORWARD
, REVERSE
 }
Functions
VECTOR_STRUCT (short, Short)
VECTOR_STRUCT (unsigned short int, UShort)
VECTOR_STRUCT (int, Int)
VECTOR_STRUCT (unsigned, UInt)
VECTOR_STRUCT (long, LInt)
VECTOR_STRUCT (unsigned long int, ULInt)
VECTOR_STRUCT (long long int, LLInt)
VECTOR_STRUCT (unsigned long long int, ULLInt)
VECTOR_STRUCT (float, Flt)
VECTOR_STRUCT (double, Dble)
VECTOR_STRUCT (long double, LDble)
VECTOR_STRUCT (char, Char)
VECTOR_STRUCT (unsigned char, UChar)
VECTOR_STRUCT (bool, Bool)
int init_short_vector (Short *vec, size_t length)
int init_ushort_vector (UShort *vec, size_t length)
int init_int_vector (Int *vec, size_t length)
int init_uint_vector (UInt *vec, size_t length)
int init_long_vector (LInt *vec, size_t length)
int init_ulong_vector (ULInt *vec, size_t length)
int init_llong_vector (LLInt *vec, size_t length)
int init_ullong_vector (ULLInt *vec, size_t length)
int init_float_vector (Flt *vec, size_t length)
int init_double_vector (Dble *vec, size_t length)
int init_ldouble_vector (LDble *vec, size_t length)
int init_char_vector (Char *vec, size_t length)
int init_uchar_vector (UChar *vec, size_t length)
int init_bool_vector (Bool *vec, size_t length)
int init_string_vector (String *vec)
void init_short_array (Short *vec, short int *arr, size_t allocated_length, size_t active_length)
void init_ushort_array (UShort *vec, unsigned short int *arr, size_t allocated_length, size_t active_length)
void init_int_array (Int *vec, int *arr, size_t allocated_length, size_t active_length)
void init_uint_array (UInt *vec, unsigned int *arr, size_t allocated_length, size_t active_length)
void init_long_array (LInt *vec, long int *arr, size_t allocated_length, size_t active_length)
void init_ulong_array (ULInt *vec, unsigned long int *arr, size_t allocated_length, size_t active_length)
void init_llong_array (LLInt *vec, long long int *arr, size_t allocated_length, size_t active_length)
void init_ullong_array (ULLInt *vec, unsigned long long int *arr, size_t allocated_length, size_t active_length)
void init_float_array (Flt *vec, float *arr, size_t allocated_length, size_t active_length)
void init_double_array (Dble *vec, double *arr, size_t allocated_length, size_t active_length)
void init_ldouble_array (LDble *vec, long double *arr, size_t allocated_length, size_t active_length)
void init_char_array (Char *vec, char *arr, size_t allocated_length, size_t active_length)
void init_uchar_array (UChar *vec, unsigned char *arr, size_t allocated_length, size_t active_length)
void init_bool_array (Bool *vec, bool *arr, size_t allocated_length, size_t active_length)
int push_short_vector (Short *vec, short int value, size_t index)
int push_ushort_vector (UShort *vec, unsigned short int value, size_t index)
int push_int_vector (Int *vec, int value, size_t index)
int push_uint_vector (UInt *vec, unsigned int value, size_t index)
int push_long_vector (LInt *vec, long int value, size_t index)
int push_ulong_vector (ULInt *vec, unsigned long int value, size_t index)
int push_llong_vector (LLInt *vec, long long int value, size_t index)
int push_ullong_vector (ULLInt *vec, unsigned long long int value, size_t index)
int push_float_vector (Flt *vec, float value, size_t index)
int push_double_vector (Dble *vec, double value, size_t index)
int push_ldouble_vector (LDble *vec, long double value, size_t index)
int push_char_vector (Char *vec, char value, size_t index)
int push_uchar_vector (UChar *vec, unsigned char value, size_t index)
int push_string_vector (String *vec, char *value, size_t index)
int push_bool_vector (Bool *vec, bool value, size_t index)
int insert_short_vector (Short *vec, short int *elements, size_t num_indices, size_t index)
int insert_ushort_vector (UShort *vec, unsigned short int *elements, size_t num_indices, size_t index)
int insert_int_vector (Int *vec, int *elements, size_t num_indices, size_t index)
int insert_uint_vector (UInt *vec, unsigned int *elements, size_t num_indices, size_t index)
int insert_long_vector (LInt *vec, long int *elements, size_t num_indices, size_t index)
int insert_ulong_vector (ULInt *vec, unsigned long int *elements, size_t num_indices, size_t index)
int insert_llong_vector (LLInt *vec, long long int *elements, size_t num_indices, size_t index)
int insert_ullong_vector (ULLInt *vec, unsigned long long int *elements, size_t num_indices, size_t index)
int insert_float_vector (Flt *vec, float *elements, size_t num_indices, size_t index)
int insert_double_vector (Dble *vec, double *elements, size_t num_indices, size_t index)
int insert_ldouble_vector (LDble *vec, long double *elements, size_t num_indices, size_t index)
int insert_char_vector (Char *vec, char *elements, size_t num_indices, size_t index)
int insert_uchar_vector (UChar *vec, unsigned char *elements, size_t num_indices, size_t index)
int insert_bool_vector (Bool *vec, bool *elements, size_t num_indices, size_t index)
int insert_string_vector (String *vec, char **elements, size_t num_indices, size_t index)
int pop_short_vector_index (Short *vec, size_t index)
pop_type_stack_index functions
int pop_ushort_vector_index (UShort *vec, size_t index)
int pop_int_vector_index (Int *vec, size_t index)
int pop_uint_vector_index (UInt *vec, size_t index)
int pop_long_vector_index (LInt *vec, size_t index)
int pop_ulong_vector_index (ULInt *vec, size_t index)
int pop_llong_vector_index (LLInt *vec, size_t index)
int pop_ullong_vector_index (ULLInt *vec, size_t index)
int pop_float_vector_index (Flt *vec, size_t index)
int pop_double_vector_index (Dble *vec, size_t index)
int pop_ldouble_vector_index (LDble *vec, size_t index)
int pop_char_vector_index (Char *vec, size_t index)
int pop_uchar_vector_index (UChar *vec, size_t index)
int pop_bool_vector_index (Bool *vec, size_t index)
int pop_string_vector_index (String *vec, size_t index)
void replace_short_vector_values (Short *vec, short int old_value, short int new_value)
void replace_ushort_vector_values (UShort *vec, unsigned short int old_value, unsigned short int new_value)
void replace_int_vector_values (Int *vec, int old_value, int new_value)
void replace_uint_vector_values (UInt *vec, unsigned int old_value, unsigned int new_value)
void replace_long_vector_values (LInt *vec, long int old_value, long int new_value)
void replace_ulong_vector_values (ULInt *vec, unsigned long int old_value, unsigned long int new_value)
void replace_llong_vector_values (LLInt *vec, long long int old_value, long long int new_value)
void replace_ullong_vector_values (ULLInt *vec, unsigned long long int old_value, unsigned long long int new_value)
void replace_float_vector_values (Flt *vec, float old_value, float new_value)
void replace_double_vector_values (Dble *vec, double old_value, double new_value)
void replace_ldouble_vector_values (LDble *vec, long double old_value, long double new_value)
void replace_char_vector_values (Char *vec, char old_value, char new_value)
void replace_uchar_vector_values (UChar *vec, unsigned char old_value, unsigned char new_value)
void replace_bool_vector_values (Bool *vec, bool old_value, char new_value)
void replace_string_vector_values (String *vec, char *old_value, char *new_value)
void free_short_vector (Short *vec)
void free_ushort_vector (UShort *vec)
void free_int_vector (Int *vec)
void free_uint_vector (UInt *vec)
void free_long_vector (LInt *vec)
void free_ulong_vector (ULInt *vec)
void free_llong_vector (LLInt *vec)
void free_ullong_vector (ULLInt *vec)
void free_float_vector (Flt *vec)
void free_double_vector (Dble *vec)
void free_ldouble_vector (LDble *vec)
void free_char_vector (Char *vec)
void free_uchar_vector (UChar *vec)
void free_bool_vector (Bool *vec)
void free_string_vector (String *vec)
void delete_short_vector_duplicates (Short *vec)
void delete_ushort_vector_duplicates (UShort *vec)
void delete_int_vector_duplicates (Int *vec)
void delete_uint_vector_duplicates (UInt *vec)
void delete_long_vector_duplicates (LInt *vec)
void delete_ulong_vector_duplicates (ULInt *vec)
void delete_llong_vector_duplicates (LLInt *vec)
void delete_ullong_vector_duplicates (ULLInt *vec)
void delete_float_vector_duplicates (Flt *vec)
void delete_double_vector_duplicates (Dble *vec)
void delete_ldouble_vector_duplicates (LDble *vec)
void delete_char_vector_duplicates (Char *vec)
void delete_uchar_vector_duplicates (UChar *vec)
void delete_bool_vector_duplicates (Bool *vec)
void delete_string_vector_duplicates (String *vec)
void reverse_short_vector (Short *vec)
void reverse_ushort_vector (UShort *vec)
void reverse_int_vector (Int *vec)
void reverse_uint_vector (UInt *vec)
void reverse_long_vector (LInt *vec)
void reverse_ulong_vector (ULInt *vec)
void reverse_llong_vector (LLInt *vec)
void reverse_ullong_vector (ULLInt *vec)
void reverse_float_vector (Flt *vec)
void reverse_double_vector (Dble *vec)
void reverse_ldouble_vector (LDble *vec)
void reverse_char_vector (Char *vec)
void reverse_uchar_vector (UChar *vec)
void reverse_bool_vector (Bool *vec)
void reverse_string_vector (String *vec)
void sort_short_vector (Short *vec, size_t low, size_t high, sort_order order)
void sort_ushort_vector (UShort *vec, size_t low, size_t high, sort_order order)
void sort_int_vector (Int *vec, size_t low, size_t high, sort_order order)
void sort_uint_vector (UInt *vec, size_t low, size_t high, sort_order order)
void sort_long_vector (LInt *vec, size_t low, size_t high, sort_order order)
void sort_ulong_vector (ULInt *vec, size_t low, size_t high, sort_order order)
void sort_llong_vector (LLInt *vec, size_t low, size_t high, sort_order order)
void sort_ullong_vector (ULLInt *vec, size_t low, size_t high, sort_order order)
void sort_float_vector (Flt *vec, size_t low, size_t high, sort_order order)
void sort_double_vector (Dble *vec, size_t low, size_t high, sort_order order)
void sort_ldouble_vector (LDble *vec, size_t low, size_t high, sort_order order)
void sort_char_vector (Char *vec, size_t low, size_t high, sort_order order)
void sort_uchar_vector (UChar *vec, size_t low, size_t high, sort_order order)
void sort_bool_vector (Bool *vec, size_t low, size_t high, sort_order order)
void sort_string_vector (String *vec, size_t low, size_t high, sort_order order)
char sum_char_vector (Char *vec)
unsigned char sum_uchar_vector (UChar *vec)
short int sum_short_vector (Short *vec)
unsigned short int sum_ushort_vector (UShort *vec)
int sum_int_vector (Int *vec)
unsigned int sum_uint_vector (UInt *vec)
long int sum_long_vector (LInt *vec)
unsigned long int sum_ulong_vector (ULInt *vec)
long long int sum_llong_vector (LLInt *vec)
unsigned long long int sum_ullong_vector (ULLInt *vec)
float sum_float_vector (Flt *vec)
double sum_double_vector (Dble *vec)
long double sum_ldouble_vector (LDble *vec)
Char cumsum_char_vector (Char *vec)
UChar cumsum_uchar_vector (UChar *vec)
Short cumsum_short_vector (Short *vec)
UShort cumsum_ushort_vector (UShort *vec)
Int cumsum_int_vector (Int *vec)
UInt cumsum_uint_vector (UInt *vec)
LInt cumsum_long_vector (LInt *vec)
ULInt cumsum_ulong_vector (ULInt *vec)
LLInt cumsum_llong_vector (LLInt *vec)
ULLInt cumsum_ullong_vector (ULLInt *vec)
Flt cumsum_float_vector (Flt *vec)
Dble cumsum_double_vector (Dble *vec)
LDble cumsum_ldouble_vector (LDble *vec)
char average_char_vector (Char *vec)
unsigned char average_uchar_vector (UChar *vec)
float average_short_vector (Short *vec)
float average_ushort_vector (UShort *vec)
float average_int_vector (Int *vec)
float average_uint_vector (UInt *vec)
double average_long_vector (LInt *vec)
double average_ulong_vector (ULInt *vec)
long double average_llong_vector (LLInt *vec)
long double average_ullong_vector (ULLInt *vec)
float average_float_vector (Flt *vec)
double average_double_vector (Dble *vec)
long double average_ldouble_vector (LDble *vec)
char stdev_char_vector (Char *vec)
char stdev_uchar_vector (UChar *vec)
float stdev_short_vector (Short *vec)
float stdev_ushort_vector (UShort *vec)
float stdev_int_vector (Int *vec)
float stdev_uint_vector (UInt *vec)
double stdev_long_vector (LInt *vec)
double stdev_ulong_vector (ULInt *vec)
long double stdev_llong_vector (LLInt *vec)
long double stdev_ullong_vector (ULLInt *vec)
float stdev_float_vector (Flt *vec)
double stdev_double_vector (Dble *vec)
long double stdev_ldouble_vector (LDble *vec)
char max_char_vector (Char *vec)
unsigned char max_uchar_vector (UChar *vec)
short int max_short_vector (Short *vec)
unsigned short int max_ushort_vector (UShort *vec)
int max_int_vector (Int *vec)
unsigned int max_uint_vector (UInt *vec)
long int max_long_vector (LInt *vec)
unsigned long int max_ulong_vector (ULInt *vec)
long long int max_llong_vector (LLInt *vec)
unsigned long long int max_ullong_vector (ULLInt *vec)
float max_float_vector (Flt *vec)
double max_double_vector (Dble *vec)
long double max_ldouble_vector (LDble *vec)
char min_char_vector (Char *vec)
unsigned char min_uchar_vector (UChar *vec)
short int min_short_vector (Short *vec)
unsigned short int min_ushort_vector (UShort *vec)
int min_int_vector (Int *vec)
unsigned int min_uint_vector (UInt *vec)
long int min_long_vector (LInt *vec)
unsigned long int min_ulong_vector (ULInt *vec)
long long int min_llong_vector (LLInt *vec)
unsigned long long int min_ullong_vector (ULLInt *vec)
float min_float_vector (Flt *vec)
double min_double_vector (Dble *vec)
long double min_ldouble_vector (LDble *vec)
void range_char_vector (Char *vec, char start, char end, char delta)
void range_uchar_vector (UChar *vec, unsigned char start, unsigned char end, unsigned char delta)
void range_short_vector (Short *vec, short int start, short int end, short int delta)
void range_ushort_vector (UShort *vec, unsigned short int start, unsigned short int end, unsigned short int delta)
void range_int_vector (Int *vec, int start, int end, int delta)
void range_uint_vector (UInt *vec, unsigned int start, unsigned int end, unsigned int delta)
void range_long_vector (LInt *vec, long int start, long int end, long int delta)
void range_ulong_vector (ULInt *vec, unsigned long int start, unsigned long int end, unsigned long int delta)
void range_llong_vector (LLInt *vec, long long int start, long long int end, long long int delta)
void range_ullong_vector (ULLInt *vec, unsigned long long int start, unsigned long long int end, unsigned long long int delta)
void range_float_vector (Flt *vec, float start, float end, float delta)
void range_double_vector (Dble *vec, double start, double end, double delta)
Short copy_short_vector (Short *vec)
UShort copy_ushort_vector (UShort *vec)
Int copy_int_vector (Int *vec)
UInt copy_uint_vector (UInt *vec)
LInt copy_long_vector (LInt *vec)
ULInt copy_ulong_vector (ULInt *vec)
LLInt copy_llong_vector (LLInt *vec)
ULLInt copy_ullong_vector (ULLInt *vec)
Flt copy_float_vector (Flt *vec)
Dble copy_double_vector (Dble *vec)
LDble copy_ldouble_vector (LDble *vec)
Char copy_char_vector (Char *vec)
Bool copy_bool_vector (Bool *vec)
String copy_string_vector (String *vec)
short short_vector_data (Short *vec, size_t index)
unsigned short int ushort_vector_data (UShort *vec, size_t index)
int int_vector_data (Int *vec, size_t index)
unsigned int uint_vector_data (UInt *vec, size_t index)
long int long_vector_data (LInt *vec, size_t index)
unsigned long int ulong_vector_data (ULInt *vec, size_t index)
long long int llong_vector_data (LLInt *vec, size_t index)
unsigned long long int ullong_vector_data (ULLInt *vec, size_t index)
float float_vector_data (Flt *vec, size_t index)
double double_vector_data (Dble *vec, size_t index)
long double ldouble_vector_data (LDble *vec, size_t index)
char char_vector_data (Char *vec, size_t index)
bool bool_vector_data (Bool *vec, size_t index)
char * string_vector_data (String *vec, size_t index)
void trim_short_vector (Short *vec)
void trim_ushort_vector (UShort *vec)
void trim_int_vector (Int *vec)
void trim_uint_vector (UInt *vec)
void trim_long_vector (LInt *vec)
void trim_ulong_vector (ULInt *vec)
void trim_llong_vector (LLInt *vec)
void trim_ullong_vector (ULLInt *vec)
void trim_float_vector (Flt *vec)
void trim_double_vector (Dble *vec)
void trim_ldouble_vector (LDble *vec)
void trim_char_vector (Char *vec)
void trim_uchar_vector (UChar *vec)
void trim_bool_vector (Bool *vec)
int replace_short_vector_index (Short *vec, short int new_value, size_t index)
int replace_ushort_vector_index (UShort *vec, unsigned short int new_value, size_t index)
int replace_int_vector_index (Int *vec, int new_value, size_t index)
int replace_uint_vector_index (UInt *vec, unsigned int new_value, size_t index)
int replace_long_vector_index (LInt *vec, long int new_value, size_t index)
int replace_ulong_vector_index (ULInt *vec, unsigned long int new_value, size_t index)
int replace_llong_vector_index (LLInt *vec, long long int new_value, size_t index)
int replace_ullong_vector_index (ULLInt *vec, unsigned long long int new_value, size_t index)
int replace_float_vector_index (Flt *vec, float new_value, size_t index)
int replace_double_vector_index (Dble *vec, double new_value, size_t index)
int replace_ldouble_vector_index (LDble *vec, long double new_value, size_t index)
int replace_bool_vector_index (Bool *vec, bool new_value, size_t index)
int replace_string_vector_index (String *vec, char *new_value, size_t index)
int replace_char_vector_index (Char *vec, char new_value, size_t index)
int replace_uchar_vector_index (UChar *vec, unsigned char new_value, size_t index)
int repeat_short_vector (Short *vec, short int value, size_t num)
int repeat_ushort_vector (UShort *vec, unsigned short int value, size_t num)
int repeat_int_vector (Int *vec, int value, size_t num)
int repeat_uint_vector (UInt *vec, unsigned int value, size_t num)
int repeat_long_vector (LInt *vec, long int value, size_t num)
int repeat_ulong_vector (ULInt *vec, unsigned long int value, size_t num)
int repeat_llong_vector (LLInt *vec, long long int value, size_t num)
int repeat_ullong_vector (ULLInt *vec, unsigned long long int value, size_t num)
int repeat_float_vector (Flt *vec, float value, size_t num)
int repeat_double_vector (Dble *vec, double value, size_t num)
int repeat_ldouble_vector (LDble *vec, long double value, size_t num)
int repeat_bool_vector (Bool *vec, bool value, size_t num)
int repeat_string_vector (String *vec, char *value, size_t num)
int repeat_char_vector (Char *vec, char value, size_t num)
int repeat_uchar_vector (UChar *vec, unsigned char value, size_t num)
Macro Definition Documentation
INIT_ARRAY
#define INIT_ARRAY(T, arr, aloc_len, active_len)
Value:
                                                   _Generic((T), Short: init_short_array, \
                                                   UShort: init_ushort_array, \
                                                   Int: init_int_array, \
                                                   UInt: init_uint_array, \
                                                   LInt: init_long_array, \
                                                   ULInt: init_ulong_array, \
                                                   LLInt: init_llong_array, \
                                                   ULLInt: init_ullong_array, \
                                                   Flt: init_float_array, \
                                                   Dble: init_double_array, \
                                                   LDble: init_ldouble_array, \
                                                   Char: init_char_array, \
                                                   UChar: init_uchar_array, \
                                                   Bool: init_bool_array)(&T, arr, aloc_len, active_len)
Definition at line 567 of file vector.h.
INIT_VECTOR
#define INIT_VECTOR(T, length)
Value:
                                                   _Generic((T), Short: init_short_vector, \
                                                   UShort: init_ushort_vector, \
                                                   Int: init_int_vector, \
                                                   UInt: init_uint_vector, \
                                                   LInt: init_long_vector, \
                                                   ULInt: init_ulong_vector, \
                                                   LLInt: init_llong_vector, \
                                                   ULLInt: init_ullong_vector, \
                                                   Flt: init_float_vector, \
                                                   Dble: init_double_vector, \
                                                   LDble: init_ldouble_vector, \
                                                   Char: init_char_vector, \
                                                   UChar: init_uchar_vector, \
                                                   Bool: init_bool_vector)(&T, length)
This macro will allocate memory for an array and assign that memory to the array pointer variable in a struct. The macro will also assign the number of allocated indices to allocated_length and assign active_length a size of 0. This function requires the input of a struct instantiated with the VECTOR_STRUCT method.
/param vec A vector instantiated with the VECTOR_STRUCT macro. /length The length of the array as a size_t variable
// Initialize a dynamically allocated Integer vector with 0 indices
Int vec;
INIT_VECTOR(vec, 20)
Definition at line 280 of file vector.h.
TRIM
#define TRIM(T)
Value:
                                       _Generic((T), Int8: Short: trim_short_vector, \
                                       UShort: trim_ushort_vector, \
                                       Int: trim_int_vector, \
                                       UInt: trim_uint_vector, \
                                       LInt: trim_long_vector, \
                                       ULInt: trim_ulong_vector, \
                                       LLInt: trim_llong_vector, \
                                       ULLInt: trim_ullong_vector, \
                                       Flt: trim_float_vector, \
                                       Dble: trim_double_vector, \
                                       LDble: trim_ldouble_vector, \
                                       Char: trim_char_vector, \
                                       UChar: trim_uchar_vector, \
                                       Bool: trim_bool_vector)(&T)
Macro to trim a vecotr or array memory to minimum necessary value
/param vec The vector to be trimmed.
Definition at line 5804 of file vector.h.
VECTOR_STRUCT
#define VECTOR_STRUCT(type, dtype) typedef struct {type *array; size_t allocated_length; size_t active_length; mem_type dat_type; } dtype
This macro will produce a struct that is specifically designed to track all attributes necessary for the maintenance of a dynamically, or statically allocated array. The macro has an attribute to a pointer for the array, allocated_length, active_length, and mem_type.
/param type The data type that will be assigned to the array pointer /param dtype The name to be given to the typedef for the struct
// code to create a struct of type IntVector
VECTOR_STRUCT(float, IntVector)
IntVector vec;
Definition at line 69 of file vector.h.
Enumeration Type Documentation
mem_type
enum mem_type
A collection of human readable integer representations that describe how memory is allocated to a vector or array
Parameters
DYNAMIC An integer representing dynamic memory allocation on the heap
STATIC An integer representing static memory allocation on the stack
Enumerator
DYNAMIC
STATIC
Definition at line 36 of file vector.h.
{
    DYNAMIC,
    STATIC
} mem_type;
sort_order
enum sort_order
A collection of human readable integer representations that describe whether an array is to be sorted in the forward or reverse direction
Enumerator
FORWARD
REVERSE
Definition at line 47 of file vector.h.
{
    FORWARD,
    REVERSE
} sort_order;
Function Documentation
average_char_vector()
char average_char_vector (Char * vec)
This function will return the average value of the data in a vector data structure of type Short
/param vec A vector data structure of type Char /return avg The average value in the input data structure of type Char
Char vec;
init_char_vector(&vec, 5);
char a[5] = {1, 2, 3, 4, 5};
insert_char_vector(&vec, a, 5, 0);
char b = average_char_vector(&vec);
PRINT(b);
// >> 3.00000
free_char_vector(&vec);
Definition at line 3154 of file vector.c.
                                    {
    char sum = sum_char_vector(vec);
    char avg = sum / (char)vec->active_length;
    return avg;
}
References sum_char_vector().
Referenced by stdev_char_vector().
average_double_vector()
double average_double_vector (Dble * vec)
This function will return the average value of the data in a vector data structure of type Dble
/param vec A vector data structure of type Dble /return avg The average value in the input data structure of type Dble
Dble vec;
init_double_vector(&vec, 5);
double a[5] = {1, 2, 3, 4, 5};
insert_double_vector(&vec, a, 5, 0);
double b = average_double_vector(&vec);
PRINT(b);
// >> 3.00000
free_double_vector(&vec);
Definition at line 3230 of file vector.c.
                                        {
    double sum = sum_double_vector(vec);
    double avg = sum / (double)vec->active_length;
    return avg;
}
References sum_double_vector().
Referenced by stdev_double_vector().
average_float_vector()
float average_float_vector (Flt * vec)
This function will return the average value of the data in a vector data structure of type Flt
/param vec A vector data structure of type Flt /return avg The average value in the input data structure of type Flt
Flt vec;
init_float_vector(&vec, 5);
float a[5] = {1, 2, 3, 4, 5};
insert_float_vector(&vec, a, 5, 0);
float b = average_float_vector(&vec);
PRINT(b);
// >> 3.00000
free_float_vector(&vec);
Definition at line 3223 of file vector.c.
                                     {
    float sum = sum_float_vector(vec);
    float avg = sum / (float)vec->active_length;
    return avg;
}
References sum_float_vector().
Referenced by stdev_float_vector().
average_int_vector()
float average_int_vector (Int * vec)
This function will return the average value of the data in a vector data structure of type Int
/param vec A vector data structure of type Int /return avg The average value in the input data structure of type Int
Int vec;
init_int_vector(&vec, 5);
int a[5] = {1, 2, 3, 4, 5};
insert_int_vector(&vec, a, 5, 0);
float b = average_int_vector(&vec);
PRINT(b);
// >> 3.00000
free_int_vector(&vec);
Definition at line 3181 of file vector.c.
                                   {
    int sum = sum_int_vector(vec);
    float avg = sum / (float)vec->active_length;
    return avg;
}
References sum_int_vector().
Referenced by stdev_int_vector().
average_ldouble_vector()
long double average_ldouble_vector (LDble * vec)
This function will return the average value of the data in a vector data structure of type LDble
/param vec A vector data structure of type LDble /return avg The average value in the input data structure of type LDble
LDble vec;
init_ldouble_vector(&vec, 5);
long double a[5] = {1, 2, 3, 4, 5};
insert_ldouble_vector(&vec, a, 5, 0);
long double b = average_ldouble_vector(&vec);
PRINT(b);
// >> 3.00000
free_ldouble_vector(&vec);
Definition at line 3237 of file vector.c.
                                               {
    long double sum = sum_ldouble_vector(vec);
    long double avg = sum / (long double)vec->active_length;
    return avg;
}
References sum_ldouble_vector().
Referenced by stdev_ldouble_vector().
average_llong_vector()
long double average_llong_vector (LLInt * vec)
This function will return the average value of the data in a vector data structure of type LLInt
/param vec A vector data structure of type LLInt /return avg The average value in the input data structure of type LLInt
LLInt vec;
init_llong_vector(&vec, 5);
long long int a[5] = {1, 2, 3, 4, 5};
insert_llong_vector(&vec, a, 5, 0);
long double b = average_llong_vector(&vec);
PRINT(b);
// >> 3.00000
free_llong_vector(&vec);
Definition at line 3209 of file vector.c.
                                             {
    long long int sum = sum_llong_vector(vec);
    long double avg = sum / (long double)vec->active_length;
    return avg;
}
References sum_llong_vector().
Referenced by stdev_llong_vector().
average_long_vector()
double average_long_vector (LInt * vec)
This function will return the average value of the data in a vector data structure of type LInt
/param vec A vector data structure of type LInt /return avg The average value in the input data structure of type LInt
LInt vec;
init_long_vector(&vec, 5);
long int a[5] = {1, 2, 3, 4, 5};
insert_long_vector(&vec, a, 5, 0);
double b = average_long_vector(&vec);
PRINT(b);
// >> 3.00000
free_long_vector(&vec);
Definition at line 3195 of file vector.c.
                                      {
    long int sum = sum_long_vector(vec);
    double avg = sum / (double)vec->active_length;
    return avg;
}
References sum_long_vector().
Referenced by stdev_long_vector().
average_short_vector()
float average_short_vector (Short * vec)
This function will return the average value of the data in a vector data structure of type Short
/param vec A vector data structure of type Short /return avg The average value in the input data structure of type Short
Short vec;
init_short_vector(&vec, 5);
short int a[5] = {1, 2, 3, 4, 5};
insert_short_vector(&vec, a, 5, 0);
float b = average_short_vector(&vec);
PRINT(b);
// >> 3.00000
free_short_vector(&vec);
Definition at line 3167 of file vector.c.
                                       {
    short int sum = sum_short_vector(vec);
    float avg = sum / (float)vec->active_length;
    return avg;
}
References sum_short_vector().
Referenced by stdev_short_vector().
average_uchar_vector()
unsigned char average_uchar_vector (UChar * vec)
This function will return the average value of the data in a vector data structure of type Short
/param vec A vector data structure of type Char /return avg The average value in the input data structure of type Char
UChar vec;
init_uchar_vector(&vec, 5);
unsigned char a[5] = {1, 2, 3, 4, 5};
insert_uchar_vector(&vec, a, 5, 0);
unsigned char b = average_uchar_vector(&vec);
PRINT(b);
// >> 3.00000
free_uchar_vector(&vec);
Definition at line 3161 of file vector.c.
                                               {
    unsigned char sum = sum_uchar_vector(vec);
    unsigned char avg = sum / (unsigned char)vec->active_length;
    return avg;
}
References sum_uchar_vector().
Referenced by stdev_uchar_vector().
average_uint_vector()
float average_uint_vector (UInt * vec)
This function will return the average value of the data in a vector data structure of type UInt
/param vec A vector data structure of type UInt /return avg The average value in the input data structure of type UInt
UInt vec;
init_uint_vector(&vec, 5);
unsigned int a[5] = {1, 2, 3, 4, 5};
insert_uint_vector(&vec, a, 5, 0);
float b = average_uint_vector(&vec);
PRINT(b);
// >> 3.00000
free_uint_vector(&vec);
Definition at line 3188 of file vector.c.
                                     {
    unsigned int sum = sum_uint_vector(vec);
    float avg = sum / (float)vec->active_length;
    return avg;
}
References sum_uint_vector().
Referenced by stdev_uint_vector().
average_ullong_vector()
long double average_ullong_vector (ULLInt * vec)
This function will return the average value of the data in a vector data structure of type ULLInt
/param vec A vector data structure of type ULLInt /return avg The average value in the input data structure of type ULLInt
ULLInt vec;
init_ullong_vector(&vec, 5);
unsigned long long int a[5] = {1, 2, 3, 4, 5};
insert_ullong_vector(&vec, a, 5, 0);
long double b = average_ullong_vector(&vec);
PRINT(b);
// >> 3.00000
free_ullong_vector(&vec);
Definition at line 3216 of file vector.c.
                                               {
    unsigned long long int sum = sum_ullong_vector(vec);
    long double avg = sum / (long double)vec->active_length;
    return avg;
}
References sum_ullong_vector().
Referenced by stdev_ullong_vector().
average_ulong_vector()
double average_ulong_vector (ULInt * vec)
This function will return the average value of the data in a vector data structure of type ULInt
/param vec A vector data structure of type ULInt /return avg The average value in the input data structure of type ULInt
ULInt vec;
init_ulong_vector(&vec, 5);
unsigned long int a[5] = {1, 2, 3, 4, 5};
insert_ulong_vector(&vec, a, 5, 0);
double b = average_ulong_vector(&vec);
PRINT(b);
// >> 3.00000
free_ulong_vector(&vec);
Definition at line 3202 of file vector.c.
                                        {
    unsigned long int sum = sum_ulong_vector(vec);
    double avg = sum / (double)vec->active_length;
    return avg;
}
References sum_ulong_vector().
Referenced by stdev_ulong_vector().
average_ushort_vector()
float average_ushort_vector (UShort * vec)
This function will return the average value of the data in a vector data structure of type UShort
/param vec A vector data structure of type UShort /return avg The average value in the input data structure of type UShort
UShort vec;
init_ushort_vector(&vec, 5);
unsigned short int a[5] = {1, 2, 3, 4, 5};
insert_ushort_vector(&vec, a, 5, 0);
float b = average_ushort_vector(&vec);
PRINT(b);
// >> 3.00000
free_ushort_vector(&vec);
Definition at line 3174 of file vector.c.
                                         {
    unsigned short int sum = sum_ushort_vector(vec);
    float avg = sum / (float)vec->active_length;
    return avg;
}
References sum_ushort_vector().
Referenced by stdev_ushort_vector().
bool_vector_data()
bool bool_vector_data (Bool * vec, size_t index)
This function will retireve the data from a user specified index in a vector or array of type Bool
/param vec A linked list struct of type Bool /param index The index from where data will be retrieved /return dat An unsigned bool data point
Bool vec;
init_bool_vector(&vec);
bool a[5] = {true, true, false, false, true};
insert_bool_vector(&vec, a, 5, 0);
PRINT(bool_vector_data(&vec, 2));
// >> false
free_bool_vector(&vec);
Definition at line 4455 of file vector.c.
{ return vec->array[index]; }
char_vector_data()
char char_vector_data (Char * vec, size_t index)
This function will retireve the data from a user specified index in a vector or array of type Char
/param vec A linked list struct of type Char /param index The index from where data will be retrieved /return dat An unsigned bool data point
Char vec;
init_char_vector(&vec);
char a[5] = {'a', 'b', 'c', 'd', 'e'};
insert_char_vector(&vec, a, 5, 0);
PRINT(char_vector_data(&vec, 2));
// >> c
free_char_vector(&vec);
Definition at line 4452 of file vector.c.
{ return vec->array[index]; }
copy_bool_vector()
Bool copy_bool_vector (Bool * vec)
This function will create and return a deep copy of an Bool struct
/param vec A vector struct of type Bool
Definition at line 4559 of file vector.c.
                                 {
    Bool new_vec;
    init_bool_vector(&new_vec, vec->active_length);
    insert_bool_vector(&new_vec, vec->array, vec->active_length, 0);
    return new_vec;
}
References init_bool_vector(), and insert_bool_vector().
copy_char_vector()
Char copy_char_vector (Char * vec)
This function will create and return a deep copy of an Char struct
/param vec A vector struct of type Char
Definition at line 4551 of file vector.c.
                                 {
    Char new_vec;
    init_char_vector(&new_vec, vec->active_length);
    insert_char_vector(&new_vec, vec->array, vec->active_length, 0);
    return new_vec;
}
References init_char_vector(), and insert_char_vector().
copy_double_vector()
Dble copy_double_vector (Dble * vec)
This function will create and return a deep copy of an Dble struct
/param vec A vector struct of type Dble
Definition at line 4535 of file vector.c.
                                   {
    Dble new_vec;
    init_double_vector(&new_vec, vec->active_length);
    insert_double_vector(&new_vec, vec->array, vec->active_length, 0);
    return new_vec;
}
References init_double_vector(), and insert_double_vector().
copy_float_vector()
Flt copy_float_vector (Flt * vec)
This function will create and return a deep copy of an Flt struct
/param vec A vector struct of type Flt
Definition at line 4527 of file vector.c.
                                {
    Flt new_vec;
    init_float_vector(&new_vec, vec->active_length);
    insert_float_vector(&new_vec, vec->array, vec->active_length, 0);
    return new_vec;
}
References init_float_vector(), and insert_float_vector().
copy_int_vector()
Int copy_int_vector (Int * vec)
This function will create and return a deep copy of an Int struct
/param vec A vector struct of type Int
Definition at line 4479 of file vector.c.
                              {
    Int new_vec;
    init_int_vector(&new_vec, vec->active_length);
    insert_int_vector(&new_vec, vec->array, vec->active_length, 0);
    return new_vec;
}
References init_int_vector(), and insert_int_vector().
copy_ldouble_vector()
LDble copy_ldouble_vector (LDble * vec)
This function will create and return a deep copy of an LDble struct
/param vec A vector struct of type LDble
Definition at line 4543 of file vector.c.
                                      {
    LDble new_vec;
    init_ldouble_vector(&new_vec, vec->active_length);
    insert_ldouble_vector(&new_vec, vec->array, vec->active_length, 0);
    return new_vec;
}
References init_ldouble_vector(), and insert_ldouble_vector().
copy_llong_vector()
LLInt copy_llong_vector (LLInt * vec)
This function will create and return a deep copy of an LLInt struct
/param vec A vector struct of type LLInt
Definition at line 4511 of file vector.c.
                                    {
    LLInt new_vec;
    init_llong_vector(&new_vec, vec->active_length);
    insert_llong_vector(&new_vec, vec->array, vec->active_length, 0);
    return new_vec;
}
References init_llong_vector(), and insert_llong_vector().
copy_long_vector()
LInt copy_long_vector (LInt * vec)
This function will create and return a deep copy of an LInt struct
/param vec A vector struct of type LInt
Definition at line 4495 of file vector.c.
                                 {
    LInt new_vec;
    init_long_vector(&new_vec, vec->active_length);
    insert_long_vector(&new_vec, vec->array, vec->active_length, 0);
    return new_vec;
}
References init_long_vector(), and insert_long_vector().
copy_short_vector()
Short copy_short_vector (Short * vec)
This function will create and return a deep copy of an Short struct
/param vec A vector struct of type Short
Definition at line 4463 of file vector.c.
                                    {
    Short new_vec;
    init_short_vector(&new_vec, vec->active_length);
    insert_short_vector(&new_vec, vec->array, vec->active_length, 0);
    return new_vec;
}
References init_short_vector(), and insert_short_vector().
copy_string_vector()
String copy_string_vector (String * vec)
This function will create and return a deep copy of an String struct
/param vec A vector struct of type String
Definition at line 4567 of file vector.c.
                                       {
    String new_vec;
    init_string_vector(&new_vec);
    for (size_t i = 0; i < vec->active_length; i++) {
        push_string_vector(&new_vec, vec->array[i], new_vec.active_length);
    }
    return new_vec;
}
References String::active_length, String::array, init_string_vector(), and push_string_vector().
copy_uint_vector()
UInt copy_uint_vector (UInt * vec)
This function will create and return a deep copy of an UInt struct
/param vec A vector struct of type UInt
Definition at line 4487 of file vector.c.
                                 {
    UInt new_vec;
    init_uint_vector(&new_vec, vec->active_length);
    insert_uint_vector(&new_vec, vec->array, vec->active_length, 0);
    return new_vec;
}
References init_uint_vector(), and insert_uint_vector().
copy_ullong_vector()
ULLInt copy_ullong_vector (ULLInt * vec)
This function will create and return a deep copy of an ULLInt struct
/param vec A vector struct of type ULLInt
Definition at line 4519 of file vector.c.
                                       {
    ULLInt new_vec;
    init_ullong_vector(&new_vec, vec->active_length);
    insert_ullong_vector(&new_vec, vec->array, vec->active_length, 0);
    return new_vec;
}
References init_ullong_vector(), and insert_ullong_vector().
copy_ulong_vector()
ULInt copy_ulong_vector (ULInt * vec)
This function will create and return a deep copy of an ULInt struct
/param vec A vector struct of type ULInt
Definition at line 4503 of file vector.c.
                                    {
    ULInt new_vec;
    init_ulong_vector(&new_vec, vec->active_length);
    insert_ulong_vector(&new_vec, vec->array, vec->active_length, 0);
    return new_vec;
}
References init_ulong_vector(), and insert_ulong_vector().
copy_ushort_vector()
UShort copy_ushort_vector (UShort * vec)
This function will create and return a deep copy of an UShort struct
/param vec A vector struct of type UShort
Definition at line 4471 of file vector.c.
                                       {
    UShort new_vec;
    init_ushort_vector(&new_vec, vec->active_length);
    insert_ushort_vector(&new_vec, vec->array, vec->active_length, 0);
    return new_vec;
}
References init_ushort_vector(), and insert_ushort_vector().
cumsum_char_vector()
Char cumsum_char_vector (Char * vec)
This function will return an Char vector container that holds an array containing the cumulative sum of the values in the input array
/param vec A vector container of type Char /return return_vec A vector container of type Char
Char vec;
init_char_vector(&vec, 5);
char a[5] = {1, 2, 3, 4, 5};
insert_char_vector(&vec, a, 5, 0);
Char cum_vec = cumsum_char_vector(&vec);
PRINT(vum_vec);
[ 1, 3, 6, 10, 15 ]
free_char_vector(&vec);
Definition at line 2996 of file vector.c.
                                   {
    Char new_vec;
    init_char_vector(&new_vec, vec->active_length);
    char sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
        push_char_vector(&new_vec, sum, new_vec.active_length);
    }
    return new_vec;
}
References init_char_vector(), and push_char_vector().
cumsum_double_vector()
Dble cumsum_double_vector (Dble * vec)
This function will return an Dble vector container that holds an array containing the cumulative sum of the values in the input array
/param vec A vector container of type Dble /return return_vec A vector container of type Dble
Dble vec;
init_double_vector(&vec, 5);
double a[5] = {1, 2, 3, 4, 5};
insert_double_vector(&vec, a, 5, 0);
Dble cum_vec = cumsum_double_vector(&vec);
PRINT(vum_vec);
[ 1, 3, 6, 10, 15 ]
free_double_vector(&vec);
Definition at line 3128 of file vector.c.
                                     {
    Dble new_vec;
    init_double_vector(&new_vec, vec->active_length);
    double sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
        push_double_vector(&new_vec, sum, new_vec.active_length);
    }
    return new_vec;
}
References init_double_vector(), and push_double_vector().
cumsum_float_vector()
Flt cumsum_float_vector (Flt * vec)
This function will return an Flt vector container that holds an array containing the cumulative sum of the values in the input array
/param vec A vector container of type Flt /return return_vec A vector container of type Flt
Flt vec;
init_float_vector(&vec, 5);
float a[5] = {1, 2, 3, 4, 5};
insert_float_vector(&vec, a, 5, 0);
Flt cum_vec = cumsum_float_vector(&vec);
PRINT(vum_vec);
[ 1, 3, 6, 10, 15 ]
free_float_vector(&vec);
Definition at line 3116 of file vector.c.
                                  {
    Flt new_vec;
    init_float_vector(&new_vec, vec->active_length);
    float sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
        push_float_vector(&new_vec, sum, new_vec.active_length);
    }
    return new_vec;
}
References init_float_vector(), and push_float_vector().
cumsum_int_vector()
Int cumsum_int_vector (Int * vec)
This function will return an Int vector container that holds an array containing the cumulative sum of the values in the input array
/param vec A vector container of type Int /return return_vec A vector container of type Int
Int vec;
init_int_vector(&vec, 5);
int a[5] = {1, 2, 3, 4, 5};
insert_int_vector(&vec, a, 5, 0);
Int cum_vec = cumsum_int_vector(&vec);
PRINT(vum_vec);
[ 1, 3, 6, 10, 15 ]
free_int_vector(&vec);
Definition at line 3044 of file vector.c.
                                {
    Int new_vec;
    init_int_vector(&new_vec, vec->active_length);
    int sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
        push_int_vector(&new_vec, sum, new_vec.active_length);
    }
    return new_vec;
}
References init_int_vector(), and push_int_vector().
cumsum_ldouble_vector()
LDble cumsum_ldouble_vector (LDble * vec)
This function will return an LDble vector container that holds an array containing the cumulative sum of the values in the input array
/param vec A vector container of type LDble /return return_vec A vector container of type LDble
LDble vec;
init_ldouble_vector(&vec, 5);
long double a[5] = {1, 2, 3, 4, 5};
insert_ldouble_vector(&vec, a, 5, 0);
LDble cum_vec = cumsum_ldouble_vector(&vec);
PRINT(vum_vec);
[ 1, 3, 6, 10, 15 ]
free_ldouble_vector(&vec);
Definition at line 3140 of file vector.c.
                                        {
    LDble new_vec;
    init_ldouble_vector(&new_vec, vec->active_length);
    long double sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
        push_ldouble_vector(&new_vec, sum, new_vec.active_length);
    }
    return new_vec;
}
References init_ldouble_vector(), and push_ldouble_vector().
cumsum_llong_vector()
LLInt cumsum_llong_vector (LLInt * vec)
This function will return an LLInt vector container that holds an array containing the cumulative sum of the values in the input array
/param vec A vector container of type LLInt /return return_vec A vector container of type LLInt
LLInt vec;
init_llong_vector(&vec, 5);
long long int a[5] = {1, 2, 3, 4, 5};
insert_llong_vector(&vec, a, 5, 0);
LLInt cum_vec = cumsum_llong_vector(&vec);
PRINT(vum_vec);
[ 1, 3, 6, 10, 15 ]
free_llong_vector(&vec);
Definition at line 3092 of file vector.c.
                                      {
    LLInt new_vec;
    init_llong_vector(&new_vec, vec->active_length);
    long long int sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
        push_llong_vector(&new_vec, sum, new_vec.active_length);
    }
    return new_vec;
}
References init_llong_vector(), and push_llong_vector().
cumsum_long_vector()
LInt cumsum_long_vector (LInt * vec)
This function will return an LInt vector container that holds an array containing the cumulative sum of the values in the input array
/param vec A vector container of type LInt /return return_vec A vector container of type LInt
LInt vec;
init_long_vector(&vec, 5);
long int a[5] = {1, 2, 3, 4, 5};
insert_long_vector(&vec, a, 5, 0);
LInt cum_vec = cumsum_long_vector(&vec);
PRINT(vum_vec);
[ 1, 3, 6, 10, 15 ]
free_long_vector(&vec);
Definition at line 3068 of file vector.c.
                                   {
    LInt new_vec;
    init_long_vector(&new_vec, vec->active_length);
    long int sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
        push_long_vector(&new_vec, sum, new_vec.active_length);
    }
    return new_vec;
}
References init_long_vector(), and push_long_vector().
cumsum_short_vector()
Short cumsum_short_vector (Short * vec)
This function will return an Short vector container that holds an array containing the cumulative sum of the values in the input array
/param vec A vector container of type Short /return return_vec A vector container of type UShort
Short vec;
init_short_vector(&vec, 5);
short int a[5] = {1, 2, 3, 4, 5};
insert_short_vector(&vec, a, 5, 0);
Short cum_vec = cumsum_short_vector(&vec);
PRINT(vum_vec);
[ 1, 3, 6, 10, 15 ]
free_short_vector(&vec);
Definition at line 3020 of file vector.c.
                                      {
    Short new_vec;
    init_short_vector(&new_vec, vec->active_length);
    short int sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
        push_short_vector(&new_vec, sum, new_vec.active_length);
    }
    return new_vec;
}
References init_short_vector(), and push_short_vector().
cumsum_uchar_vector()
UChar cumsum_uchar_vector (UChar * vec)
This function will return an UChar vector container that holds an array containing the cumulative sum of the values in the input array
/param vec A vector container of type UChar /return return_vec A vector container of type UChar
UChar vec;
init_uchar_vector(&vec, 5);
unsigned char a[5] = {1, 2, 3, 4, 5};
insert_uchar_vector(&vec, a, 5, 0);
UChar cum_vec = cumsum_uchar_vector(&vec);
PRINT(vum_vec);
[ 1, 3, 6, 10, 15 ]
free_uchar_vector(&vec);
Definition at line 3008 of file vector.c.
                                      {
    UChar new_vec;
    init_uchar_vector(&new_vec, vec->active_length);
    unsigned char sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
        push_uchar_vector(&new_vec, sum, new_vec.active_length);
    }
    return new_vec;
}
References init_uchar_vector(), and push_uchar_vector().
cumsum_uint_vector()
UInt cumsum_uint_vector (UInt * vec)
This function will return an UInt vector container that holds an array containing the cumulative sum of the values in the input array
/param vec A vector container of type UInt /return return_vec A vector container of type UInt
UInt vec;
init_uint_vector(&vec, 5);
unsigned int a[5] = {1, 2, 3, 4, 5};
insert_uint_vector(&vec, a, 5, 0);
UInt cum_vec = cumsum_uint_vector(&vec);
PRINT(vum_vec);
[ 1, 3, 6, 10, 15 ]
free_uint_vector(&vec);
Definition at line 3056 of file vector.c.
                                   {
    UInt new_vec;
    init_uint_vector(&new_vec, vec->active_length);
    unsigned int sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
        push_uint_vector(&new_vec, sum, new_vec.active_length);
    }
    return new_vec;
}
References init_uint_vector(), and push_uint_vector().
cumsum_ullong_vector()
ULLInt cumsum_ullong_vector (ULLInt * vec)
This function will return an ULLInt vector container that holds an array containing the cumulative sum of the values in the input array
/param vec A vector container of type ULLInt /return return_vec A vector container of type ULLInt
ULLInt vec;
init_ullong_vector(&vec, 5);
unsigned long long int a[5] = {1, 2, 3, 4, 5};
insert_ullong_vector(&vec, a, 5, 0);
ULLInt cum_vec = cumsum_ullong_vector(&vec);
PRINT(vum_vec);
[ 1, 3, 6, 10, 15 ]
free_ullong_vector(&vec);
Definition at line 3104 of file vector.c.
                                         {
    ULLInt new_vec;
    init_ullong_vector(&new_vec, vec->active_length);
    unsigned long long int sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
        push_ullong_vector(&new_vec, sum, new_vec.active_length);
    }
    return new_vec;
}
References init_ullong_vector(), and push_ullong_vector().
cumsum_ulong_vector()
ULInt cumsum_ulong_vector (ULInt * vec)
This function will return an ULInt vector container that holds an array containing the cumulative sum of the values in the input array
/param vec A vector container of type ULInt /return return_vec A vector container of type ULInt
ULInt vec;
init_ulong_vector(&vec, 5);
unsigned long int a[5] = {1, 2, 3, 4, 5};
insert_ulong_vector(&vec, a, 5, 0);
ULInt cum_vec = cumsum_ulong_vector(&vec);
PRINT(vum_vec);
[ 1, 3, 6, 10, 15 ]
free_ulong_vector(&vec);
Definition at line 3080 of file vector.c.
                                      {
    ULInt new_vec;
    init_ulong_vector(&new_vec, vec->active_length);
    unsigned long int sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
        push_ulong_vector(&new_vec, sum, new_vec.active_length);
    }
    return new_vec;
}
References init_ulong_vector(), and push_ulong_vector().
cumsum_ushort_vector()
UShort cumsum_ushort_vector (UShort * vec)
This function will return an UShort vector container that holds an array containing the cumulative sum of the values in the input array
/param vec A vector container of type UShort /return return_vec A vector container of type UShort
UShort vec;
init_ushort_vector(&vec, 5);
unsigned short int a[5] = {1, 2, 3, 4, 5};
insert_ushort_vector(&vec, a, 5, 0);
UShort cum_vec = cumsum_ushort_vector(&vec);
PRINT(vum_vec);
[ 1, 3, 6, 10, 15 ]
free_ushort_vector(&vec);
Definition at line 3032 of file vector.c.
                                         {
    UShort new_vec;
    init_ushort_vector(&new_vec, vec->active_length);
    unsigned short int sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
        push_ushort_vector(&new_vec, sum, new_vec.active_length);
    }
    return new_vec;
}
References init_ushort_vector(), and push_ushort_vector().
delete_bool_vector_duplicates()
void delete_bool_vector_duplicates (Bool * vec)
This function will delete all duplicate values in a Bool struct, with exception of the first instance of the variable.
/param vec A struct container of type Bool
Char vec;
init_bool_vector(vec, 6);
push_bool_vector(vec, true);
push_bool_vector(vec, true);
push_bool_vector(vec, false);
push_bool_vector(vec, false);
push_bool_vector(vec, true);
push_bool_vector(vec, true);
delete_bool_vector_duplicates(vec);
PRINT(vec);
[ true, false ]
free_bool_vector(&vec);
Definition at line 2037 of file vector.c.
                                              {
    for (size_t i = 0; i < vec->active_length - 1; i++) {
        for (size_t j = i + 1; j < vec->active_length; j++) {
            if (vec->array[j] == vec->array[i]) {
                pop_bool_vector_index(vec, j);
                j--;
            }
        }
    }
}
References pop_bool_vector_index().
delete_char_vector_duplicates()
void delete_char_vector_duplicates (Char * vec)
This function will delete all duplicate values in a Char struct, with exception of the first instance of the variable.
/param vec A struct container of type Char
Char vec;
init_char_vector(vec, 6);
push_char_vector(vec, 'a');
push_char_vector(vec, 'a');
push_char_vector(vec, 'b');
push_char_vector(vec, 'b');
push_char_vector(vec, 'c');
push_char_vector(vec, 'c');
delete_char_vector_duplicates(vec);
PRINT(vec);
[ a, b, c ]
free_char_vector(&vec);
Definition at line 2013 of file vector.c.
                                              {
    for (size_t i = 0; i < vec->active_length - 1; i++) {
        for (size_t j = i + 1; j < vec->active_length; j++) {
            if (vec->array[j] == vec->array[i]) {
                pop_char_vector_index(vec, j);
                j--;
            }
        }
    }
}
References pop_char_vector_index().
delete_double_vector_duplicates()
void delete_double_vector_duplicates (Dble * vec)
This function will delete all duplicate values in a Dble struct, with exception of the first instance of the variable.
/param vec A struct container of type Dble
Dble vec;
init_double_vector(vec, 6);
push_double_vector(vec, 1.);
push_double_vector(vec, 1.);
push_double_vector(vec, 2.);
push_double_vector(vec, 2.);
push_double_vector(vec, 3.);
push_double_vector(vec, 3.);
delete_double_vector_duplicates(vec);
PRINT(vec);
[ 1, 2, 3 ]
free_double_vector(&vec);
Definition at line 1989 of file vector.c.
                                                {
    for (size_t i = 0; i < vec->active_length - 1; i++) {
        for (size_t j = i + 1; j < vec->active_length; j++) {
            if (vec->array[j] == vec->array[i]) {
                pop_double_vector_index(vec, j);
                j--;
            }
        }
    }
}
References pop_double_vector_index().
delete_float_vector_duplicates()
void delete_float_vector_duplicates (Flt * vec)
This function will delete all duplicate values in a Flt struct, with exception of the first instance of the variable.
/param vec A struct container of type Flt
Flt vec;
init_float_vector(vec, 6);
push_float_vector(vec, 1.f);
push_float_vector(vec, 1.f);
push_float_vector(vec, 2.f);
push_float_vector(vec, 2.f);
push_float_vector(vec, 3.f);
push_float_vector(vec, 3.f);
delete_float_vector_duplicates(vec);
PRINT(vec);
[ 1, 2, 3 ]
free_float_vector(&vec);
Definition at line 1977 of file vector.c.
                                              {
    for (size_t i = 0; i < vec->active_length - 1; i++) {
        for (size_t j = i + 1; j < vec->active_length; j++) {
            if (vec->array[j] == vec->array[i]) {
                pop_float_vector_index(vec, j);
                j--;
            }
        }
    }
}
References pop_float_vector_index().
delete_int_vector_duplicates()
void delete_int_vector_duplicates (Int * vec)
This function will delete all duplicate values in an Int struct, with exception of the first instance of the variable.
/param vec A struct container of type Int
Int vec;
init_int_vector(vec, 6);
push_int_vector(vec, 1);
push_int_vector(vec, 1);
push_int_vector(vec, 2);
push_int_vector(vec, 2);
push_int_vector(vec, 3);
push_int_vector(vec, 3);
delete_int_vector_duplicates(vec);
PRINT(vec);
[ 1, 2, 3 ]
free_int_vector(&vec);
Definition at line 1905 of file vector.c.
                                            {
    for (size_t i = 0; i < vec->active_length - 1; i++) {
        for (size_t j = i + 1; j < vec->active_length; j++) {
            if (vec->array[j] == vec->array[i]) {
                pop_int_vector_index(vec, j);
                j--;
            }
        }
    }
}
References pop_int_vector_index().
delete_ldouble_vector_duplicates()
void delete_ldouble_vector_duplicates (LDble * vec)
This function will delete all duplicate values in a LDble struct, with exception of the first instance of the variable.
/param vec A struct container of type LDble
LDble vec;
init_ldouble_vector(vec, 6);
push_ldouble_vector(vec, 1.);
push_ldouble_vector(vec, 1.);
push_ldouble_vector(vec, 2.);
push_ldouble_vector(vec, 2.);
push_ldouble_vector(vec, 3.);
push_ldouble_vector(vec, 3.);
delete_ldouble_vector_duplicates(vec);
PRINT(vec);
[ 1, 2, 3 ]
free_ldouble_vector(&vec);
Definition at line 2001 of file vector.c.
                                                  {
    for (size_t i = 0; i < vec->active_length - 1; i++) {
        for (size_t j = i + 1; j < vec->active_length; j++) {
            if (vec->array[j] == vec->array[i]) {
                pop_ldouble_vector_index(vec, j);
                j--;
            }
        }
    }
}
References pop_ldouble_vector_index().
delete_llong_vector_duplicates()
void delete_llong_vector_duplicates (LLInt * vec)
This function will delete all duplicate values in a LLInt struct, with exception of the first instance of the variable.
/param vec A struct container of type LLInt
LLInt vec;
init_llong_vector(vec, 6);
push_llong_vector(vec, 1);
push_llong_vector(vec, 1);
push_llong_vector(vec, 2);
push_llong_vector(vec, 2);
push_llong_vector(vec, 3);
push_llong_vector(vec, 3);
delete_llong_vector_duplicates(vec);
PRINT(vec);
[ 1, 2, 3 ]
free_llong_vector(&vec);
Definition at line 1953 of file vector.c.
                                                {
    for (size_t i = 0; i < vec->active_length - 1; i++) {
        for (size_t j = i + 1; j < vec->active_length; j++) {
            if (vec->array[j] == vec->array[i]) {
                pop_llong_vector_index(vec, j);
                j--;
            }
        }
    }
}
References pop_llong_vector_index().
delete_long_vector_duplicates()
void delete_long_vector_duplicates (LInt * vec)
This function will delete all duplicate values in a LInt struct, with exception of the first instance of the variable.
/param vec A struct container of type LInt
LInt vec;
init_long_vector(vec, 6);
push_long_vector(vec, 1);
push_long_vector(vec, 1);
push_long_vector(vec, 2);
push_long_vector(vec, 2);
push_long_vector(vec, 3);
push_long_vector(vec, 3);
delete_long_vector_duplicates(vec);
PRINT(vec);
[ 1, 2, 3 ]
free_long_vector(&vec);
Definition at line 1929 of file vector.c.
                                              {
    for (size_t i = 0; i < vec->active_length - 1; i++) {
        for (size_t j = i + 1; j < vec->active_length; j++) {
            if (vec->array[j] == vec->array[i]) {
                pop_long_vector_index(vec, j);
                j--;
            }
        }
    }
}
References pop_long_vector_index().
delete_short_vector_duplicates()
void delete_short_vector_duplicates (Short * vec)
This function will delete all duplicate values in an Short struct, with exception of the first instance of the variable.
/param vec A struct container of type Short
Short vec;
init_short_vector(vec, 6);
push_short_vector(vec, 1);
push_short_vector(vec, 1);
push_short_vector(vec, 2);
push_short_vector(vec, 2);
push_short_vector(vec, 3);
push_short_vector(vec, 3);
delete_short_vector_duplicates(vec);
PRINT(vec);
[ 1, 2, 3 ]
free_short_vector(&vec);
Definition at line 1881 of file vector.c.
                                                {
    for (size_t i = 0; i < vec->active_length - 1; i++) {
        for (size_t j = i + 1; j < vec->active_length; j++) {
            if (vec->array[j] == vec->array[i]) {
                pop_short_vector_index(vec, j);
                j--;
            }
        }
    }
}
References pop_short_vector_index().
delete_string_vector_duplicates()
void delete_string_vector_duplicates (String * vec)
This function will delete all duplicate values in a String struct, with exception of the first instance of the variable
/param vec A struct container of type String
init_string_vector(vec);
push_string_vector(vec, "One", 0);
push_string_vector(vec, "Two", 1);
push_string_vector(vec, "One", 2);
push_string_vector(vec, "One", 3);
push_string_vector(vec, "Three", 4);
push_string_vector(vec, "Two", 5);
delete_string_vector_duplicates(vec);
PRINT(vec);
// >> [One, Two, Three ]
free_string_vector(&vec);
Definition at line 2049 of file vector.c.
                                                  {
    int test;
    for (size_t i = 0; i < vec->active_length - 1; i++) {
        for (size_t j = i + 1; j < vec->active_length; j++) {
            test = strcmp(vec->array[i], vec->array[j]);
            if (test == 0) {
                pop_string_vector_index(vec, j);
                j--;
            }
        }
    }
}
References String::active_length, String::array, and pop_string_vector_index().
delete_uchar_vector_duplicates()
void delete_uchar_vector_duplicates (UChar * vec)
This function will delete all duplicate values in a Char struct, with exception of the first instance of the variable.
/param vec A struct container of type Char
UChar vec;
init_uchar_vector(vec, 6);
push_uchar_vector(vec, 'a');
push_uchar_vector(vec, 'a');
push_uchar_vector(vec, 'b');
push_uchar_vector(vec, 'b');
push_uchar_vector(vec, 'c');
push_uchar_vector(vec, 'c');
delete_uchar_vector_duplicates(vec);
PRINT(vec);
[ a, b, c ]
free_uchar_vector(&vec);
Definition at line 2025 of file vector.c.
                                                {
    for (size_t i = 0; i < vec->active_length - 1; i++) {
        for (size_t j = i + 1; j < vec->active_length; j++) {
            if (vec->array[j] == vec->array[i]) {
                pop_uchar_vector_index(vec, j);
                j--;
            }
        }
    }
}
References pop_uchar_vector_index().
delete_uint_vector_duplicates()
void delete_uint_vector_duplicates (UInt * vec)
This function will delete all duplicate values in a UInt struct, with exception of the first instance of the variable.
/param vec A struct container of type UInt
UInt vec;
init_uint_vector(vec, 6);
push_uint_vector(vec, 1);
push_uint_vector(vec, 1);
push_uint_vector(vec, 2);
push_uint_vector(vec, 2);
push_uint_vector(vec, 3);
push_uint_vector(vec, 3);
delete_uint_vector_duplicates(vec);
PRINT(vec);
[ 1, 2, 3 ]
free_uint_vector(&vec);
Definition at line 1917 of file vector.c.
                                              {
    for (size_t i = 0; i < vec->active_length - 1; i++) {
        for (size_t j = i + 1; j < vec->active_length; j++) {
            if (vec->array[j] == vec->array[i]) {
                pop_uint_vector_index(vec, j);
                j--;
            }
        }
    }
}
References pop_uint_vector_index().
delete_ullong_vector_duplicates()
void delete_ullong_vector_duplicates (ULLInt * vec)
This function will delete all duplicate values in a ULLInt struct, with exception of the first instance of the variable.
/param vec A struct container of type ULLInt
ULLInt vec;
init_ullong_vector(vec, 6);
push_ullong_vector(vec, 1);
push_ullong_vector(vec, 1);
push_ullong_vector(vec, 2);
push_ullong_vector(vec, 2);
push_ullong_vector(vec, 3);
push_ullong_vector(vec, 3);
delete_ullong_vector_duplicates(vec);
PRINT(vec);
[ 1, 2, 3 ]
free_ullong_vector(&vec);
Definition at line 1965 of file vector.c.
                                                  {
    for (size_t i = 0; i < vec->active_length - 1; i++) {
        for (size_t j = i + 1; j < vec->active_length; j++) {
            if (vec->array[j] == vec->array[i]) {
                pop_ullong_vector_index(vec, j);
                j--;
            }
        }
    }
}
References pop_ullong_vector_index().
delete_ulong_vector_duplicates()
void delete_ulong_vector_duplicates (ULInt * vec)
This function will delete all duplicate values in a ULInt struct, with exception of the first instance of the variable.
/param vec A struct container of type ULInt
ULInt vec;
init_ulong_vector(vec, 6);
push_ulong_vector(vec, 1);
push_ulong_vector(vec, 1);
push_ulong_vector(vec, 2);
push_ulong_vector(vec, 2);
push_ulong_vector(vec, 3);
push_ulong_vector(vec, 3);
delete_ulong_vector_duplicates(vec);
PRINT(vec);
[ 1, 2, 3 ]
free_ulong_vector(&vec);
Definition at line 1941 of file vector.c.
                                                {
    for (size_t i = 0; i < vec->active_length - 1; i++) {
        for (size_t j = i + 1; j < vec->active_length; j++) {
            if (vec->array[j] == vec->array[i]) {
                pop_ulong_vector_index(vec, j);
                j--;
            }
        }
    }
}
References pop_ulong_vector_index().
delete_ushort_vector_duplicates()
void delete_ushort_vector_duplicates (UShort * vec)
This function will delete all duplicate values in an UShort struct, with exception of the first instance of the variable.
/param vec A struct container of type UShort
UShort vec;
init_ushort_vector(vec, 6);
push_ushort_vector(vec, 1);
push_ushort_vector(vec, 1);
push_ushort_vector(vec, 2);
push_ushort_vector(vec, 2);
push_ushort_vector(vec, 3);
push_ushort_vector(vec, 3);
delete_ushort_vector_duplicates(vec);
PRINT(vec);
[ 1, 2, 3 ]
free_ushort_vector(&vec);
Definition at line 1893 of file vector.c.
                                                  {
    for (size_t i = 0; i < vec->active_length - 1; i++) {
        for (size_t j = i + 1; j < vec->active_length; j++) {
            if (vec->array[j] == vec->array[i]) {
                pop_ushort_vector_index(vec, j);
                j--;
            }
        }
    }
}
References pop_ushort_vector_index().
double_vector_data()
double double_vector_data (Dble * vec, size_t index)
This function will retireve the data from a user specified index in a vector or array of type Dble
/param vec A linked list struct of type Dble /param index The index from where data will be retrieved /return dat An unsigned bool data point
Dble vec;
init_double_vector(&vec);
double a[5] = {1, 2, 3, 4, 5};
insert_double_vector(&vec, a, 5, 0);
PRINT(double_vector_data(&vec, 2));
// >> 3.000
free_double_vector(&vec);
Definition at line 4446 of file vector.c.
{ return vec->array[index]; }
float_vector_data()
float float_vector_data (Flt * vec, size_t index)
This function will retireve the data from a user specified index in a vector or array of type Flt
/param vec A linked list struct of type Flt /param index The index from where data will be retrieved /return dat An unsigned bool data point
Flt vec;
init_float_vector(&vec);
float a[5] = {1, 2, 3, 4, 5};
insert_float_vector(&vec, a, 5, 0);
PRINT(float_vector_data(&vec, 2));
// >> 3.000
free_float_vector(&vec);
Definition at line 4443 of file vector.c.
{ return vec->array[index]; }
free_bool_vector()
void free_bool_vector (Bool * vec)
This function will free all memory from an Bool data type assuming the type was used for dynamically allocated memory. If the type was initialized for statically allocated memory, this function will write an error to stderror and return a value of -1 to the calling program.
/param vec A struct container of type Bool
Definition at line 1854 of file vector.c.
                                 {
    if (vec->dat_type == DYNAMIC) {
        free(vec->array);
        vec->array = NULL;
        vec->active_length = 0;
        vec->allocated_length = 0;
    }
    else {
        fprintf(stderr, "Struct in file %s on line %d must be DYNAMIC\n", __FILE__, __LINE__);
    }
}
References DYNAMIC.
free_char_vector()
void free_char_vector (Char * vec)
This function will free all memory from an Char data type assuming the type was used for dynamically allocated memory. If the type was initialized for statically allocated memory, this function will write an error to stderror and return a value of -1 to the calling program.
/param vec A struct container of type Char
Definition at line 1828 of file vector.c.
                                 {
    if (vec->dat_type == DYNAMIC) {
        free(vec->array);
        vec->array = NULL;
        vec->active_length = 0;
        vec->allocated_length = 0;
    }
    else {
        fprintf(stderr, "Struct in file %s on line %d must be DYNAMIC\n", __FILE__, __LINE__);
    }
}
References DYNAMIC.
free_double_vector()
void free_double_vector (Dble * vec)
This function will free all memory from an Dble data type assuming the type was used for dynamically allocated memory. If the type was initialized for statically allocated memory, this function will write an error to stderror and return a value of -1 to the calling program.
/param vec A struct container of type Dble
Definition at line 1802 of file vector.c.
                                   {
    if (vec->dat_type == DYNAMIC) {
        free(vec->array);
        vec->array = NULL;
        vec->active_length = 0;
        vec->allocated_length = 0;
    }
    else {
        fprintf(stderr, "Struct in file %s on line %d must be DYNAMIC\n", __FILE__, __LINE__);
    }
}
References DYNAMIC.
free_float_vector()
void free_float_vector (Flt * vec)
This function will free all memory from an Flt data type assuming the type was used for dynamically allocated memory. If the type was initialized for statically allocated memory, this function will write an error to stderror and return a value of -1 to the calling program.
/param vec A struct container of type Flt
Definition at line 1789 of file vector.c.
                                 {
    if (vec->dat_type == DYNAMIC) {
        free(vec->array);
        vec->array = NULL;
        vec->active_length = 0;
        vec->allocated_length = 0;
    }
    else {
        fprintf(stderr, "Struct in file %s on line %d must be DYNAMIC\n", __FILE__, __LINE__);
    }
}
References DYNAMIC.
free_int_vector()
void free_int_vector (Int * vec)
This function will free all memory from an Int data type assuming the type was used for dynamically allocated memory. If the type was initialized for statically allocated memory, this function will write an error to stderror and return a value of -1 to the calling program.
/param vec A struct container of type Int
Definition at line 1711 of file vector.c.
                               {
    if (vec->dat_type == DYNAMIC) {
        free(vec->array);
        vec->array = NULL;
        vec->active_length = 0;
        vec->allocated_length = 0;
    }
    else {
        fprintf(stderr, "Struct in file %s on line %d must be DYNAMIC\n", __FILE__, __LINE__);
    }
}
References DYNAMIC.
free_ldouble_vector()
void free_ldouble_vector (LDble * vec)
This function will free all memory from an LDble data type assuming the type was used for dynamically allocated memory. If the type was initialized for statically allocated memory, this function will write an error to stderror and return a value of -1 to the calling program.
/param vec A struct container of type LDble
Definition at line 1815 of file vector.c.
                                     {
    if (vec->dat_type == DYNAMIC) {
        free(vec->array);
        vec->array = NULL;
        vec->active_length = 0;
        vec->allocated_length = 0;
    }
    else {
        fprintf(stderr, "Struct in file %s on line %d must be DYNAMIC\n", __FILE__, __LINE__);
    }
}
References DYNAMIC.
free_llong_vector()
void free_llong_vector (LLInt * vec)
This function will free all memory from an LLInt data type assuming the type was used for dynamically allocated memory. If the type was initialized for statically allocated memory, this function will write an error to stderror and return a value of -1 to the calling program.
/param vec A struct container of type LLInt
Definition at line 1763 of file vector.c.
                                   {
    if (vec->dat_type == DYNAMIC) {
        free(vec->array);
        vec->array = NULL;
        vec->active_length = 0;
        vec->allocated_length = 0;
    }
    else {
        fprintf(stderr, "Struct in file %s on line %d must be DYNAMIC\n", __FILE__, __LINE__);
    }
}
References DYNAMIC.
free_long_vector()
void free_long_vector (LInt * vec)
This function will free all memory from an LInt data type assuming the type was used for dynamically allocated memory. If the type was initialized for statically allocated memory, this function will write an error to stderror and return a value of -1 to the calling program.
/param vec A struct container of type LInt
Definition at line 1737 of file vector.c.
                                 {
    if (vec->dat_type == DYNAMIC) {
        free(vec->array);
        vec->array = NULL;
        vec->active_length = 0;
        vec->allocated_length = 0;
    }
    else {
        fprintf(stderr, "Struct in file %s on line %d must be DYNAMIC\n", __FILE__, __LINE__);
    }
}
References DYNAMIC.
free_short_vector()
void free_short_vector (Short * vec)
This function will free all memory from an Short data type assuming the type was used for dynamically allocated memory. If the type was initialized for statically allocated memory, this function will write an error to stderror and return a value of -1 to the calling program.
/param vec A struct container of type Short
Definition at line 1685 of file vector.c.
                                   {
    if (vec->dat_type == DYNAMIC) {
        free(vec->array);
        vec->array = NULL;
        vec->active_length = 0;
        vec->allocated_length = 0;
    }
    else {
        fprintf(stderr, "Struct in file %s on line %d must be DYNAMIC\n", __FILE__, __LINE__);
    }
}
References DYNAMIC.
free_string_vector()
void free_string_vector (String * vec)
This function will free all memory from anString data type assuming the type was used for dynamically allocated memory.
/param vec A struct container of type String
Definition at line 1867 of file vector.c.
                                     {
    if (vec != NULL) {
        for (size_t i = 0; i < vec->active_length; i++) {
            free(vec->array[i]);
        }
        free(vec->array);
        vec->array = NULL;
        vec->active_length = 0;
    }
}
References String::active_length, and String::array.
free_uchar_vector()
void free_uchar_vector (UChar * vec)
This function will free all memory from an Char data type assuming the type was used for dynamically allocated memory. If the type was initialized for statically allocated memory, this function will write an error to stderror and return a value of -1 to the calling program.
/param vec A struct container of type UChar
Definition at line 1841 of file vector.c.
                                   {
    if (vec->dat_type == DYNAMIC) {
        free(vec->array);
        vec->array = NULL;
        vec->active_length = 0;
        vec->allocated_length = 0;
    }
    else {
        fprintf(stderr, "Struct in file %s on line %d must be DYNAMIC\n", __FILE__, __LINE__);
    }
}
References DYNAMIC.
free_uint_vector()
void free_uint_vector (UInt * vec)
This function will free all memory from an UInt data type assuming the type was used for dynamically allocated memory. If the type was initialized for statically allocated memory, this function will write an error to stderror and return a value of -1 to the calling program.
/param vec A struct container of type UInt
Definition at line 1724 of file vector.c.
                                 {
    if (vec->dat_type == DYNAMIC) {
        free(vec->array);
        vec->array = NULL;
        vec->active_length = 0;
        vec->allocated_length = 0;
    }
    else {
        fprintf(stderr, "Struct in file %s on line %d must be DYNAMIC\n", __FILE__, __LINE__);
    }
}
References DYNAMIC.
free_ullong_vector()
void free_ullong_vector (ULLInt * vec)
This function will free all memory from an ULLInt data type assuming the type was used for dynamically allocated memory. If the type was initialized for statically allocated memory, this function will write an error to stderror and return a value of -1 to the calling program.
/param vec A struct container of type ULLInt
Definition at line 1776 of file vector.c.
                                     {
    if (vec->dat_type == DYNAMIC) {
        free(vec->array);
        vec->array = NULL;
        vec->active_length = 0;
        vec->allocated_length = 0;
    }
    else {
        fprintf(stderr, "Struct in file %s on line %d must be DYNAMIC\n", __FILE__, __LINE__);
    }
}
References DYNAMIC.
free_ulong_vector()
void free_ulong_vector (ULInt * vec)
This function will free all memory from an ULInt data type assuming the type was used for dynamically allocated memory. If the type was initialized for statically allocated memory, this function will write an error to stderror and return a value of -1 to the calling program.
/param vec A struct container of type ULInt
Definition at line 1750 of file vector.c.
                                   {
    if (vec->dat_type == DYNAMIC) {
        free(vec->array);
        vec->array = NULL;
        vec->active_length = 0;
        vec->allocated_length = 0;
    }
    else {
        fprintf(stderr, "Struct in file %s on line %d must be DYNAMIC\n", __FILE__, __LINE__);
    }
}
References DYNAMIC.
free_ushort_vector()
void free_ushort_vector (UShort * vec)
This function will free all memory from an UShort data type assuming the type was used for dynamically allocated memory. If the type was initialized for statically allocated memory, this function will write an error to stderror and return a value of -1 to the calling program.
/param vec A struct container of type UShort
Definition at line 1698 of file vector.c.
                                     {
    if (vec->dat_type == DYNAMIC) {
        free(vec->array);
        vec->array = NULL;
        vec->active_length = 0;
        vec->allocated_length = 0;
    }
    else {
        fprintf(stderr, "Struct in file %s on line %d must be DYNAMIC\n", __FILE__, __LINE__);
    }
}
References DYNAMIC.
init_bool_array()
void init_bool_array (Bool * vec, bool * arr, size_t allocated_length, size_t active_length)
This funciton will initialize an array struct container of type Bool
/param vec A vector struct container of type Bool /param arr An array of type unsigned bool /param allocated_length The allocated length of the array /param active_length The number of acticaly populated indices in the array arr
Char arr;
char a[5] = {trye, true};
init_bool_array(&arr, a, 5, 2);
// Since the array is statically allocated it does not need to be freed
Definition at line 340 of file vector.c.
                                                                                          {
    vec->array = arr;
    vec->dat_type = STATIC;
    vec->active_length = active_length;
    vec->allocated_length = allocated_length;
}
References STATIC.
init_bool_vector()
int init_bool_vector (Bool * vec, size_t length)
Definition at line 212 of file vector.c.
                                               {
    // Make initial vector allocation
    bool *ptr = malloc(length * sizeof(bool));
    if (ptr == NULL) {
        fprintf(stderr, "malloc failed in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->dat_type = DYNAMIC;
    vec->allocated_length = length;
    vec->active_length = 0;
    vec->array = ptr;
    return 1;
}
References DYNAMIC.
Referenced by copy_bool_vector().
init_char_array()
void init_char_array (Char * vec, char * arr, size_t allocated_length, size_t active_length)
This funciton will initialize an array struct container of type Char
/param vec A vector struct container of type Char /param arr An array of type unsigned char /param allocated_length The allocated length of the array /param active_length The number of acticaly populated indices in the array arr
Char arr;
char a[5] = {'a', 'b'};
init_char_array(&arr, a, 5, 2);
// Since the array is statically allocated it does not need to be freed
Definition at line 324 of file vector.c.
                                                                                          {
    vec->array = arr;
    vec->dat_type = STATIC;
    vec->active_length = active_length;
    vec->allocated_length = allocated_length;
}
References STATIC.
init_char_vector()
int init_char_vector (Char * vec, size_t length)
Definition at line 182 of file vector.c.
                                               {
    // Make initial vector allocation
    char *ptr = malloc(length * sizeof(char));
    if (ptr == NULL) {
        fprintf(stderr, "malloc failed in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->dat_type = DYNAMIC;
    vec->allocated_length = length;
    vec->active_length = 0;
    vec->array = ptr;
    return 1;
}
References DYNAMIC.
Referenced by copy_char_vector(), and cumsum_char_vector().
init_double_array()
void init_double_array (Dble * vec, double * arr, size_t allocated_length, size_t active_length)
This funciton will initialize an array struct container of type Dble
/param vec A vector struct container of type Dble /param arr An array of type unsigned double /param allocated_length The allocated length of the array /param active_length The number of acticaly populated indices in the array arr
Dble arr;
double a[5] = {1.1, 2.2};
init_double_array(&arr, a, 5, 2);
// Since the array is statically allocated it does not need to be freed
Definition at line 308 of file vector.c.
                                                                                              {
    vec->array = arr;
    vec->dat_type = STATIC;
    vec->active_length = active_length;
    vec->allocated_length = allocated_length;
}
References STATIC.
init_double_vector()
int init_double_vector (Dble * vec, size_t length)
Definition at line 152 of file vector.c.
                                                 {
    // Make initial vector allocation
    double *ptr = malloc(length * sizeof(double));
    if (ptr == NULL) {
        fprintf(stderr, "malloc failed in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->dat_type = DYNAMIC;
    vec->allocated_length = length;
    vec->active_length = 0;
    vec->array = ptr;
    return 1;
}
References DYNAMIC.
Referenced by copy_double_vector(), and cumsum_double_vector().
init_float_array()
void init_float_array (Flt * vec, float * arr, size_t allocated_length, size_t active_length)
This funciton will initialize an array struct container of type Flt
/param vec A vector struct container of type Flt /param arr An array of type float /param allocated_length The allocated length of the array /param active_length The number of acticaly populated indices in the array arr
Flt arr;
float a[5] = {1.1, 2.2};
init_float_array(&arr, a, 5, 2);
// Since the array is statically allocated it does not need to be freed
Definition at line 300 of file vector.c.
                                                                                           {
    vec->array = arr;
    vec->dat_type = STATIC;
    vec->active_length = active_length;
    vec->allocated_length = allocated_length;
}
References STATIC.
init_float_vector()
int init_float_vector (Flt * vec, size_t length)
Definition at line 137 of file vector.c.
                                               {
    // Make initial vector allocation
    float *ptr = malloc(length * sizeof(float));
    if (ptr == NULL) {
        fprintf(stderr, "malloc failed in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->dat_type = DYNAMIC;
    vec->allocated_length = length;
    vec->active_length = 0;
    vec->array = ptr;
    return 1;
}
References DYNAMIC.
Referenced by copy_float_vector(), and cumsum_float_vector().
init_int_array()
void init_int_array (Int * vec, int * arr, size_t allocated_length, size_t active_length)
This funciton will initialize an array struct container of type Int
/param vec A vector struct container of type Int /param arr An array of type int /param allocated_length The allocated length of the array /param active_length The number of acticaly populated indices in the array arr
Int arr;
int a[5] = {1, 2};
init_int_array(&arr, a, 5, 2);
// Since the array is statically allocated it does not need to be freed
Definition at line 252 of file vector.c.
                                                                                       {
    vec->array = arr;
    vec->dat_type = STATIC;
    vec->active_length = active_length;
    vec->allocated_length = allocated_length;
}
References STATIC.
init_int_vector()
int init_int_vector (Int * vec, size_t length)
Definition at line 48 of file vector.c.
                                             {
    // Make initial vector allocation
    int *ptr = malloc(length * sizeof(int));
    if (ptr == NULL) {
        fprintf(stderr, "malloc failed in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->dat_type = DYNAMIC;
    vec->allocated_length = length;
    vec->active_length = 0;
    vec->array = ptr;
    return 1;
}
References DYNAMIC.
Referenced by copy_int_vector(), and cumsum_int_vector().
init_ldouble_array()
void init_ldouble_array (LDble * vec, long double * arr, size_t allocated_length, size_t active_length)
This funciton will initialize an array struct container of type LDble
/param vec A vector struct container of type LDble /param arr An array of type long double /param allocated_length The allocated length of the array /param active_length The number of acticaly populated indices in the array arr
LDble arr;
long doub;e a[5] = {1.1, 2.2};
init_ldouble_array(&arr, a, 5, 2);
// Since the array is statically allocated it does not need to be freed
Definition at line 316 of file vector.c.
                                                                                                     {
    vec->array = arr;
    vec->dat_type = STATIC;
    vec->active_length = active_length;
    vec->allocated_length = allocated_length;
}
References STATIC.
init_ldouble_vector()
int init_ldouble_vector (LDble * vec, size_t length)
Definition at line 167 of file vector.c.
                                                   {
    // Make initial vector allocation
    long double *ptr = malloc(length * sizeof(long double));
    if (ptr == NULL) {
        fprintf(stderr, "malloc failed in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->dat_type = DYNAMIC;
    vec->allocated_length = length;
    vec->active_length = 0;
    vec->array = ptr;
    return 1;
}
References DYNAMIC.
Referenced by copy_ldouble_vector(), and cumsum_ldouble_vector().
init_llong_array()
void init_llong_array (LLInt * vec, long long int * arr, size_t allocated_length, size_t active_length)
This funciton will initialize an array struct container of type LLInt
/param vec A vector struct container of type LLInt /param arr An array of type long long int /param allocated_length The allocated length of the array /param active_length The number of acticaly populated indices in the array arr
LLInt arr;
long long int a[5] = {1, 2};
init_llong_array(&arr, a, 5, 2);
// Since the array is statically allocated it does not need to be freed
Definition at line 284 of file vector.c.
                                                                                                     {
    vec->array = arr;
    vec->dat_type = STATIC;
    vec->active_length = active_length;
    vec->allocated_length = allocated_length;
}
References STATIC.
init_llong_vector()
int init_llong_vector (LLInt * vec, size_t length)
Definition at line 107 of file vector.c.
                                                 {
    // Make initial vector allocation
    long long int *ptr = malloc(length * sizeof(long long int));
    if (ptr == NULL) {
        fprintf(stderr, "malloc failed in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->dat_type = DYNAMIC;
    vec->allocated_length = length;
    vec->active_length = 0;
    vec->array = ptr;
    return 1;
}
References DYNAMIC.
Referenced by copy_llong_vector(), and cumsum_llong_vector().
init_long_array()
void init_long_array (LInt * vec, long int * arr, size_t allocated_length, size_t active_length)
This funciton will initialize an array struct container of type LInt
/param vec A vector struct container of type LInt /param arr An array of type long int /param allocated_length The allocated length of the array /param active_length The number of acticaly populated indices in the array arr
LInt arr;
long int a[5] = {1, 2};
init_long_array(&arr, a, 5, 2);
// Since the array is statically allocated it does not need to be freed
Definition at line 268 of file vector.c.
                                                                                              {
    vec->array = arr;
    vec->dat_type = STATIC;
    vec->active_length = active_length;
    vec->allocated_length = allocated_length;
}
References STATIC.
init_long_vector()
int init_long_vector (LInt * vec, size_t length)
Definition at line 78 of file vector.c.
                                               {
    // Make initial vector allocation
    long int *ptr = malloc(length * sizeof(long int));
    if (ptr == NULL) {
        fprintf(stderr, "malloc failed in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->dat_type = DYNAMIC;
    vec->allocated_length = length;
    vec->active_length = 0;
    vec->array = ptr;
    return 1;
}
References DYNAMIC.
Referenced by copy_long_vector(), and cumsum_long_vector().
init_short_array()
void init_short_array (Short * vec, short int * arr, size_t allocated_length, size_t active_length)
This funciton will initialize an array struct container of type Short
/param vec A vector struct container of type Short /param arr An array of type short int /param allocated_length The allocated length of the array /param active_length The number of acticaly populated indices in the array arr
Short arr;
short int a[5] = {1, 2};
init_short_array(&arr, a, 5, 2);
// Since the array is statically allocated it does not need to be freed
Definition at line 236 of file vector.c.
                                                                                                 {
    vec->array = arr;
    vec->dat_type = STATIC;
    vec->active_length = active_length;
    vec->allocated_length = allocated_length;
}
References STATIC.
init_short_vector()
int init_short_vector (Short * vec, size_t length)
Definition at line 18 of file vector.c.
                                                 {
    // Make initial vector allocation
    short int *ptr = malloc(length * sizeof(short int));
    if (ptr == NULL) {
        fprintf(stderr, "malloc failed in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->dat_type = DYNAMIC;
    vec->allocated_length = length;
    vec->active_length = 0;
    vec->array = ptr;
    return 1;
}
References DYNAMIC.
Referenced by copy_short_vector(), and cumsum_short_vector().
init_string_vector()
int init_string_vector (String * vec)
This function initializes a vector struct of type String to contain a dynamically allocated array of strings.
/param vec A Vector struct of type String
Definition at line 227 of file vector.c.
                                    {
    vec->active_length = 0;
    vec->array = NULL;
    return 1;
}
References String::active_length, and String::array.
Referenced by copy_string_vector().
init_uchar_array()
void init_uchar_array (UChar * vec, unsigned char * arr, size_t allocated_length, size_t active_length)
This funciton will initialize an array struct container of type UChar
/param vec A vector struct container of type UChar /param arr An array of type unsigned unsigned char /param allocated_length The allocated length of the array /param active_length The number of acticaly populated indices in the array arr
UChar arr;
unsigned char a[5] = {'a', 'b'};
init_uchar_array(&arr, a, 5, 2);
// Since the array is statically allocated it does not need to be freed
Definition at line 332 of file vector.c.
                                                                                                     {
    vec->array = arr;
    vec->dat_type = STATIC;
    vec->active_length = active_length;
    vec->allocated_length = allocated_length;
}
References STATIC.
init_uchar_vector()
int init_uchar_vector (UChar * vec, size_t length)
Definition at line 197 of file vector.c.
                                                 {
    // Make initial vector allocation
    unsigned char *ptr = malloc(length * sizeof(unsigned char));
    if (ptr == NULL) {
        fprintf(stderr, "malloc failed in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->dat_type = DYNAMIC;
    vec->allocated_length = length;
    vec->active_length = 0;
    vec->array = ptr;
    return 1;
}
References DYNAMIC.
Referenced by cumsum_uchar_vector().
init_uint_array()
void init_uint_array (UInt * vec, unsigned int * arr, size_t allocated_length, size_t active_length)
This funciton will initialize an array struct container of type UInt
/param vec A vector struct container of type UInt /param arr An array of type unsigned unsigned int /param allocated_length The allocated length of the array /param active_length The number of acticaly populated indices in the array arr
UInt arr;
unsigned int a[5] = {1, 2};
init_uint_array(&arr, a, 5, 2);
// Since the array is statically allocated it does not need to be freed
Definition at line 260 of file vector.c.
                                                                                                  {
    vec->array = arr;
    vec->dat_type = STATIC;
    vec->active_length = active_length;
    vec->allocated_length = allocated_length;
}
References STATIC.
init_uint_vector()
int init_uint_vector (UInt * vec, size_t length)
Definition at line 63 of file vector.c.
                                               {
    // Make initial vector allocation
    unsigned int *ptr = malloc(length * sizeof(unsigned int));
    if (ptr == NULL) {
        fprintf(stderr, "malloc failed in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->dat_type = DYNAMIC;
    vec->allocated_length = length;
    vec->active_length = 0;
    vec->array = ptr;
    return 1;
}
References DYNAMIC.
Referenced by copy_uint_vector(), and cumsum_uint_vector().
init_ullong_array()
void init_ullong_array (ULLInt * vec, unsigned long long int * arr, size_t allocated_length, size_t active_length)
This funciton will initialize an array struct container of type ULLInt
/param vec A vector struct container of type ULLInt /param arr An array of type unsigned unsigned long long int /param allocated_length The allocated length of the array /param active_length The number of acticaly populated indices in the array arr
ULLInt arr;
unsigned long long int a[5] = {1, 2};
init_ullong_array(&arr, a, 5, 2);
// Since the array is statically allocated it does not need to be freed
Definition at line 292 of file vector.c.
                                                                                                                {
    vec->array = arr;
    vec->dat_type = STATIC;
    vec->active_length = active_length;
    vec->allocated_length = allocated_length;
}
References STATIC.
init_ullong_vector()
int init_ullong_vector (ULLInt * vec, size_t length)
Definition at line 122 of file vector.c.
                                                   {
    // Make initial vector allocation
    unsigned long long int *ptr = malloc(length * sizeof(unsigned long long int));
    if (ptr == NULL) {
        fprintf(stderr, "malloc failed in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->dat_type = DYNAMIC;
    vec->allocated_length = length;
    vec->active_length = 0;
    vec->array = ptr;
    return 1;
}
References DYNAMIC.
Referenced by copy_ullong_vector(), and cumsum_ullong_vector().
init_ulong_array()
void init_ulong_array (ULInt * vec, unsigned long int * arr, size_t allocated_length, size_t active_length)
This funciton will initialize an array struct container of type ULInt
/param vec A vector struct container of type ULInt /param arr An array of type unsigned unsigned long int /param allocated_length The allocated length of the array /param active_length The number of acticaly populated indices in the array arr
ULInt arr;
unsigned long int a[5] = {1, 2};
init_ulong_array(&arr, a, 5, 2);
// Since the array is statically allocated it does not need to be freed
Definition at line 276 of file vector.c.
                                                                                                         {
    vec->array = arr;
    vec->dat_type = STATIC;
    vec->active_length = active_length;
    vec->allocated_length = allocated_length;
}
References STATIC.
init_ulong_vector()
int init_ulong_vector (ULInt * vec, size_t length)
Definition at line 93 of file vector.c.
                                                 {
    // Make initial vector allocation
    unsigned long int *ptr = malloc(length * sizeof(unsigned long int));
    if (ptr == NULL) {
        fprintf(stderr, "malloc failed in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->dat_type = DYNAMIC;
    vec->allocated_length = length;
    vec->active_length = 0;
    vec->array = ptr;
    return 1;
}
References DYNAMIC.
Referenced by copy_ulong_vector(), and cumsum_ulong_vector().
init_ushort_array()
void init_ushort_array (UShort * vec, unsigned short int * arr, size_t allocated_length, size_t active_length)
This funciton will initialize an array struct container of type UShort
/param vec A vector struct container of type UShort /param arr An array of type unsigned short int /param allocated_length The allocated length of the array /param active_length The number of acticaly populated indices in the array arr
UShort arr;
unsigned short int a[5] = {1, 2};
init_ushort_array(&arr, a, 5, 2);
// Since the array is statically allocated it does not need to be freed
Definition at line 244 of file vector.c.
                                                                                                            {
    vec->array = arr;
    vec->dat_type = STATIC;
    vec->active_length = active_length;
    vec->allocated_length = allocated_length;
}
References STATIC.
init_ushort_vector()
int init_ushort_vector (UShort * vec, size_t length)
Definition at line 33 of file vector.c.
                                                   {
    // Make initial vector allocation
    unsigned short int *ptr = malloc(length * sizeof(unsigned short int));
    if (ptr == NULL) {
        fprintf(stderr, "malloc failed in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->dat_type = DYNAMIC;
    vec->allocated_length = length;
    vec->active_length = 0;
    vec->array = ptr;
    return 1;
}
References DYNAMIC.
Referenced by copy_ushort_vector(), and cumsum_ushort_vector().
insert_bool_vector()
int insert_bool_vector (Bool * vec, bool * elements, size_t num_indices, size_t index)
This function will allow a user to insert a scalar char or an array of bool values into a vector struct of Bool type.
/param vec A vector struct of type Bool /param elements An array or scalar of type bool /param num_indices The number of data points in elements /param index The index where the scalar or array is to be inserted
#include "vector.h"
#include "print.h"*
Bool vec;
init_bool_vector(vec, 6);
push_bool_vector(vec, true);
push_bool_vector(vec, true);
push_bool_vector(vec, false;
char a[3] = {false, false, false};
insert_bool_vector(vec, a, 3, 1);
PRINT(vec);
// >> [ true, false, false, false, true, false ]
free_bool_vector(&vec);
Definition at line 1301 of file vector.c.
                                                         {
    // Ensure that the index is within the active_length
    if (index > vec->active_length) {
        printf("WARNING: The selected index is larger than the active length\n");
        return 0;
    }
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + num_indices) * 2;
        bool *ptr = (bool *)realloc(vec->array, size * sizeof(bool));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Failure on file=%s, line=%d", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (num_indices + index) * sizeof(bool),
            ((char *)vec->array) + index * sizeof(bool),
            (vec->active_length - index) * sizeof(bool));
    memcpy(((char *)vec->array) + index * sizeof(bool), elements,
            num_indices * sizeof(bool));
    vec->active_length += num_indices;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by copy_bool_vector().
insert_char_vector()
int insert_char_vector (Char * vec, char * elements, size_t num_indices, size_t index)
This function will allow a user to insert a scalar char or an array of char values into a vector struct of Char type.
/param vec A vector struct of type Char /param elements An array or scalar of type char /param num_indices The number of data points in elements /param index The index where the scalar or array is to be inserted
#include "vector.h"
#include "print.h"*
Char vec;
init_char_vector(vec, 6);
push_char_vector(vec, 'a');
push_char_vector(vec, 'b');
push_char_vector(vec, 'c';
char a[3] = {'x', 'y', 'z'};
insert_ldouble_vector(vec, a, 3, 1);
PRINT(vec);
// >> [ a, x, y, z, b, c ]
free_char_vector(&vec);
Definition at line 1229 of file vector.c.
                                                      {
    // Ensure that the index is within the active_length
    if (index > vec->active_length) {
        printf("WARNING: The selected index is larger than the active length\n");
        return 0;
    }
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + num_indices) * 2;
        char *ptr = (char *)realloc(vec->array, size * sizeof(char));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Failure on file=%s, line=%d", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (num_indices + index) * sizeof(char),
            ((char *)vec->array) + index * sizeof(char),
            (vec->active_length - index) * sizeof(char));
    memcpy(((char *)vec->array) + index * sizeof(char), elements,
            num_indices * sizeof(char));
    vec->active_length += num_indices;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by copy_char_vector().
insert_double_vector()
int insert_double_vector (Dble * vec, double * elements, size_t num_indices, size_t index)
This function will allow a user to insert a scalar double or an array of double values into a vector struct of Dble type.
/param vec A vector struct of type Dble /param elements An array or scalar of type double /param num_indices The number of data points in elements /param index The index where the scalar or array is to be inserted
#include "vector.h"
#include "print.h"*
Dble vec;
init_double_vector(vec, 6);
push_double_vector(vec, 1);
push_double_vector(vec, 2);
push_double_vector(vec, 3);
double a[3] = {5, 6, 7};
insert_double_vector(vec, a, 3, 1);
PRINT(vec);
// >> [ 1, 5, 6, 7, 2, 3 ]
free_double_vector(&vec);
Definition at line 1157 of file vector.c.
                                                        {
    // Ensure that the index is within the active_length
    if (index > vec->active_length) {
        printf("WARNING: The selected index is larger than the active length\n");
        return 0;
    }
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + num_indices) * 2;
        double *ptr = (double *)realloc(vec->array, size * sizeof(double));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Failure on file=%s, line=%d", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (num_indices + index) * sizeof(double),
            ((char *)vec->array) + index * sizeof(double),
            (vec->active_length - index) * sizeof(double));
    memcpy(((char *)vec->array) + index * sizeof(double), elements,
            num_indices * sizeof(double));
    vec->active_length += num_indices;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by copy_double_vector().
insert_float_vector()
int insert_float_vector (Flt * vec, float * elements, size_t num_indices, size_t index)
This function will allow a user to insert a scalar float or an array of float values into a vector struct of Flt type.
/param vec A vector struct of type Flt /param elements An array or scalar of type float /param num_indices The number of data points in elements /param index The index where the scalar or array is to be inserted
#include "vector.h"
#include "print.h"*
Flt vec;
init_float_vector(vec, 6);
push_float_vector(vec, 1);
push_float_vector(vec, 2);
push_float_vector(vec, 3);
float a[3] = {5, 6, 7};
insert_float_vector(vec, a, 3, 1);
PRINT(vec);
// >> [ 1, 5, 6, 7, 2, 3 ]
free_float_vector(&vec);
Definition at line 1121 of file vector.c.
                                                       {
    // Ensure that the index is within the active_length
    if (index > vec->active_length) {
        printf("WARNING: The selected index is larger than the active length\n");
        return 0;
    }
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + num_indices) * 2;
        float *ptr = (float *)realloc(vec->array, size * sizeof(float));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Failure on file=%s, line=%d", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (num_indices + index) * sizeof(float),
            ((char *)vec->array) + index * sizeof(float),
            (vec->active_length - index) * sizeof(float));
    memcpy(((char *)vec->array) + index * sizeof(float), elements,
            num_indices * sizeof(float));
    vec->active_length += num_indices;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by copy_float_vector().
insert_int_vector()
int insert_int_vector (Int * vec, int * elements, size_t num_indices, size_t index)
This function will allow a user to insert a scalar int or an array of int values into a vector struct of Int type.
/param vec A vector struct of type Int /param elements An array or scalar of type int /param num_indices The number of data points in elements /param index The index where the scalar or array is to be inserted
#include "vector.h"
#include "print.h"*
Int vec;
init_int_vector(vec, 6);
push_int_vector(vec, 1);
push_int_vector(vec, 2);
push_int_vector(vec, 3);
int a[3] = {5, 6, 7};
insert_int_vector(vec, a, 3, 1);
PRINT(vec);
// >> [ 1, 5, 6, 7, 2, 3 ]
free_int_vector(&vec);
Definition at line 905 of file vector.c.
                                                     {
    // Ensure that the index is within the active_length
    if (index > vec->active_length) {
        printf("WARNING: The selected index is larger than the active length\n");
        return 0;
    }
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + num_indices) * 2;
        int *ptr = (int *)realloc(vec->array, size * sizeof(int));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Failure on file=%s, line=%d", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (num_indices + index) * sizeof(int),
            ((char *)vec->array) + index * sizeof(int),
            (vec->active_length - index) * sizeof(int));
    memcpy(((char *)vec->array) + index * sizeof(int), elements,
            num_indices * sizeof(int));
    vec->active_length += num_indices;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by copy_int_vector().
insert_ldouble_vector()
int insert_ldouble_vector (LDble * vec, long double * elements, size_t num_indices, size_t index)
This function will allow a user to insert a scalar long double or an array of long double values into a vector struct of LDble type.
/param vec A vector struct of type LDble /param elements An array or scalar of type long double /param num_indices The number of data points in elements /param index The index where the scalar or array is to be inserted
#include "vector.h"
#include "print.h"*
LDble vec;
init_ldouble_vector(vec, 6);
push_ldouble_vector(vec, 1);
push_ldouble_vector(vec, 2);
push_ldouble_vector(vec, 3);
long double a[3] = {5, 6, 7};
insert_ldouble_vector(vec, a, 3, 1);
PRINT(vec);
// >> [ 1, 5, 6, 7, 2, 3 ]
free_ldouble_vector(&vec);
Definition at line 1193 of file vector.c.
                                                         {
    // Ensure that the index is within the active_length
    if (index > vec->active_length) {
        printf("WARNING: The selected index is larger than the active length\n");
        return 0;
    }
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + num_indices) * 2;
        long double *ptr = (long double *)realloc(vec->array, size * sizeof(long double));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Failure on file=%s, line=%d", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (num_indices + index) * sizeof(long double),
            ((char *)vec->array) + index * sizeof(long double),
            (vec->active_length - index) * sizeof(long double));
    memcpy(((char *)vec->array) + index * sizeof(long double), elements,
            num_indices * sizeof(long double));
    vec->active_length += num_indices;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by copy_ldouble_vector().
insert_llong_vector()
int insert_llong_vector (LLInt * vec, long long int * elements, size_t num_indices, size_t index)
This function will allow a user to insert a scalar long long or an array of long long values into a vector struct of LLInt type.
/param vec A vector struct of type LLInt /param elements An array or scalar of type long long int /param num_indices The number of data points in elements /param index The index where the scalar or array is to be inserted
#include "vector.h"
#include "print.h"*
LLInt vec;
init_llong_vector(vec, 6);
push_llong_vector(vec, 1);
push_llong_vector(vec, 2);
push_llong_vector(vec, 3);
long long int a[3] = {5, 6, 7};
insert_llong_vector(vec, a, 3, 1);
PRINT(vec);
// >> [ 1, 5, 6, 7, 2, 3 ]
free_llong_vector(&vec);
Definition at line 1049 of file vector.c.
                                                       {
    // Ensure that the index is within the active_length
    if (index > vec->active_length) {
        printf("WARNING: The selected index is larger than the active length\n");
        return 0;
    }
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + num_indices) * 2;
        long long int *ptr = (long long int *)realloc(vec->array, size * sizeof(long long int));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Failure on file=%s, line=%d", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (num_indices + index) * sizeof(long long int),
            ((char *)vec->array) + index * sizeof(long long int),
            (vec->active_length - index) * sizeof(long long int));
    memcpy(((char *)vec->array) + index * sizeof(long long int), elements,
            num_indices * sizeof(long long int));
    vec->active_length += num_indices;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by copy_llong_vector().
insert_long_vector()
int insert_long_vector (LInt * vec, long int * elements, size_t num_indices, size_t index)
This function will allow a user to insert a scalar long or an array of long values into a vector struct of LInt type.
/param vec A vector struct of type LInt /param elements An array or scalar of type long int /param num_indices The number of data points in elements /param index The index where the scalar or array is to be inserted
#include "vector.h"
#include "print.h"*
LInt vec;
init_long_vector(vec, 6);
push_long_vector(vec, 1);
push_long_vector(vec, 2);
push_long_vector(vec, 3);
long int a[3] = {5, 6, 7};
insert_long_vector(vec, a, 3, 1);
PRINT(vec);
// >> [ 1, 5, 6, 7, 2, 3 ]
free_long_vector(&vec);
Definition at line 977 of file vector.c.
                                                      {
    // Ensure that the index is within the active_length
    if (index > vec->active_length) {
        printf("WARNING: The selected index is larger than the active length\n");
        return 0;
    }
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + num_indices) * 2;
        long int *ptr = (long int *)realloc(vec->array, size * sizeof(long int));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Failure on file=%s, line=%d", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (num_indices + index) * sizeof(long int),
            ((char *)vec->array) + index * sizeof(long int),
            (vec->active_length - index) * sizeof(long int));
    memcpy(((char *)vec->array) + index * sizeof(long int), elements,
            num_indices * sizeof(long int));
    vec->active_length += num_indices;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by copy_long_vector().
insert_short_vector()
int insert_short_vector (Short * vec, short int * elements, size_t num_indices, size_t index)
This function will allow a user to insert a scalar short or an array of short values into a vector struct of Short type.
/param vec A vector struct of type Short /param elements An array or scalar of type short /param num_indices The number of data points in elements /param index The index where the scalar or array is to be inserted
#include "vector.h"
#include "print.h"*
Short vec;
init_short_vector(vec, 6);
push_short_vector(vec, 1);
push_short_vector(vec, 2);
push_short_vector(vec, 3);
short a[3] = {5, 6, 7};
insert_short_vector(vec, a, 3, 1);
PRINT(vec);
// >> [ 1, 5, 6, 7, 2, 3 ]
free_short_vector(&vec);
Definition at line 833 of file vector.c.
                                                       {
    // Ensure that the index is within the active_length
    if (index > vec->active_length) {
        printf("WARNING: The selected index is larger than the active length\n");
        return 0;
    }
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + num_indices) * 2;
        short int *ptr = (short int *)realloc(vec->array, size * sizeof(short int));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Failure on file=%s, line=%d", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (num_indices + index) * sizeof(short int),
            ((char *)vec->array) + index * sizeof(short int),
            (vec->active_length - index) * sizeof(short int));
    memcpy(((char *)vec->array) + index * sizeof(short int), elements,
            num_indices * sizeof(short int));
    vec->active_length += num_indices;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by copy_short_vector().
insert_string_vector()
int insert_string_vector (String * vec, char ** elements, size_t num_indices, size_t index)
This function will allow a user to insert a scalar char or an array of bool values into a vector struct of String type.
/param vec A vector struct of type String /param elements An array or scalar of type char* /param num_indices The number of data points in elements /param index The index where the scalar or array is to be inserted
#include "vector.h"
#include "print.h"*
String vec;
init_string_vector(vec);
push_string_vector(vec, "One");
push_string_vector(vec, "Two");
push_string_vector(vec, "Three");
char *a[3] = {"Four", "Five", "Six"};
insert_string_vector(vec, a, 3, 1);
PRINT(vec);
// >> [ One, Four, Five, Six, Two, Three ]
free_string_vector(&vec);
Definition at line 1337 of file vector.c.
                                                      {
    if (index > vec->active_length) {
        fprintf(stderr, "String index out of range in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    char **resized = realloc(vec->array, sizeof(*vec->array) * (vec->active_length + length));
    if (!resized) {
        fprintf(stderr, "realloc failed in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->array = resized;
    if (index < vec->active_length) {
        memmove(vec->array + index + length, vec->array + index, sizeof(*vec->array) * (vec->active_length - index));
    }
    for (size_t i = 0; i < length; i++) {
        vec->array[index + i] = strdup(values[i]);
    }
    vec->active_length += length;
    return 1;
}
References String::active_length, and String::array.
insert_uchar_vector()
int insert_uchar_vector (UChar * vec, unsigned char * elements, size_t num_indices, size_t index)
This function will allow a user to insert a scalar char or an array of char values into a vector struct of Char type.
/param vec A vector struct of type Char /param elements An array or scalar of type char /param num_indices The number of data points in elements /param index The index where the scalar or array is to be inserted
#include "vector.h"
#include "print.h"*
UChar vec;
init_uchar_vector(vec, 6);
push_uchar_vector(vec, 'a');
push_uchar_vector(vec, 'b');
push_uchar_vector(vec, 'c';
char a[3] = {'x', 'y', 'z'};
insert_uchar_vector(vec, a, 3, 1);
PRINT(vec);
// >> [ a, x, y, z, b, c ]
free_char_vector(&vec);
Definition at line 1265 of file vector.c.
                                                      {
    // Ensure that the index is within the active_length
    if (index > vec->active_length) {
        printf("WARNING: The selected index is larger than the active length\n");
        return 0;
    }
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + num_indices) * 2;
        unsigned char *ptr = (unsigned char *)realloc(vec->array, size * sizeof(unsigned char));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Failure on file=%s, line=%d", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((unsigned char *)vec->array) + (num_indices + index) * sizeof(unsigned char),
            ((unsigned char *)vec->array) + index * sizeof(unsigned char),
            (vec->active_length - index) * sizeof(unsigned char));
    memcpy(((unsigned char *)vec->array) + index * sizeof(unsigned char), elements,
            num_indices * sizeof(unsigned char));
    vec->active_length += num_indices;
    return 1;
}
References DYNAMIC, and STATIC.
insert_uint_vector()
int insert_uint_vector (UInt * vec, unsigned int * elements, size_t num_indices, size_t index)
This function will allow a user to insert a scalar unsigned int or an array of unsigned int values into a vector struct of UInt type.
/param vec A vector struct of type UInt /param elements An array or scalar of type unsigned int /param num_indices The number of data points in elements /param index The index where the scalar or array is to be inserted
#include "vector.h"
#include "print.h"*
UInt vec;
init_uint_vector(vec, 6);
push_uint_vector(vec, 1);
push_uint_vector(vec, 2);
push_uint_vector(vec, 3);
unsigned int a[3] = {5, 6, 7};
insert_uint_vector(vec, a, 3, 1);
PRINT(vec);
// >> [ 1, 5, 6, 7, 2, 3 ]
free_uint_vector(&vec);
Definition at line 941 of file vector.c.
                                                      {
    // Ensure that the index is within the active_length
    if (index > vec->active_length) {
        printf("WARNING: The selected index is larger than the active length\n");
        return 0;
    }
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + num_indices) * 2;
        unsigned int *ptr = (unsigned int *)realloc(vec->array, size * sizeof(unsigned int));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Failure on file=%s, line=%d", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (num_indices + index) * sizeof(unsigned int),
            ((char *)vec->array) + index * sizeof(unsigned int),
            (vec->active_length - index) * sizeof(unsigned int));
    memcpy(((char *)vec->array) + index * sizeof(unsigned int), elements,
            num_indices * sizeof(unsigned int));
    vec->active_length += num_indices;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by copy_uint_vector().
insert_ullong_vector()
int insert_ullong_vector (ULLInt * vec, unsigned long long int * elements, size_t num_indices, size_t index)
This function will allow a user to insert a scalar unsigned long long or an array of unsigned long long values into a vector struct of ULLInt type.
/param vec A vector struct of type ULLInt /param elements An array or scalar of type unsigned long long int /param num_indices The number of data points in elements /param index The index where the scalar or array is to be inserted
#include "vector.h"
#include "print.h"*
ULLInt vec;
init_ullong_vector(vec, 6);
push_ullong_vector(vec, 1);
push_ullong_vector(vec, 2);
push_ullong_vector(vec, 3);
unsigned long long int a[3] = {5, 6, 7};
insert_ullong_vector(vec, a, 3, 1);
PRINT(vec);
// >> [ 1, 5, 6, 7, 2, 3 ]
free_ullong_vector(&vec);
Definition at line 1085 of file vector.c.
                                                        {
    // Ensure that the index is within the active_length
    if (index > vec->active_length) {
        printf("WARNING: The selected index is larger than the active length\n");
        return 0;
    }
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + num_indices) * 2;
        unsigned long long int *ptr = (unsigned long long int *)realloc(vec->array, size * sizeof(unsigned long long int));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Failure on file=%s, line=%d", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (num_indices + index) * sizeof(unsigned long long int),
            ((char *)vec->array) + index * sizeof(unsigned long long int),
            (vec->active_length - index) * sizeof(unsigned long long int));
    memcpy(((char *)vec->array) + index * sizeof(unsigned long long int), elements,
            num_indices * sizeof(unsigned long long int));
    vec->active_length += num_indices;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by copy_ullong_vector().
insert_ulong_vector()
int insert_ulong_vector (ULInt * vec, unsigned long int * elements, size_t num_indices, size_t index)
This function will allow a user to insert a scalar unsigned long or an array of unsigned long values into a vector struct of ULInt type.
/param vec A vector struct of type ULInt /param elements An array or scalar of type unsigned long int /param num_indices The number of data points in elements /param index The index where the scalar or array is to be inserted
#include "vector.h"
#include "print.h"*
ULInt vec;
init_ulong_vector(vec, 6);
push_ulong_vector(vec, 1);
push_ulong_vector(vec, 2);
push_ulong_vector(vec, 3);
unsigned long int a[3] = {5, 6, 7};
insert_ulong_vector(vec, a, 3, 1);
PRINT(vec);
// >> [ 1, 5, 6, 7, 2, 3 ]
free_ulong_vector(&vec);
Definition at line 1013 of file vector.c.
                                                       {
    // Ensure that the index is within the active_length
    if (index > vec->active_length) {
        printf("WARNING: The selected index is larger than the active length\n");
        return 0;
    }
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + num_indices) * 2;
        unsigned long int *ptr = (unsigned long int *)realloc(vec->array, size * sizeof(unsigned long int));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Failure on file=%s, line=%d", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (num_indices + index) * sizeof(unsigned long int),
            ((char *)vec->array) + index * sizeof(unsigned long int),
            (vec->active_length - index) * sizeof(unsigned long int));
    memcpy(((char *)vec->array) + index * sizeof(unsigned long int), elements,
            num_indices * sizeof(unsigned long int));
    vec->active_length += num_indices;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by copy_ulong_vector().
insert_ushort_vector()
int insert_ushort_vector (UShort * vec, unsigned short int * elements, size_t num_indices, size_t index)
This function will allow a user to insert a scalar unsigned short or an array of unsigned short values into a vector struct of UShort type.
/param vec A vector struct of type UShort /param elements An array or scalar of type unsigned short /param num_indices The number of data points in elements /param index The index where the scalar or array is to be inserted
#include "vector.h"
#include "print.h"*
UShort vec;
init_ushort_vector(vec, 6);
push_ushort_vector(vec, 1);
push_ushort_vector(vec, 2);
push_ushort_vector(vec, 3);
unsigned short a[3] = {5, 6, 7};
insert_ushort_vector(vec, a, 3, 1);
PRINT(vec);
// >> [ 1, 5, 6, 7, 2, 3 ]
free_ushort_vector(&vec);
Definition at line 869 of file vector.c.
                                                        {
    // Ensure that the index is within the active_length
    if (index > vec->active_length) {
        printf("WARNING: The selected index is larger than the active length\n");
        return 0;
    }
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + num_indices > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + num_indices) * 2;
        unsigned short int *ptr = (unsigned short int *)realloc(vec->array, size * sizeof(unsigned short int));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Failure on file=%s, line=%d", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (num_indices + index) * sizeof(unsigned short int),
            ((char *)vec->array) + index * sizeof(unsigned short int),
            (vec->active_length - index) * sizeof(unsigned short int));
    memcpy(((char *)vec->array) + index * sizeof(unsigned short int), elements,
            num_indices * sizeof(unsigned short int));
    vec->active_length += num_indices;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by copy_ushort_vector().
int_vector_data()
int int_vector_data (Int * vec, size_t index)
This function will retireve the data from a user specified index in a vector or array of type Int
/param vec A linked list struct of type Int /param index The index from where data will be retrieved /return dat An unsigned bool data point
Int vec;
init_int_vector(&vec);
int a[5] = {1, 2, 3, 4, 5};
insert_int_vector(&vec, a, 5, 0);
PRINT(int_vector_data(&vec, 2));
// >> 3
free_int_vector(&vec);
Definition at line 4425 of file vector.c.
{ return vec->array[index]; }
ldouble_vector_data()
long double ldouble_vector_data (LDble * vec, size_t index)
This function will retireve the data from a user specified index in a vector or array of type LDble
/param vec A linked list struct of type LDble /param index The index from where data will be retrieved /return dat An unsigned bool data point
LDble vec;
init_ldouble_vector(&vec);
long double a[5] = {1, 2, 3, 4, 5};
insert_ldouble_vector(&vec, a, 5, 0);
PRINT(ldouble_vector_data(&vec, 2));
// >> 3.000
free_ldouble_vector(&vec);
Definition at line 4449 of file vector.c.
{ return vec->array[index]; }
llong_vector_data()
long long int llong_vector_data (LLInt * vec, size_t index)
This function will retireve the data from a user specified index in a vector or array of type LLInt
/param vec A linked list struct of type LLInt /param index The index from where data will be retrieved /return dat An unsigned bool data point
LLInt vec;
init_llong_vector(&vec);
long long int a[5] = {1, 2, 3, 4, 5};
insert_llong_vector(&vec, a, 5, 0);
PRINT(llong_vector_data(&vec, 2));
// >> 3
free_llong_vector(&vec);
Definition at line 4437 of file vector.c.
{ return vec->array[index]; }
long_vector_data()
long int long_vector_data (LInt * vec, size_t index)
This function will retireve the data from a user specified index in a vector or array of type LInt
/param vec A linked list struct of type LInt /param index The index from where data will be retrieved /return dat An unsigned bool data point
LInt vec;
init_long_vector(&vec);
long int a[5] = {1, 2, 3, 4, 5};
insert_long_vector(&vec, a, 5, 0);
PRINT(long_vector_data(&vec, 2));
// >> 3
free_long_vector(&vec);
Definition at line 4431 of file vector.c.
{ return vec->array[index]; }
max_char_vector()
char max_char_vector (Char * vec)
This function will determine the max value in a vector data structure of type Char
/param vec A vector data structure of type Char
Char vec;
init_char_vector(&vec, 5);
char a[5] = { 1, 2, 3, 4, 5};
insert_char_vector(&vec, a, 5, 0);
char max = max_char_vector(&vec);
PRINT(max);
// >> 5
free_char_vector(&vec);
Definition at line 4002 of file vector.c.
                                {
    if (vec->active_length == 1) return vec->array[0];
    char max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max < vec->array[i]) max = vec->array[i];
    }
    return max;
}
max_double_vector()
double max_double_vector (Dble * vec)
This function will determine the max value in a vector data structure of type Dble
/param vec A vector data structure of type Dble
Dble vec;
init_double_vector(&vec, 5);
double a[5] = { 1.1, 2.2, 3.3, 4.4, 5.5};
insert_double_vector(&vec, a, 5, 0);
double max = max_double_vector(&vec);
PRINT(max);
// >> 5.5
free_double_vector(&vec);
Definition at line 4123 of file vector.c.
                                    {
    if (vec->active_length == 1) return vec->array[0];
    double max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max < vec->array[i]) max = vec->array[i];
    }
    return max;
}
max_float_vector()
float max_float_vector (Flt * vec)
This function will determine the max value in a vector data structure of type Flt
/param vec A vector data structure of type Flt
Flt vec;
init_float_vector(&vec, 5);
float a[5] = { 1.1, 2.2, 3.3, 4.4, 5.5};
insert_float_vector(&vec, a, 5, 0);
float max = max_float_vector(&vec);
PRINT(max);
// >> 5.5
free_float_vector(&vec);
Definition at line 4112 of file vector.c.
                                 {
    if (vec->active_length == 1) return vec->array[0];
    float max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max < vec->array[i]) max = vec->array[i];
    }
    return max;
}
max_int_vector()
int max_int_vector (Int * vec)
This function will determine the max value in a vector data structure of type Int
/param vec A vector data structure of type Int
Int vec;
init_int_vector(&vec, 5);
int a[5] = { 1, 2, 3, 4, 5};
insert_int_vector(&vec, a, 5, 0);
int max = max_int_vector(&vec);
PRINT(max);
// >> 5
free_int_vector(&vec);
Definition at line 4046 of file vector.c.
                             {
    if (vec->active_length == 1) return vec->array[0];
    int max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max < vec->array[i]) max = vec->array[i];
    }
    return max;
}
max_ldouble_vector()
long double max_ldouble_vector (LDble * vec)
This function will determine the max value in a vector data structure of type LDble
/param vec A vector data structure of type LDble
LDble vec;
init_ldouble_vector(&vec, 5);
long double a[5] = { 1.1, 2.2, 3.3, 4.4, 5.5};
insert_ldouble_vector(&vec, a, 5, 0);
long double max = max_ldouble_vector(&vec);
PRINT(max);
// >> 5.5
free_ldouble_vector(&vec);
Definition at line 4134 of file vector.c.
                                           {
    if (vec->active_length == 1) return vec->array[0];
    long double max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max < vec->array[i]) max = vec->array[i];
    }
    return max;
}
max_llong_vector()
long long int max_llong_vector (LLInt * vec)
This function will determine the max value in a vector data structure of type LLInt
/param vec A vector data structure of type LLInt
LLInt vec;
init_llong_vector(&vec, 5);
long long int a[5] = { 1, 2, 3, 4, 5};
insert_llong_vector(&vec, a, 5, 0);
long long int max = max_llong_vector(&vec);
PRINT(max);
// >> 5
free_llong_vector(&vec);
Definition at line 4090 of file vector.c.
                                           {
    if (vec->active_length == 1) return vec->array[0];
    long long int max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max < vec->array[i]) max = vec->array[i];
    }
    return max;
}
max_long_vector()
long int max_long_vector (LInt * vec)
This function will determine the max value in a vector data structure of type LInt
/param vec A vector data structure of type LInt
LInt vec;
init_long_vector(&vec, 5);
long int a[5] = { 1, 2, 3, 4, 5};
insert_long_vector(&vec, a, 5, 0);
long int max = max_long_vector(&vec);
PRINT(max);
// >> 5
free_long_vector(&vec);
Definition at line 4068 of file vector.c.
                                    {
    if (vec->active_length == 1) return vec->array[0];
    long int max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max < vec->array[i]) max = vec->array[i];
    }
    return max;
}
max_short_vector()
short int max_short_vector (Short * vec)
This function will determine the max value in a vector data structure of type Short
/param vec A vector data structure of type Short
Short vec;
init_short_vector(&vec, 5);
short int a[5] = { 1, 2, 3, 4, 5};
insert_short_vector(&vec, a, 5, 0);
short int max = max_short_vector(&vec);
PRINT(max);
// >> 5
free_short_vector(&vec);
Definition at line 4024 of file vector.c.
                                       {
    if (vec->active_length == 1) return vec->array[0];
    short int max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max < vec->array[i]) max = vec->array[i];
    }
    return max;
}
max_uchar_vector()
unsigned char max_uchar_vector (UChar * vec)
This function will determine the max value in a vector data structure of type UChar
/param vec A vector data structure of type UChar
UChar vec;
init_uchar_vector(&vec, 5);
unsigned char a[5] = { 1, 2, 3, 4, 5};
insert_uchar_vector(&vec, a, 5, 0);
unsigned char max = max_uchar_vector(&vec);
PRINT(max);
// >> 5
free_uchar_vector(&vec);
Definition at line 4013 of file vector.c.
                                           {
    if (vec->active_length == 1) return vec->array[0];
    unsigned char max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max < vec->array[i]) max = vec->array[i];
    }
    return max;
}
max_uint_vector()
unsigned int max_uint_vector (UInt * vec)
This function will determine the max value in a vector data structure of type UInt
/param vec A vector data structure of type UInt
UInt vec;
init_uint_vector(&vec, 5);
unsigned int a[5] = { 1, 2, 3, 4, 5};
insert_uint_vector(&vec, a, 5, 0);
unsigned int max = max_uint_vector(&vec);
PRINT(max);
// >> 5
free_uint_vector(&vec);
Definition at line 4057 of file vector.c.
                                        {
    if (vec->active_length == 1) return vec->array[0];
    unsigned int max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max < vec->array[i]) max = vec->array[i];
    }
    return max;
}
max_ullong_vector()
unsigned long long int max_ullong_vector (ULLInt * vec)
This function will determine the max value in a vector data structure of type ULLInt
/param vec A vector data structure of type ULLInt
ULLInt vec;
init_ullong_vector(&vec, 5);
unsigned long long int a[5] = { 1, 2, 3, 4, 5};
insert_ullong_vector(&vec, a, 5, 0);
unsigned long long int max = max_ullong_vector(&vec);
PRINT(max);
// >> 5
free_ullong_vector(&vec);
Definition at line 4101 of file vector.c.
                                                      {
    if (vec->active_length == 1) return vec->array[0];
    unsigned long long int max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max < vec->array[i]) max = vec->array[i];
    }
    return max;
}
max_ulong_vector()
unsigned long int max_ulong_vector (ULInt * vec)
This function will determine the max value in a vector data structure of type ULInt
/param vec A vector data structure of type ULInt
ULInt vec;
init_ulong_vector(&vec, 5);
unsigned long int a[5] = { 1, 2, 3, 4, 5};
insert_ulong_vector(&vec, a, 5, 0);
unsigned long int max = max_ulong_vector(&vec);
PRINT(max);
// >> 5
free_ulong_vector(&vec);
Definition at line 4079 of file vector.c.
                                               {
    if (vec->active_length == 1) return vec->array[0];
    unsigned long int max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max < vec->array[i]) max = vec->array[i];
    }
    return max;
}
max_ushort_vector()
unsigned short int max_ushort_vector (UShort * vec)
This function will determine the max value in a vector data structure of type UShort
/param vec A vector data structure of type UShort
UShort vec;
init_ushort_vector(&vec, 5);
unsigned short int a[5] = { 1, 2, 3, 4, 5};
insert_ushort_vector(&vec, a, 5, 0);
unsigned short int max = max_ushort_vector(&vec);
PRINT(max);
// >> 5
free_ushort_vector(&vec);
Definition at line 4035 of file vector.c.
                                                  {
    if (vec->active_length == 1) return vec->array[0];
    unsigned short int max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max < vec->array[i]) max = vec->array[i];
    }
    return max;
}
min_char_vector()
char min_char_vector (Char * vec)
This function will determine the min value in a vector data structure of type Char
/param vec A vector data structure of type Char /return min The minimum value
Char vec;
init_char_vector(&vec, 5);
char a[5] = { 1, 2, 3, 4, 5};
insert_char_vector(&vec, a, 5, 0);
char min = min_char_vector(&vec);
PRINT(max);
// >> 1
free_char_vector(&vec);
Definition at line 4147 of file vector.c.
                                {
    if (vec->active_length == 1) return vec->array[0];
    char max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max > vec->array[i]) max = vec->array[i];
    }
    return max;
}
min_double_vector()
double min_double_vector (Dble * vec)
This function will determine the min value in a vector data structure of type Dble
/param vec A vector data structure of type Dble
Dble vec;
init_double_vector(&vec, 5);
double a[5] = { 1., 2., 3., 4., 5.};
insert_double_vector(&vec, a, 5, 0);
double min = min_double_vector(&vec);
PRINT(max);
// >> 1
free_double_vector(&vec);
Definition at line 4268 of file vector.c.
                                    {
    if (vec->active_length == 1) return vec->array[0];
    double max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max > vec->array[i]) max = vec->array[i];
    }
    return max;
}
min_float_vector()
float min_float_vector (Flt * vec)
This function will determine the min value in a vector data structure of type Flt
/param vec A vector data structure of type Flt
Flt vec;
init_float_vector(&vec, 5);
float a[5] = {1., 2., 3., 4., 5.};
insert_float_vector(&vec, a, 5, 0);
float min = min_float_vector(&vec);
PRINT(max);
// >> 1
free_float_vector(&vec);
Definition at line 4257 of file vector.c.
                                 {
    if (vec->active_length == 1) return vec->array[0];
    float max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max > vec->array[i]) max = vec->array[i];
    }
    return max;
}
min_int_vector()
int min_int_vector (Int * vec)
This function will determine the min value in a vector data structure of type Int
/param vec A vector data structure of type Int
Int vec;
init_int_vector(&vec, 5);
int a[5] = { 1, 2, 3, 4, 5};
insert_int_vector(&vec, a, 5, 0);
int min = min_int_vector(&vec);
PRINT(max);
// >> 1
free_int_vector(&vec);
Definition at line 4191 of file vector.c.
                             {
    if (vec->active_length == 1) return vec->array[0];
    int max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max > vec->array[i]) max = vec->array[i];
    }
    return max;
}
min_ldouble_vector()
long double min_ldouble_vector (LDble * vec)
This function will determine the min value in a vector data structure of type LDble
/param vec A vector data structure of type LDble
LDble vec;
init_ldouble_vector(&vec, 5);
long double a[5] = { 1., 2., 3., 4., 5.};
insert_ldouble_vector(&vec, a, 5, 0);
long double min = min_ldouble_vector(&vec);
PRINT(max);
// >> 1
free_ldouble_vector(&vec);
min_llong_vector()
long long int min_llong_vector (LLInt * vec)
This function will determine the min value in a vector data structure of type LLInt
/param vec A vector data structure of type LLInt
LLInt vec;
init_llong_vector(&vec, 5);
long long int a[5] = { 1, 2, 3, 4, 5};
insert_llong_vector(&vec, a, 5, 0);
long long int min = min_llong_vector(&vec);
PRINT(max);
// >> 1
free_llong_vector(&vec);
Definition at line 4235 of file vector.c.
                                           {
    if (vec->active_length == 1) return vec->array[0];
    long long int max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max > vec->array[i]) max = vec->array[i];
    }
    return max;
}
min_long_vector()
long int min_long_vector (LInt * vec)
This function will determine the min value in a vector data structure of type LInt
/param vec A vector data structure of type LInt
LInt vec;
init_long_vector(&vec, 5);
long int a[5] = { 1, 2, 3, 4, 5};
insert_long_vector(&vec, a, 5, 0);
long int min = min_long_vector(&vec);
PRINT(max);
// >> 1
free_long_vector(&vec);
Definition at line 4213 of file vector.c.
                                    {
    if (vec->active_length == 1) return vec->array[0];
    long int max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max > vec->array[i]) max = vec->array[i];
    }
    return max;
}
min_short_vector()
short int min_short_vector (Short * vec)
This function will determine the min value in a vector data structure of type Short
/param vec A vector data structure of type Short
Short vec;
init_short_vector(&vec, 5);
short int a[5] = { 1, 2, 3, 4, 5};
insert_short_vector(&vec, a, 5, 0);
short int min = min_short_vector(&vec);
PRINT(max);
// >> 1
free_short_vector(&vec);
Definition at line 4169 of file vector.c.
                                       {
    if (vec->active_length == 1) return vec->array[0];
    short int max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max > vec->array[i]) max = vec->array[i];
    }
    return max;
}
min_uchar_vector()
unsigned char min_uchar_vector (UChar * vec)
This function will determine the min value in a vector data structure of type UChar
/param vec A vector data structure of type Short /param min The minimum values
UChar vec;
init_uchar_vector(&vec, 5);
unsigned char a[5] = { 1, 2, 3, 4, 5};
insert_uchar_vector(&vec, a, 5, 0);
unsigned char min = min_uchar_vector(&vec);
PRINT(max);
// >> 1
free_uchar_vector(&vec);
Definition at line 4158 of file vector.c.
                                           {
    if (vec->active_length == 1) return vec->array[0];
    unsigned char max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max > vec->array[i]) max = vec->array[i];
    }
    return max;
}
min_uint_vector()
unsigned int min_uint_vector (UInt * vec)
This function will determine the min value in a vector data structure of type UInt
/param vec A vector data structure of type UInt
UInt vec;
init_uint_vector(&vec, 5);
unsigned int a[5] = { 1, 2, 3, 4, 5};
insert_uint_vector(&vec, a, 5, 0);
unsigned int min = min_uint_vector(&vec);
PRINT(max);
// >> 1
free_uint_vector(&vec);
Definition at line 4202 of file vector.c.
                                        {
    if (vec->active_length == 1) return vec->array[0];
    unsigned int max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max > vec->array[i]) max = vec->array[i];
    }
    return max;
}
min_ullong_vector()
unsigned long long int min_ullong_vector (ULLInt * vec)
This function will determine the min value in a vector data structure of type ULLInt
/param vec A vector data structure of type ULLInt
ULLInt vec;
init_ullong_vector(&vec, 5);
unsigned long long int a[5] = { 1, 2, 3, 4, 5};
insert_ullong_vector(&vec, a, 5, 0);
unsigned long long int min = min_ullong_vector(&vec);
PRINT(max);
// >> 1
free_ullong_vector(&vec);
Definition at line 4246 of file vector.c.
                                                      {
    if (vec->active_length == 1) return vec->array[0];
    unsigned long long int max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max > vec->array[i]) max = vec->array[i];
    }
    return max;
}
min_ulong_vector()
unsigned long int min_ulong_vector (ULInt * vec)
This function will determine the min value in a vector data structure of type ULInt
/param vec A vector data structure of type ULInt
ULInt vec;
init_ulong_vector(&vec, 5);
unsigned long int a[5] = { 1, 2, 3, 4, 5};
insert_ulong_vector(&vec, a, 5, 0);
unsigned long int min = min_ulong_vector(&vec);
PRINT(max);
// >> 1
free_ulong_vector(&vec);
Definition at line 4224 of file vector.c.
                                               {
    if (vec->active_length == 1) return vec->array[0];
    unsigned long int max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max > vec->array[i]) max = vec->array[i];
    }
    return max;
}
min_ushort_vector()
unsigned short int min_ushort_vector (UShort * vec)
This function will determine the min value in a vector data structure of type UShort
/param vec A vector data structure of type UShort
UShort vec;
init_ushort_vector(&vec, 5);
unsigned short int a[5] = { 1, 2, 3, 4, 5};
insert_ushort_vector(&vec, a, 5, 0);
unsigned short int min = min_ushort_vector(&vec);
PRINT(max);
// >> 1
free_ushort_vector(&vec);
Definition at line 4180 of file vector.c.
                                                  {
    if (vec->active_length == 1) return vec->array[0];
    unsigned short int max = vec->array[0];
    for (size_t i = 1; i < vec->active_length; i++) {
        if (max > vec->array[i]) max = vec->array[i];
    }
    return max;
}
pop_bool_vector_index()
int pop_bool_vector_index (Bool * vec, size_t index)
This function will pop a value from an Bool struct container as a user defined index. This function runs fastest, when the index is the last populated index.
/param vec An struct container of type Bool /param index The index from which data is to be popped.
Bool vec;
init_bool_vector(vec, 5);
push_bool_vector(vec, true);
push_bool_vector(vec, true);
push_bool_vector(vec, true);
push_bool_vector(vec, false);
push_bool_vector(vec, false);
pop_bool_vector_index(vec, 0);
pop_bool_vector_index(vec, vec.active_length);
PRINT(vec);
[ true, true, false ]
free_char_vector(&vec);
Definition at line 1534 of file vector.c.
                                                   {
    if (index >= vec->active_length) {
        fprintf(stderr, "index, out of bounds in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    unsigned char *dst = (unsigned char *)vec->array + index * sizeof(bool);
    memmove(dst, dst + sizeof(bool), sizeof(bool) * (vec->active_length - index - 1));
    vec->array[vec->active_length - 1] = 0;
    vec->active_length -= 1;
    return 1;
}
Referenced by delete_bool_vector_duplicates().
pop_char_vector_index()
int pop_char_vector_index (Char * vec, size_t index)
This function will pop a value from an Char struct container as a user defined index. This function runs fastest, when the index is the last populated index.
/param vec An struct container of type Char /param index The index from which data is to be popped.
Char vec;
init_char_vector(vec, 5);
push_char_vector(vec, 1);
push_char_vector(vec, 2);
push_char_vector(vec, 3);
push_char_vector(vec, 4);
push_char_vector(vec, 5);
pop_char_vector_index(vec, 0);
pop_char_vector_index(vec, vec.active_length);
PRINT(vec);
[ 2, 3, 4 ]
free_char_vector(&vec);
Definition at line 1509 of file vector.c.
                                                   {
    if (index >= vec->active_length) {
        fprintf(stderr, "index, out of bounds in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    char *dst = (char *)vec->array + index * sizeof(char);
    memmove(dst, dst + sizeof(char), sizeof(char) * (vec->active_length - index - 1));
    vec->array[vec->active_length - 1] = 0;
    vec->active_length -= 1;
    return 1;
}
Referenced by delete_char_vector_duplicates().
pop_double_vector_index()
int pop_double_vector_index (Dble * vec, size_t index)
This function will pop a value from an Dble struct container as a user defined index. This function runs fastest, when the index is the last populated index.
/param vec An struct container of type Dble /param index The index from which data is to be popped.
Dble vec;
init_double_vector(vec, 5);
push_double_vector(vec, 1);
push_double_vector(vec, 2);
push_double_vector(vec, 3);
push_double_vector(vec, 4);
push_double_vector(vec, 5);
pop_double_vector_index(vec, 0);
pop_double_vector_index(vec, vec.active_length);
PRINT(vec);
[ 2, 3, 4 ]
free_double_vector(&vec);
Definition at line 1483 of file vector.c.
                                                     {
    if (index >= vec->active_length) {
        fprintf(stderr, "index, out of bounds in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    unsigned char *dst = (unsigned char *)vec->array + index * sizeof(double);
    memmove(dst, dst + sizeof(double), sizeof(double) * (vec->active_length - index - 1));
    vec->array[vec->active_length - 1] = 0;
    vec->active_length -= 1;
    return 1;
}
Referenced by delete_double_vector_duplicates().
pop_float_vector_index()
int pop_float_vector_index (Flt * vec, size_t index)
This function will pop a value from an Flt struct container as a user defined index. This function runs fastest, when the index is the last populated index.
/param vec An struct container of type Flt /param index The index from which data is to be popped.
Flt vec;
init_float_vector(vec, 5);
push_float_vector(vec, 1);
push_float_vector(vec, 2);
push_float_vector(vec, 3);
push_float_vector(vec, 4);
push_float_vector(vec, 5);
pop_float_vector_index(vec, 0);
pop_float_vector_index(vec, vec.active_length);
PRINT(vec);
[ 2, 3, 4 ]
free_float_vector(&vec);
Definition at line 1470 of file vector.c.
                                                   {
    if (index >= vec->active_length) {
        fprintf(stderr, "index, out of bounds in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    unsigned char *dst = (unsigned char *)vec->array + index * sizeof(float);
    memmove(dst, dst + sizeof(float), sizeof(float) * (vec->active_length - index - 1));
    vec->array[vec->active_length - 1] = 0;
    vec->active_length -= 1;
    return 1;
}
Referenced by delete_float_vector_duplicates().
pop_int_vector_index()
int pop_int_vector_index (Int * vec, size_t index)
This function will pop a value from an Int struct container as a user defined index. This function runs fastest, when the index is the last populated index.
/param vec An struct container of type Int /param index The index from which data is to be popped.
Int vec;
init_int_vector(vec, 5);
push_int_vector(vec, 1);
push_int_vector(vec, 2);
push_int_vector(vec, 3);
push_int_vector(vec, 4);
push_int_vector(vec, 5);
pop_int_vector_index(vec, 0);
pop_int_vector_index(vec, vec.active_length);
PRINT(vec);
[ 2, 3, 4 ]
free_int_vector(&vec);
Definition at line 1392 of file vector.c.
                                                 {
    if (index >= vec->active_length) {
        fprintf(stderr, "index, out of bounds in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    unsigned char *dst = (unsigned char *)vec->array + index * sizeof(int);
    memmove(dst, dst + sizeof(int), sizeof(int) * (vec->active_length - index - 1));
    vec->array[vec->active_length - 1] = 0;
    vec->active_length -= 1;
    return 1;
}
Referenced by delete_int_vector_duplicates().
pop_ldouble_vector_index()
int pop_ldouble_vector_index (LDble * vec, size_t index)
This function will pop a value from an LDble struct container as a user defined index. This function runs fastest, when the index is the last populated index.
/param vec An struct container of type LDble /param index The index from which data is to be popped.
LDble vec;
init_ldouble_vector(vec, 5);
push_ldouble_vector(vec, 1);
push_ldouble_vector(vec, 2);
push_ldouble_vector(vec, 3);
push_ldouble_vector(vec, 4);
push_ldouble_vector(vec, 5);
pop_ldouble_vector_index(vec, 0);
pop_ldouble_vector_index(vec, vec.active_length);
PRINT(vec);
[ 2, 3, 4 ]
free_ldouble_vector(&vec);
Definition at line 1496 of file vector.c.
                                                       {
    if (index >= vec->active_length) {
        fprintf(stderr, "index, out of bounds in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    unsigned char *dst = (unsigned char *)vec->array + index * sizeof(long double);
    memmove(dst, dst + sizeof(long double), sizeof(long double) * (vec->active_length - index - 1));
    vec->array[vec->active_length - 1] = 0;
    vec->active_length -= 1;
    return 1;
}
Referenced by delete_ldouble_vector_duplicates().
pop_llong_vector_index()
int pop_llong_vector_index (LLInt * vec, size_t index)
This function will pop a value from an LLInt struct container as a user defined index. This function runs fastest, when the index is the last populated index.
/param vec An struct container of type LLInt /param index The index from which data is to be popped.
LLInt vec;
init_llong_vector(vec, 5);
push_llong_vector(vec, 1);
push_llong_vector(vec, 2);
push_llong_vector(vec, 3);
push_llong_vector(vec, 4);
push_llong_vector(vec, 5);
pop_llong_vector_index(vec, 0);
pop_llong_vector_index(vec, vec.active_length);
PRINT(vec);
[ 2, 3, 4 ]
free_llong_vector(&vec);
Definition at line 1444 of file vector.c.
                                                     {
    if (index >= vec->active_length) {
        fprintf(stderr, "index, out of bounds in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    unsigned char *dst = (unsigned char *)vec->array + index * sizeof(long long int);
    memmove(dst, dst + sizeof(long long int), sizeof(long long int) * (vec->active_length - index - 1));
    vec->array[vec->active_length - 1] = 0;
    vec->active_length -= 1;
    return 1;
}
Referenced by delete_llong_vector_duplicates().
pop_long_vector_index()
int pop_long_vector_index (LInt * vec, size_t index)
This function will pop a value from an LInt struct container as a user defined index. This function runs fastest, when the index is the last populated index.
/param vec An struct container of type LInt /param index The index from which data is to be popped.
LInt vec;
init_long_vector(vec, 5);
push_long_vector(vec, 1);
push_long_vector(vec, 2);
push_long_vector(vec, 3);
push_long_vector(vec, 4);
push_long_vector(vec, 5);
pop_long_vector_index(vec, 0);
pop_long_vector_index(vec, vec.active_length);
PRINT(vec);
[ 2, 3, 4 ]
free_long_vector(&vec);
Definition at line 1418 of file vector.c.
                                                   {
    if (index >= vec->active_length) {
        fprintf(stderr, "index, out of bounds in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    unsigned char *dst = (unsigned char *)vec->array + index * sizeof(long int);
    memmove(dst, dst + sizeof(long int), sizeof(long int) * (vec->active_length - index - 1));
    vec->array[vec->active_length - 1] = 0;
    vec->active_length -= 1;
    return 1;
}
Referenced by delete_long_vector_duplicates().
pop_short_vector_index()
int pop_short_vector_index (Short * vec, size_t index)
pop_type_stack_index functions
This function will pop a value from an Short struct container as a user defined index. This function runs fastest, when the index is the last populated index.
/param vec An struct container of type Short /param index The index from which data is to be popped.
Short vec;
init_short_vector(vec, 5);
push_short_vector(vec, 1);
push_short_vector(vec, 2);
push_short_vector(vec, 3);
push_short_vector(vec, 4);
push_short_vector(vec, 5);
pop_short_vector_index(vec, 0);
pop_short_vector_index(vec, vec.active_length);
PRINT(vec);
[ 2, 3, 4 ]
free_short_vector(&vec);
Definition at line 1366 of file vector.c.
                                                     {
    if (index >= vec->active_length) {
        fprintf(stderr, "index, out of bounds in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    unsigned char *dst = (unsigned char *)vec->array + index * sizeof(short int);
    memmove(dst, dst + sizeof(short int), sizeof(short int) * (vec->active_length - index - 1));
    vec->array[vec->active_length - 1] = 0;
    vec->active_length -= 1;
    return 1;
}
Referenced by delete_short_vector_duplicates().
pop_string_vector_index()
int pop_string_vector_index (String * vec, size_t index)
This function will pop a value from an Char struct container as a user defined index. This function runs fastest, when the index is the last populated index.
/param vec An struct container of type Char /param index The index from which data is to be popped.
String vec;
init_string_vector(vec);
push_string_vector(vec, "Hello", vec.active_length);
push_string_vector(vec, "Goodbye", vec.active_length);
push_string_vector(vec, "again", vec.active_length);
push_string_vector(vec, Test", vec.active_length);
push_string_vector(vec, "One", vec.active_length);
pop_string_vector_index(vec, 0);
PRINT(vec);
[ Goodbye, again, Test, One ]
free_string_vector(&vec);
Definition at line 1547 of file vector.c.
                                                       {
    if (index + 1 > vec->active_length) {
        fprintf(stderr, "Index out of range at file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    char *value = vec->array[index];
    if (index + 1 < vec->active_length) {
        memmove(vec->array + index, vec->array + index + 1, sizeof(*vec->array) * (vec->active_length - index - 1));
    }
    char **resized = realloc(vec->array, sizeof(*vec->array) * (vec->active_length - 1));
    if (!resized) {
        fprintf(stderr, "String index out of range in file %s on line %d\n", __FILE__, __LINE__);
        memmove(vec->array + index + 1, vec->array + index, sizeof(char *) * (vec->active_length - index - 1));
        vec->array[index] = value;
        return -1;
    }
    vec->array = resized;
    vec->active_length--;
    free(value);
    return 1;
}
References String::active_length, and String::array.
Referenced by delete_string_vector_duplicates(), replace_string_vector_values(), and reverse_string_vector().
pop_uchar_vector_index()
int pop_uchar_vector_index (UChar * vec, size_t index)
This function will pop a value from an Char struct container as a user defined index. This function runs fastest, when the index is the last populated index.
/param vec An struct container of type UChar /param index The index from which data is to be popped.
UChar vec;
init_uchar_vector(vec, 5);
push_uchar_vector(vec, 1);
push_uchar_vector(vec, 2);
push_uchar_vector(vec, 3);
push_uchar_vector(vec, 4);
push_uchar_vector(vec, 5);
pop_uchar_vector_index(vec, 0);
pop_uchar_vector_index(vec, vec.active_length);
PRINT(vec);
[ 2, 3, 4 ]
free_uchar_vector(&vec);
Definition at line 1521 of file vector.c.
                                                     {
    if (index >= vec->active_length) {
        fprintf(stderr, "index, out of bounds in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    unsigned char *dst = (unsigned char *)vec->array + index * sizeof(unsigned char);
    memmove(dst, dst + sizeof(char), sizeof(char) * (vec->active_length - index - 1));
    vec->array[vec->active_length - 1] = 0;
    vec->active_length -= 1;
    return 1;
}
Referenced by delete_uchar_vector_duplicates().
pop_uint_vector_index()
int pop_uint_vector_index (UInt * vec, size_t index)
This function will pop a value from an UInt struct container as a user defined index. This function runs fastest, when the index is the last populated index.
/param vec An struct container of type UInt /param index The index from which data is to be popped.
UInt vec;
init_uint_vector(vec, 5);
push_uint_vector(vec, 1);
push_uint_vector(vec, 2);
push_uint_vector(vec, 3);
push_uint_vector(vec, 4);
push_uint_vector(vec, 5);
pop_uint_vector_index(vec, 0);
pop_uint_vector_index(vec, vec.active_length);
PRINT(vec);
[ 2, 3, 4 ]
free_uint_vector(&vec);
Definition at line 1405 of file vector.c.
                                                   {
    if (index >= vec->active_length) {
        fprintf(stderr, "index, out of bounds in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    unsigned char *dst = (unsigned char *)vec->array + index * sizeof(unsigned int);
    memmove(dst, dst + sizeof(unsigned int), sizeof(unsigned int) * (vec->active_length - index - 1));
    vec->array[vec->active_length - 1] = 0;
    vec->active_length -= 1;
    return 1;
}
Referenced by delete_uint_vector_duplicates().
pop_ullong_vector_index()
int pop_ullong_vector_index (ULLInt * vec, size_t index)
This function will pop a value from an ULLInt struct container as a user defined index. This function runs fastest, when the index is the last populated index.
/param vec An struct container of type ULLInt /param index The index from which data is to be popped.
ULLInt vec;
init_ullong_vector(vec, 5);
push_ullong_vector(vec, 1);
push_ullong_vector(vec, 2);
push_ullong_vector(vec, 3);
push_ullong_vector(vec, 4);
push_ullong_vector(vec, 5);
pop_ullong_vector_index(vec, 0);
pop_ullong_vector_index(vec, vec.active_length);
PRINT(vec);
[ 2, 3, 4 ]
free_ullong_vector(&vec);
Definition at line 1457 of file vector.c.
                                                       {
    if (index >= vec->active_length) {
        fprintf(stderr, "index, out of bounds in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    unsigned char *dst = (unsigned char *)vec->array + index * sizeof(unsigned long long int);
    memmove(dst, dst + sizeof(unsigned long long int), sizeof(unsigned long long int) * (vec->active_length - index - 1));
    vec->array[vec->active_length - 1] = 0;
    vec->active_length -= 1;
    return 1;
}
Referenced by delete_ullong_vector_duplicates().
pop_ulong_vector_index()
int pop_ulong_vector_index (ULInt * vec, size_t index)
This function will pop a value from an ULInt struct container as a user defined index. This function runs fastest, when the index is the last populated index.
/param vec An struct container of type ULInt /param index The index from which data is to be popped.
ULInt vec;
init_ulong_vector(vec, 5);
push_ulong_vector(vec, 1);
push_ulong_vector(vec, 2);
push_ulong_vector(vec, 3);
push_ulong_vector(vec, 4);
push_ulong_vector(vec, 5);
pop_ulong_vector_index(vec, 0);
pop_ulong_vector_index(vec, vec.active_length);
PRINT(vec);
[ 2, 3, 4 ]
free_ulong_vector(&vec);
Definition at line 1431 of file vector.c.
                                                     {
    if (index >= vec->active_length) {
        fprintf(stderr, "index, out of bounds in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    unsigned char *dst = (unsigned char *)vec->array + index * sizeof(unsigned long int);
    memmove(dst, dst + sizeof(unsigned long int), sizeof(unsigned long int) * (vec->active_length - index - 1));
    vec->array[vec->active_length - 1] = 0;
    vec->active_length -= 1;
    return 1;
}
Referenced by delete_ulong_vector_duplicates().
pop_ushort_vector_index()
int pop_ushort_vector_index (UShort * vec, size_t index)
This function will pop a value from an UShort struct container as a user defined index. This function runs fastest, when the index is the last populated index.
/param vec An struct container of type UShort /param index The index from which data is to be popped.
UShort vec;
init_ushort_vector(vec, 5);
push_ushort_vector(vec, 1);
push_ushort_vector(vec, 2);
push_ushort_vector(vec, 3);
push_ushort_vector(vec, 4);
push_ushort_vector(vec, 5);
pop_ushort_vector_index(vec, 0);
pop_ushort_vector_index(vec, vec.active_length);
PRINT(vec);
[ 2, 3, 4 ]
free_ushort_vector(&vec);
Definition at line 1379 of file vector.c.
                                                       {
    if (index >= vec->active_length) {
        fprintf(stderr, "index, out of bounds in file %s at line %d\n", __FILE__, __LINE__);
        return -1;
    }
    unsigned char *dst = (unsigned char *)vec->array + index * sizeof(unsigned short int);
    memmove(dst, dst + sizeof(unsigned short int), sizeof(unsigned short int) * (vec->active_length - index - 1));
    vec->array[vec->active_length - 1] = 0;
    vec->active_length -= 1;
    return 1;
}
Referenced by delete_ushort_vector_duplicates().
push_bool_vector()
int push_bool_vector (Bool * vec, bool value, size_t index)
Definition at line 778 of file vector.c.
                                                          {
    if (index >= vec->active_length + 1) {
        fprintf(stderr, "Index in fsize_tile %s on line %d is out of bounds\n", __FILE__, __LINE__);
        return -1;
    }
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + 1) * 2;
        bool *ptr = (bool *)realloc(vec->array, size * sizeof(bool));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (index + 1) * sizeof(bool),
            ((char *)vec->array) + index * sizeof(bool),
            (vec->active_length - index) * sizeof(bool));
    vec->array[index] = value;
    vec->active_length += 1;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by repeat_bool_vector().
push_char_vector()
int push_char_vector (Char * vec, char value, size_t index)
Definition at line 712 of file vector.c.
                                                          {
    if (index >= vec->active_length + 1) {
        fprintf(stderr, "Index in fsize_tile %s on line %d is out of bounds\n", __FILE__, __LINE__);
        return -1;
    }
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + 1) * 2;
        char *ptr = (char *)realloc(vec->array, size * sizeof(char));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (index + 1) * sizeof(char),
            ((char *)vec->array) + index * sizeof(char),
            (vec->active_length - index) * sizeof(char));
    vec->array[index] = value;
    vec->active_length += 1;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by cumsum_char_vector(), range_char_vector(), and repeat_char_vector().
push_double_vector()
int push_double_vector (Dble * vec, double value, size_t index)
Definition at line 646 of file vector.c.
                                                              {
    if (index >= vec->active_length + 1) {
        fprintf(stderr, "Index in file %s on line %d is out of bounds\n", __FILE__, __LINE__);
        return -1;
    }
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + 1) * 2;
        double *ptr = (double *)realloc(vec->array, size * sizeof(double));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (index + 1) * sizeof(double),
            ((char *)vec->array) + index * sizeof(double),
            (vec->active_length - index) * sizeof(double));
    vec->array[index] = value;
    vec->active_length += 1;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by cumsum_double_vector(), range_double_vector(), and repeat_double_vector().
push_float_vector()
int push_float_vector (Flt * vec, float value, size_t index)
Definition at line 613 of file vector.c.
                                                           {
    if (index >= vec->active_length + 1) {
        fprintf(stderr, "Index in file %s on line %d is out of bounds\n", __FILE__, __LINE__);
        return -1;
    }
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + 1) * 2;
        float *ptr = (float *)realloc(vec->array, size * sizeof(float));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (index + 1) * sizeof(float),
            ((char *)vec->array) + index * sizeof(float),
            (vec->active_length - index) * sizeof(float));
    vec->array[index] = value;
    vec->active_length += 1;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by cumsum_float_vector(), range_float_vector(), and repeat_float_vector().
push_int_vector()
int push_int_vector (Int * vec, int value, size_t index)
Definition at line 415 of file vector.c.
                                                       {
    if (index >= vec->active_length + 1) {
        fprintf(stderr, "Index in file %s on line %d is out of bounds\n", __FILE__, __LINE__);
        return -1;
    }
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + 1) * 2;
        int *ptr = (int *)realloc(vec->array, size * sizeof(int));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (index + 1) * sizeof(int),
            ((char *)vec->array) + index * sizeof(int),
            (vec->active_length - index) * sizeof(int));
    vec->array[index] = value;
    vec->active_length += 1;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by cumsum_int_vector(), range_int_vector(), and repeat_int_vector().
push_ldouble_vector()
int push_ldouble_vector (LDble * vec, long double value, size_t index)
Definition at line 679 of file vector.c.
                                                                     {
    if (index >= vec->active_length + 1) {
        fprintf(stderr, "Index in file %s on line %d is out of bounds\n", __FILE__, __LINE__);
        return -1;
    }
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + 1) * 2;
        long double *ptr = (long double *)realloc(vec->array, size * sizeof(long double));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (index + 1) * sizeof(long double),
            ((char *)vec->array) + index * sizeof(long double),
            (vec->active_length - index) * sizeof(long double));
    vec->array[index] = value;
    vec->active_length += 1;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by cumsum_ldouble_vector(), range_ldouble_vector(), and repeat_ldouble_vector().
push_llong_vector()
int push_llong_vector (LLInt * vec, long long int value, size_t index)
Definition at line 547 of file vector.c.
                                                                     {
    if (index >= vec->active_length + 1) {
        fprintf(stderr, "Index in file %s on line %d is out of bounds\n", __FILE__, __LINE__);
        return -1;
    }
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + 1) * 2;
        long long int *ptr = (long long int *)realloc(vec->array, size * sizeof(long long int));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (index + 1) * sizeof(long long int),
            ((char *)vec->array) + index * sizeof(long long int),
            (vec->active_length - index) * sizeof(long long int));
    vec->array[index] = value;
    vec->active_length += 1;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by cumsum_llong_vector(), range_llong_vector(), and repeat_llong_vector().
push_long_vector()
int push_long_vector (LInt * vec, long int value, size_t index)
Definition at line 481 of file vector.c.
                                                              {
    if (index >= vec->active_length + 1) {
        fprintf(stderr, "Index in file %s on line %d is out of bounds\n", __FILE__, __LINE__);
        return -1;
    }
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + 1) * 2;
        long int *ptr = (long int *)realloc(vec->array, size * sizeof(long int));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (index + 1) * sizeof(long int),
            ((char *)vec->array) + index * sizeof(long int),
            (vec->active_length - index) * sizeof(long int));
    vec->array[index] = value;
    vec->active_length += 1;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by cumsum_long_vector(), range_long_vector(), and repeat_long_vector().
push_short_vector()
int push_short_vector (Short * vec, short int value, size_t index)
Definition at line 349 of file vector.c.
                                                                 {
    if (index >= vec->active_length + 1) {
        fprintf(stderr, "Index in file %s on line %d is out of bounds\n", __FILE__, __LINE__);
        return -1;
    }
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + 1) * 2;
        short int *ptr = (short int *)realloc(vec->array, size * sizeof(short int));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (index + 1) * sizeof(short int),
            ((char *)vec->array) + index * sizeof(short int),
            (vec->active_length - index) * sizeof(short int));
    vec->array[index] = value;
    vec->active_length += 1;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by cumsum_short_vector(), range_short_vector(), and repeat_short_vector().
push_string_vector()
int push_string_vector (String * vec, char * value, size_t index)
This function will push a single string to an existing string vector container
/param vec A vector struct of type String /param value A string /param index The index where the string is to be pushed
#include "vector.h"
#include "print.h"
String vec;
init_string_vector(vec);
push_string_vector(&vec, "Hello", 0);
push_string_vector(&vec, "Goodbye", 1);
push_string_vector(&vec, "Again", 0);
PRINT(vec);
// >> [ Again, Hello, Goodbye ]
free_string_vector(&vec);
Definition at line 811 of file vector.c.
                                                               {
    if (index > vec->active_length) {
        fprintf(stderr, "String index out of range in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    char **resized = realloc(vec->array, sizeof(*vec->array) * (vec->active_length + 1));
    if (!resized) {
        fprintf(stderr, "realloc failed in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    value = strdup(value);
    vec->array = resized;
    if (index < vec->active_length) {
        memmove(vec->array + index + 1, vec->array + index, sizeof(*vec->array) * (vec->active_length - index));
    }
    vec->array[index] = value;
    vec->active_length++;
    return 1;
}
References String::active_length, and String::array.
Referenced by copy_string_vector(), repeat_string_vector(), replace_string_vector_values(), and reverse_string_vector().
push_uchar_vector()
int push_uchar_vector (UChar * vec, unsigned char value, size_t index)
Definition at line 745 of file vector.c.
                                                                     {
    if (index >= vec->active_length + 1) {
        fprintf(stderr, "Index in fsize_tile %s on line %d is out of bounds\n", __FILE__, __LINE__);
        return -1;
    }
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + 1) * 2;
        unsigned char *ptr = (unsigned char *)realloc(vec->array, size * sizeof(unsigned char));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((unsigned char *)vec->array) + (index + 1) * sizeof(unsigned char),
            ((unsigned char *)vec->array) + index * sizeof(unsigned char),
            (vec->active_length - index) * sizeof(unsigned char));
    vec->array[index] = value;
    vec->active_length += 1;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by cumsum_uchar_vector(), range_uchar_vector(), and repeat_uchar_vector().
push_uint_vector()
int push_uint_vector (UInt * vec, unsigned int value, size_t index)
Definition at line 448 of file vector.c.
                                                                  {
    if (index >= vec->active_length + 1) {
        fprintf(stderr, "Index in file %s on line %d is out of bounds\n", __FILE__, __LINE__);
        return -1;
    }
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + 1) * 2;
        unsigned int *ptr = (unsigned int *)realloc(vec->array, size * sizeof(unsigned int));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (index + 1) * sizeof(unsigned int),
            ((char *)vec->array) + index * sizeof(unsigned int),
            (vec->active_length - index) * sizeof(unsigned int));
    vec->array[index] = value;
    vec->active_length += 1;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by cumsum_uint_vector(), range_uint_vector(), and repeat_uint_vector().
push_ullong_vector()
int push_ullong_vector (ULLInt * vec, unsigned long long int value, size_t index)
Definition at line 580 of file vector.c.
                                                                                {
    if (index >= vec->active_length + 1) {
        fprintf(stderr, "Index in file %s on line %d is out of bounds\n", __FILE__, __LINE__);
        return -1;
    }
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + 1) * 2;
        unsigned long long int *ptr = (unsigned long long int *)realloc(vec->array, size * sizeof(unsigned long long int));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (index + 1) * sizeof(unsigned long long int),
            ((char *)vec->array) + index * sizeof(unsigned long long int),
            (vec->active_length - index) * sizeof(unsigned long long int));
    vec->array[index] = value;
    vec->active_length += 1;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by cumsum_ullong_vector(), range_ullong_vector(), and repeat_ullong_vector().
push_ulong_vector()
int push_ulong_vector (ULInt * vec, unsigned long int value, size_t index)
Definition at line 514 of file vector.c.
                                                                         {
    if (index >= vec->active_length + 1) {
        fprintf(stderr, "Index in file %s on line %d is out of bounds\n", __FILE__, __LINE__);
        return -1;
    }
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + 1) * 2;
        unsigned long int *ptr = (unsigned long int *)realloc(vec->array, size * sizeof(unsigned long int));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (index + 1) * sizeof(unsigned long int),
            ((char *)vec->array) + index * sizeof(unsigned long int),
            (vec->active_length - index) * sizeof(unsigned long int));
    vec->array[index] = value;
    vec->active_length += 1;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by cumsum_ulong_vector(), range_ulong_vector(), and repeat_ulong_vector().
push_ushort_vector()
int push_ushort_vector (UShort * vec, unsigned short int value, size_t index)
Definition at line 382 of file vector.c.
                                                                            {
    if (index >= vec->active_length + 1) {
        fprintf(stderr, "Index in file %s on line %d is out of bounds\n", __FILE__, __LINE__);
        return -1;
    }
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == STATIC) {
        fprintf(stderr, "Cannont extend static array allocation in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    // Allocate memory if necessary
    if ((vec->active_length + 1 > vec->allocated_length) && vec->dat_type == DYNAMIC) {
        size_t size = (vec->active_length + 1) * 2;
        unsigned short int *ptr = (unsigned short int *)realloc(vec->array, size * sizeof(unsigned short int));
        // Verify that sufficient memory exists
        if (ptr == NULL) {
            fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
            free(ptr);
            return -1;
        }
        // allocate memory
        vec->array = ptr;
        vec->allocated_length = size;
    }
    // Add variables and update metadata
    memmove(((char *)vec->array) + (index + 1) * sizeof(unsigned short int),
            ((char *)vec->array) + index * sizeof(unsigned short int),
            (vec->active_length - index) * sizeof(unsigned short int));
    vec->array[index] = value;
    vec->active_length += 1;
    return 1;
}
References DYNAMIC, and STATIC.
Referenced by cumsum_ushort_vector(), range_ushort_vector(), and repeat_ushort_vector().
range_char_vector()
void range_char_vector (Char * vec, char start, char end, char delta)
This function will add a range of data points to a vector data structure that start at a user defined data point and ends at another, or the nearest data point.
/param vec A vector data structure of type Char /param start The start point /param end The end point /param delta The difference between each data point
Char vec;
init_char_vector(&vec, 10);
range_char_vector(&vec, 2, 20, 2);
PRINT(vec);
// [ 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 ]
free_char_vector(&vec);
Definition at line 4281 of file vector.c.
                                                                    {
    char num = (end - start) / delta;
    char advance = start;
    for (size_t i = 0; i < num + 1; i++) {
        push_char_vector(vec, advance, vec->active_length);
        advance += delta;
    }
}
References push_char_vector().
range_double_vector()
void range_double_vector (Dble * vec, double start, double end, double delta)
This function will add a range of data points to a vector data structure that start at a user defined data point and ends at another, or the nearest data point.
/param vec A vector data structure of type Dble /param start The start point /param end The end point /param delta The difference between each data point
Dble vec;
init_double_vectoe(&vec, 10);
range_double_vector(&vec, 2, 20, 2);
PRINT(vec);
// [ 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 ]
free_double_vector(&vec);
This function will add a range of data points to a vector data structure that start at a user defined data point and ends at another, or the nearest data point.
/param vec A vector data structure of type LDble /param start The start point /param end The end point /param delta The difference between each data point
LDble vec;
init_ldouble_vector(&vec, 10)
range_ldouble_vector(&vec, 2, 20, 2);
PRINT(vec);
// [ 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 ]
free_ldouble_vector(&vec);
Definition at line 4395 of file vector.c.
                                    {
    double num = (end - start) / delta;
    double advance = start;
    for (size_t i = 0; i < num + 1; i++) {
        push_double_vector(vec, advance, vec->active_length);
        advance += delta;
    }
}
References push_double_vector().
range_float_vector()
void range_float_vector (Flt * vec, float start, float end, float delta)
This function will add a range of data points to a vector data structure that start at a user defined data point and ends at another, or the nearest data point.
/param vec A vector data structure of type Flt /param start The start point /param end The end point /param delta The difference between each data point
Flt vec;
init_float_vector(&vec, 10);
range_float_vector(&vec, 2, 20, 2);
PRINT(vec);
// [ 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 ]
free_float_vector(&vec);
Definition at line 4385 of file vector.c.
                                                                       {
    float num = (end - start) / delta;
    float advance = start;
    for (size_t i = 0; i < num + 1; i++) {
        push_float_vector(vec, advance, vec->active_length);
        advance += delta;
    }
}
References push_float_vector().
range_int_vector()
void range_int_vector (Int * vec, int start, int end, int delta)
This function will add a range of data points to a vector data structure that start at a user defined data point and ends at another, or the nearest data point.
/param vec A vector data structure of type Int /param start The start point /param end The end point /param delta The difference between each data point
Int vec;
init_int_vector(&vec, 10);
range_int_vector(&vec, 2, 20, 2);
PRINT(vec);
// [ 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 ]
free_int_vector(&vec);
Definition at line 4322 of file vector.c.
                                                               {
    int num = (end - start) / delta;
    int advance = start;
    for (size_t i = 0; i < num + 1; i++) {
        push_int_vector(vec, advance, vec->active_length);
        advance += delta;
    }
}
References push_int_vector().
range_llong_vector()
void range_llong_vector (LLInt * vec, long long int start, long long int end, long long int delta)
This function will add a range of data points to a vector data structure that start at a user defined data point and ends at another, or the nearest data point.
/param vec A vector data structure of type LLInt /param start The start point /param end The end point /param delta The difference between each data point
LLInt vec;
init_llong_vector(&vec, 10);
range_llong_vector(&vec, 2, 20, 2);
PRINT(vec);
// [ 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 ]
free_llong_vector(&vec);
Definition at line 4364 of file vector.c.
                                                                                                 {
    long long int num = (end - start) / delta;
    long long int advance = start;
    for (size_t i = 0; i < num + 1; i++) {
        push_llong_vector(vec, advance, vec->active_length);
        advance += delta;
    }
}
References push_llong_vector().
range_long_vector()
void range_long_vector (LInt * vec, long int start, long int end, long int delta)
This function will add a range of data points to a vector data structure that start at a user defined data point and ends at another, or the nearest data point.
/param vec A vector data structure of type LInt /param start The start point /param end The end point /param delta The difference between each data point
LInt vec;
init_long_vector(&vec, 10);
range_long_vector(&vec, 2, 20, 2);
PRINT(vec);
// [ 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 ]
free_long_vector(&vec);
Definition at line 4343 of file vector.c.
                                                                                {
    long int num = (end - start) / delta;
    long int advance = start;
    for (size_t i = 0; i < num + 1; i++) {
        push_long_vector(vec, advance, vec->active_length);
        advance += delta;
    }
}
References push_long_vector().
range_short_vector()
void range_short_vector (Short * vec, short int start, short int end, short int delta)
This function will add a range of data points to a vector data structure that start at a user defined data point and ends at another, or the nearest data point.
/param vec A vector data structure of type Short /param start The start point /param end The end point /param delta The difference between each data point
Short vec;
init_short_vector(&vec, 10);
range_short_vector(&vec, 2, 20, 2);
PRINT(vec);
// [ 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 ]
free_short_vector(&vec);
Definition at line 4301 of file vector.c.
                                                                                     {
    short int num = (end - start) / delta;
    short int advance = start;
    for (size_t i = 0; i < num + 1; i++) {
        push_short_vector(vec, advance, vec->active_length);
        advance += delta;
    }
}
References push_short_vector().
range_uchar_vector()
void range_uchar_vector (UChar * vec, unsigned char start, unsigned char end, unsigned char delta)
This function will add a range of data points to a vector data structure that start at a user defined data point and ends at another, or the nearest data point.
/param vec A vector data structure of type UChar /param start The start point /param end The end point /param delta The difference between each data point
UChar vec;
init_uchar_vector(&vec, 10);
range_uchar_vector(&vec, 2, 20, 2);
PRINT(vec);
// [ 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 ]
free_uchar_vector(&vec);
Definition at line 4291 of file vector.c.
                                                                                                 {
    unsigned char num = (end - start) / delta;
    unsigned char advance = start;
    for (size_t i = 0; i < num + 1; i++) {
        push_uchar_vector(vec, advance, vec->active_length);
        advance += delta;
    }
}
References push_uchar_vector().
range_uint_vector()
void range_uint_vector (UInt * vec, unsigned int start, unsigned int end, unsigned int delta)
This function will add a range of data points to a vector data structure that start at a user defined data point and ends at another, or the nearest data point.
/param vec A vector data structure of type UInt /param start The start point /param end The end point /param delta The difference between each data point
UInt vec;
init_uint_vector(&vec, 10);
range_uint_vector(&vec, 2, 20, 2);
PRINT(vec);
// [ 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 ]
free_uint_vector(&vec);
Definition at line 4332 of file vector.c.
                                        {
    unsigned int num = (end - start) / delta;
    unsigned int advance = start;
    for (size_t i = 0; i < num + 1; i++) {
        push_uint_vector(vec, advance, vec->active_length);
        advance += delta;
    }
}
References push_uint_vector().
range_ullong_vector()
void range_ullong_vector (ULLInt * vec, unsigned long long int start, unsigned long long int end, unsigned long long int delta)
This function will add a range of data points to a vector data structure that start at a user defined data point and ends at another, or the nearest data point.
/param vec A vector data structure of type ULLInt /param start The start point /param end The end point /param delta The difference between each data point
ULLInt vec;
init_ullong_vector(&vec, 10);
range_ullong_vector(&vec, 2, 20, 2);
PRINT(vec);
// [ 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 ]
free_ullong_vector(&vec);
Definition at line 4374 of file vector.c.
                                                   {
    unsigned long long int num = (end - start) / delta;
    unsigned long long int advance = start;
    for (size_t i = 0; i < num + 1; i++) {
        push_ullong_vector(vec, advance, vec->active_length);
        advance += delta;
    }
}
References push_ullong_vector().
range_ulong_vector()
void range_ulong_vector (ULInt * vec, unsigned long int start, unsigned long int end, unsigned long int delta)
This function will add a range of data points to a vector data structure that start at a user defined data point and ends at another, or the nearest data point.
/param vec A vector data structure of type ULInt /param start The start point /param end The end point /param delta The difference between each data point
ULInt vec;
init_ulong_vector(&vec, 10);
range_ulong_vector(&vec, 2, 20, 2);
PRINT(vec);
// [ 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 ]
free_ulong_vector(&vec);
Definition at line 4353 of file vector.c.
                                              {
    unsigned long int num = (end - start) / delta;
    unsigned long int advance = start;
    for (size_t i = 0; i < num + 1; i++) {
        push_ulong_vector(vec, advance, vec->active_length);
        advance += delta;
    }
}
References push_ulong_vector().
range_ushort_vector()
void range_ushort_vector (UShort * vec, unsigned short int start, unsigned short int end, unsigned short int delta)
This function will add a range of data points to a vector data structure that start at a user defined data point and ends at another, or the nearest data point.
/param vec A vector data structure of type UShort /param start The start point /param end The end point /param delta The difference between each data point
UShort vec;
init_ushort_vector(&vec, 10);
range_ushort_vector(&vec, 2, 20, 2);
PRINT(vec);
// [ 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 ]
free_ushort_vector(&vec);
Definition at line 4311 of file vector.c.
                                                {
    unsigned short int num = (end - start) / delta;
    unsigned short int advance = start;
    for (size_t i = 0; i < num + 1; i++) {
        push_ushort_vector(vec, advance, vec->active_length);
        advance += delta;
    }
}
References push_ushort_vector().
repeat_bool_vector()
int repeat_bool_vector (Bool * vec, bool value, size_t num)
This function will repeat a user defined value in a vector or array data structure a user defined number of times.
/param vec A vector or array data structure of type Bool /param value a value of type bool that be repeated /param num The number of times a value is to be repeated
Bool vec;
init_bool_vector(&vec, 10);
repeat_bool_vector(&vec, true, 4);
PRINT(vec);
[ true, true, true, true, true ]
free_bool_vector(&vec);
Definition at line 5011 of file vector.c.
                                                          {
    int j;
    for (size_t i = 0; i < num; i++) {
        j = push_bool_vector(vec, value, vec->active_length);
        if (j < 0) return -1;
    }
    return 1;
}
References push_bool_vector().
repeat_char_vector()
int repeat_char_vector (Char * vec, char value, size_t num)
This function will repeat a user defined value in a vector or array data structure a user defined number of times.
/param vec A vector or array data structure of type Char /param value a value of type char that be repeated /param num The number of times a value is to be repeated
Char vec;
init_char_vector(&vec, 10);
repeat_char_vector(&vec, 'h', 4);
PRINT(vec);
[ H, H, H, H, H ]
free_char_vector(&vec);
Definition at line 5021 of file vector.c.
                                                          {
    int j;
    for (size_t i = 0; i < num; i++) {
        j = push_char_vector(vec, value, vec->active_length);
        if (j < 0) return -1;
    }
    return 1;
}
References push_char_vector().
repeat_double_vector()
int repeat_double_vector (Dble * vec, double value, size_t num)
This function will repeat a user defined value in a vector or array data structure a user defined number of times.
/param vec A vector or array data structure of type Dble /param value a value of type double that be repeated /param num The number of times a value is to be repeated
Dble vec;
init_double_vector(&vec, 10);
repeat_double_vector(&vec, 10., 4);
PRINT(vec);
[ 10, 10, 10, 10, 10 ]
free_double_vector(&vec);
Definition at line 4991 of file vector.c.
                                                              {
    int j;
    for (size_t i = 0; i < num; i++) {
        j = push_double_vector(vec, value, vec->active_length);
        if (j < 0) return -1;
    }
    return 1;
}
References push_double_vector().
repeat_float_vector()
int repeat_float_vector (Flt * vec, float value, size_t num)
This function will repeat a user defined value in a vector or array data structure a user defined number of times.
/param vec A vector or array data structure of type Flt /param value a value of type float that be repeated /param num The number of times a value is to be repeated
Flt vec;
init_float_vector(&vec, 10);
repeat_float_vector(&vec, 10.f, 4);
PRINT(vec);
[ 10.000, 10.000, 10.000, 10.000, 10.000 ]
free_float_vector(&vec);
Definition at line 4981 of file vector.c.
                                                           {
    int j;
    for (size_t i = 0; i < num; i++) {
        j = push_float_vector(vec, value, vec->active_length);
        if (j < 0) return -1;
    }
    return 1;
}
References push_float_vector().
repeat_int_vector()
int repeat_int_vector (Int * vec, int value, size_t num)
This function will repeat a user defined value in a vector or array data structure a user defined number of times.
/param vec A vector or array data structure of type Int /param value a value of type int that be repeated /param num The number of times a value is to be repeated
Int vec;
init_int_vector(&vec, 10);
repeat_int_vector(&vec, 10, 4);
PRINT(vec);
[ 10, 10, 10, 10, 10 ]
free_int_vector(&vec);
Definition at line 4921 of file vector.c.
                                                       {
    int j;
    for (size_t i = 0; i < num; i++) {
        j = push_int_vector(vec, value, vec->active_length);
        if (j < 0) return -1;
    }
    return 1;
}
References push_int_vector().
repeat_ldouble_vector()
int repeat_ldouble_vector (LDble * vec, long double value, size_t num)
This function will repeat a user defined value in a vector or array data structure a user defined number of times.
/param vec A vector or array data structure of type LDble /param value a value of type long double that be repeated /param num The number of times a value is to be repeated
LDble vec;
init_ldouble_vector(&vec, 10);
repeat_ldouble_vector(&vec, 10., 4);
PRINT(vec);
[ 10, 10, 10, 10, 10 ]
free_ldouble_vector(&vec);
Definition at line 5001 of file vector.c.
                                                                     {
    int j;
    for (size_t i = 0; i < num; i++) {
        j = push_ldouble_vector(vec, value, vec->active_length);
        if (j < 0) return -1;
    }
    return 1;
}
References push_ldouble_vector().
repeat_llong_vector()
int repeat_llong_vector (LLInt * vec, long long int value, size_t num)
This function will repeat a user defined value in a vector or array data structure a user defined number of times.
/param vec A vector or array data structure of type LLInt /param value a value of type long long int that be repeated /param num The number of times a value is to be repeated
LLInt vec;
init_llong_vector(&vec, 10);
repeat_llong_vector(&vec, 10, 4);
PRINT(vec);
[ 10, 10, 10, 10, 10 ]
free_llong_vector(&vec);
Definition at line 4961 of file vector.c.
                                                                     {
    int j;
    for (size_t i = 0; i < num; i++) {
        j = push_llong_vector(vec, value, vec->active_length);
        if (j < 0) return -1;
    }
    return 1;
}
References push_llong_vector().
repeat_long_vector()
int repeat_long_vector (LInt * vec, long int value, size_t num)
This function will repeat a user defined value in a vector or array data structure a user defined number of times.
/param vec A vector or array data structure of type LInt /param value a value of type long int that be repeated /param num The number of times a value is to be repeated
LInt vec;
init_long_vector(&vec, 10);
repeat_long_vector(&vec, 10, 4);
PRINT(vec);
[ 10, 10, 10, 10, 10 ]
free_long_vector(&vec);
Definition at line 4941 of file vector.c.
                                                              {
    int j;
    for (size_t i = 0; i < num; i++) {
        j = push_long_vector(vec, value, vec->active_length);
        if (j < 0) return -1;
    }
    return 1;
}
References push_long_vector().
repeat_short_vector()
int repeat_short_vector (Short * vec, short int value, size_t num)
This function will repeat a user defined value in a vector or array data structure a user defined number of times.
/param vec A vector or array data structure of type Short /param value a value of type short int that be repeated /param num The number of times a value is to be repeated
Short vec;
init_short_vector(&vec, 10);
repeat_short_vector(&vec, 10, 4);
PRINT(vec);
[ 10, 10, 10, 10, 10 ]
free_short_vector(&vec);
Definition at line 4901 of file vector.c.
                                                                 {
    int j;
    for (size_t i = 0; i < num; i++) {
        j = push_short_vector(vec, value, vec->active_length);
        if (j < 0) return -1;
    }
    return 1;
}
References push_short_vector().
repeat_string_vector()
int repeat_string_vector (String * vec, char * value, size_t num)
This function will repeat a user defined value in a vector or array data structure a user defined number of times.
/param vec A vector or array data structure of type String /param value a value of type char* that be repeated /param num The number of times a value is to be repeated
String vec;
init_string_vector(&vec, 10);
repeat_string_vector(&vec, "Hello", 4);
PRINT(vec);
[ Hello, Hello, Hello, Hello, Hello ]
free_string_vector(&vec);
Definition at line 5041 of file vector.c.
                                                               {
    int j;
    for (size_t i = 0; i < num; i++) {
        j = push_string_vector(vec, value, vec->active_length);
        if (j < 0) return -1;
    }
    return 1;
}
References String::active_length, and push_string_vector().
repeat_uchar_vector()
int repeat_uchar_vector (UChar * vec, unsigned char value, size_t num)
This function will repeat a user defined value in a vector or array data structure a user defined number of times.
/param vec A vector or array data structure of type UChar /param value a value of type char that be repeated /param num The number of times a value is to be repeated
UChar vec;
init_uchar_vector(&vec, 10);
repeat_uchar_vector(&vec, 'h', 4);
PRINT(vec);
[ H, H, H, H, H ]
free_uchar_vector(&vec);
Definition at line 5031 of file vector.c.
                                                                     {
    int j;
    for (size_t i = 0; i < num; i++) {
        j = push_uchar_vector(vec, value, vec->active_length);
        if (j < 0) return -1;
    }
    return 1;
}
References push_uchar_vector().
repeat_uint_vector()
int repeat_uint_vector (UInt * vec, unsigned int value, size_t num)
This function will repeat a user defined value in a vector or array data structure a user defined number of times.
/param vec A vector or array data structure of type UInt /param value a value of type unsigned int that be repeated /param num The number of times a value is to be repeated
UInt vec;
init_uint_vector(&vec, 10);
repeat_uint_vector(&vec, 10, 4);
PRINT(vec);
[ 10, 10, 10, 10, 10 ]
free_uint_vector(&vec);
Definition at line 4931 of file vector.c.
                                                                  {
    int j;
    for (size_t i = 0; i < num; i++) {
        j = push_uint_vector(vec, value, vec->active_length);
        if (j < 0) return -1;
    }
    return 1;
}
References push_uint_vector().
repeat_ullong_vector()
int repeat_ullong_vector (ULLInt * vec, unsigned long long int value, size_t num)
This function will repeat a user defined value in a vector or array data structure a user defined number of times.
/param vec A vector or array data structure of type ULLInt /param value a value of type unsigned long long int that be repeated /param num The number of times a value is to be repeated
ULLInt vec;
init_ullong_vector(&vec, 10);
repeat_ullong_vector(&vec, 10, 4);
PRINT(vec);
[ 10, 10, 10, 10, 10 ]
free_ullong_vector(&vec);
Definition at line 4971 of file vector.c.
                                                                                {
    int j;
    for (size_t i = 0; i < num; i++) {
        j = push_ullong_vector(vec, value, vec->active_length);
        if (j < 0) return -1;
    }
    return 1;
}
References push_ullong_vector().
repeat_ulong_vector()
int repeat_ulong_vector (ULInt * vec, unsigned long int value, size_t num)
This function will repeat a user defined value in a vector or array data structure a user defined number of times.
/param vec A vector or array data structure of type ULInt /param value a value of type unsigned long int that be repeated /param num The number of times a value is to be repeated
ULInt vec;
init_ulong_vector(&vec, 10);
repeat_ulong_vector(&vec, 10, 4);
PRINT(vec);
[ 10, 10, 10, 10, 10 ]
free_ulong_vector(&vec);
Definition at line 4951 of file vector.c.
                                                                         {
    int j;
    for (size_t i = 0; i < num; i++) {
        j = push_ulong_vector(vec, value, vec->active_length);
        if (j < 0) return -1;
    }
    return 1;
}
References push_ulong_vector().
repeat_ushort_vector()
int repeat_ushort_vector (UShort * vec, unsigned short int value, size_t num)
This function will repeat a user defined value in a vector or array data structure a user defined number of times.
/param vec A vector or array data structure of type UShort /param value a value of type unsigned short int that be repeated /param num The number of times a value is to be repeated
UShort vec;
init_ushort_vector(&vec, 10);
repeat_ushort_vector(&vec, 10, 4);
PRINT(vec);
[ 10, 10, 10, 10, 10 ]
free_ushort_vector(&vec);
Definition at line 4911 of file vector.c.
                                                                            {
    int j;
    for (size_t i = 0; i < num; i++) {
        j = push_ushort_vector(vec, value, vec->active_length);
        if (j < 0) return -1;
    }
    return 1;
}
References push_ushort_vector().
replace_bool_vector_index()
int replace_bool_vector_index (Bool * vec, bool new_value, size_t index)
This function will replace the value of a vector or array at a user specified index. If the user specifies an index that is out of bounds, the function will return -1, or 1 if successfull.
/param vec A vector or array of type Bool /param new_value The replacement value of type bool /param index The index where a value will be replaced
Bool vec;
init_bool_vector(&vec, 5);
bool a[5] = {1, 2, 3, 4};
insert_bool_vector(&vec, a, 5, 0);
replace_bool_vector_index(&vec, 10, 2);
PRINT(vec);
// >> [ 1, 2, 10, 4 ]
free_bool_vector(&vec);
Definition at line 4879 of file vector.c.
                                                                       {
    if (index > vec->active_length || index < 0) {
        fprintf(stderr, "Index out of bounds in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->array[index] = new_value;
    return 1;
}
replace_bool_vector_values()
void replace_bool_vector_values (Bool * vec, bool old_value, char new_value)
This function will replace all instances of a scalar value in an Bool struct container.
/param vec A struct container of type Bool /param old_value A bool scalar variable to be replaced /param new_value A bool scalar variable to replace old_value with
Char vec;
init_bool_vector(vec, 5);
push_bool_vector(vec, true);
push_bool_vector(vec, true);
push_bool_vector(vec, false);
push_bool_vector(vec, true);
push_bool_vector(vec, true);
replace_bool_vector_values(vec, true, false);
PRINT(vec);
//>> [ false, false, false, false, false ]
free_bool_vector(&vec);
Definition at line 1664 of file vector.c.
                                                                           {
    for (size_t i = 0; i < vec->active_length; i++) {
        if (vec->array[i] == old_value) vec->array[i] = new_value;
    }
}
replace_char_vector_index()
int replace_char_vector_index (Char * vec, char new_value, size_t index)
This function will replace the value of a vector or array at a user specified index. If the user specifies an index that is out of bounds, the function will return -1, or 1 if successfull.
/param vec A vector or array of type Char /param new_value The replacement value of type char /param index The index where a value will be replaced
Char vec;
init_char_vector(&vec, 5);
char a[5] = {'a', 'b', 'c', 'd'};
insert_char_vector(&vec, a, 5, 0);
replace_char_vector_index(&vec, 'q', 2);
PRINT(vec);
// >> [ a, b, q, d ]
free_char_vector(&vec);
Definition at line 4859 of file vector.c.
                                                                       {
    if (index > vec->active_length || index < 0) {
        fprintf(stderr, "Index out of bounds in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->array[index] = new_value;
    return 1;
}
replace_char_vector_values()
void replace_char_vector_values (Char * vec, char old_value, char new_value)
This function will replace all instances of a scalar value in an Char struct container.
/param vec A struct container of type Char /param old_value A char scalar variable to be replaced /param new_value A char scalar variable to replace old_value with
Char vec;
init_char_vector(vec, 5);
push_char_vector(vec, 1);
push_char_vector(vec, 1);
push_char_vector(vec, 2);
push_char_vector(vec, 1);
push_char_vector(vec, 3);
replace_char_vector_values(vec, 1, 5);
PRINT(vec);
//>> [ 5, 5, 2, 5, 3 ]
free_char_vector(&vec);
Definition at line 1650 of file vector.c.
                                                                           {
    for (size_t i = 0; i < vec->active_length; i++) {
        if (vec->array[i] == old_value) vec->array[i] = new_value;
    }
}
replace_double_vector_index()
int replace_double_vector_index (Dble * vec, double new_value, size_t index)
This function will replace the value of a vector or array at a user specified index. If the user specifies an index that is out of bounds, the function will return -1, or 1 if successfull.
/param vec A vector or array of type Dble /param new_value The replacement value of type unsigned double /param index The index where a value will be replaced
Dble vec;
init_double_vector(&vec, 5);
double a[5] = {1, 2, 3, 4};
insert_double_vector(&vec, a, 5, 0);
replace_double_vector_index(&vec, 10, 2);
PRINT(vec);
// >> [ 1, 2, 10, 4 ]
free_double_vector(&vec);
Definition at line 4839 of file vector.c.
                                                                           {
    if (index > vec->active_length || index < 0) {
        fprintf(stderr, "Index out of bounds in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->array[index] = new_value;
    return 1;
}
replace_double_vector_values()
void replace_double_vector_values (Dble * vec, double old_value, double new_value)
This function will replace all instances of a scalar value in an Dble struct container.
/param vec A struct container of type Dble /param old_value An double scalar variable to be replaced /param new_value An double scalar variable to replace old_value with
Dble vec;
init_double_vector(vec, 5);
push_double_vector(vec, 1);
push_double_vector(vec, 1);
push_double_vector(vec, 2);
push_double_vector(vec, 1);
push_double_vector(vec, 3);
replace_double_vector_values(vec, 1, 5);
PRINT(vec);
//>> [ 5, 5, 2, 5, 3 ]
free_double_vector(&vec);
Definition at line 1636 of file vector.c.
                                                                                 {
    for (size_t i = 0; i < vec->active_length; i++) {
        if (vec->array[i] == old_value) vec->array[i] = new_value;
    }
}
replace_float_vector_index()
int replace_float_vector_index (Flt * vec, float new_value, size_t index)
This function will replace the value of a vector or array at a user specified index. If the user specifies an index that is out of bounds, the function will return -1, or 1 if successfull.
/param vec A vector or array of type Flt /param new_value The replacement value of type float /param index The index where a value will be replaced
Flt vec;
init_float_vector(&vec, 5);
float a[5] = {1, 2, 3, 4};
insert_float_vector(&vec, a, 5, 0);
replace_float_vector_index(&vec, 10, 2);
PRINT(vec);
// >> [ 1, 2, 10, 4 ]
free_float_vector(&vec);
Definition at line 4829 of file vector.c.
                                                                        {
    if (index > vec->active_length || index < 0) {
        fprintf(stderr, "Index out of bounds in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->array[index] = new_value;
    return 1;
}
replace_float_vector_values()
void replace_float_vector_values (Flt * vec, float old_value, float new_value)
This function will replace all instances of a scalar value in an Flt struct container.
/param vec A struct container of type Flt /param old_value An float scalar variable to be replaced /param new_value An float scalar variable to replace old_value with
Flt vec;
init_float_vector(vec, 5);
push_float_vector(vec, 1);
push_float_vector(vec, 1);
push_float_vector(vec, 2);
push_float_vector(vec, 1);
push_float_vector(vec, 3);
replace_float_vector_values(vec, 1, 5);
PRINT(vec);
//>> [ 5, 5, 2, 5, 3 ]
free_float_vector(&vec);
Definition at line 1629 of file vector.c.
                                                                             {
    for (size_t i = 0; i < vec->active_length; i++) {
        if (vec->array[i] == old_value) vec->array[i] = new_value;
    }
}
replace_int_vector_index()
int replace_int_vector_index (Int * vec, int new_value, size_t index)
This function will replace the value of a vector or array at a user specified index. If the user specifies an index that is out of bounds, the function will return -1, or 1 if successfull.
/param vec A vector or array of type Int /param new_value The replacement value of type int /param index The index where a value will be replaced
Int vec;
init_int_vector(&vec, 5);
int a[5] = {1, 2, 3, 4};
insert_int_vector(&vec, a, 5, 0);
replace_int_vector_index(&vec, 10, 2);
PRINT(vec);
// >> [ 1, 2, 10, 4 ]
free_int_vector(&vec);
Definition at line 4769 of file vector.c.
                                                                    {
    if (index > vec->active_length || index < 0) {
        fprintf(stderr, "Index out of bounds in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->array[index] = new_value;
    return 1;
}
replace_int_vector_values()
void replace_int_vector_values (Int * vec, int old_value, int new_value)
This function will replace all instances of a scalar value in an Int struct container.
/param vec A struct container of type Int /param old_value An int scalar variable to be replaced /param new_value An int scalar variable to replace old_value with
Int vec;
init_int_vector(vec, 5);
push_int_vector(vec, 1);
push_int_vector(vec, 1);
push_int_vector(vec, 2);
push_int_vector(vec, 1);
push_int_vector(vec, 3);
replace_int_vector_values(vec, 1, 5);
PRINT(vec);
//>> [ 5, 5, 2, 5, 3 ]
free_int_vector(&vec);
Definition at line 1587 of file vector.c.
                                                                       {
    for (size_t i = 0; i < vec->active_length; i++) {
        if (vec->array[i] == old_value) vec->array[i] = new_value;
    }
}
replace_ldouble_vector_index()
int replace_ldouble_vector_index (LDble * vec, long double new_value, size_t index)
This function will replace the value of a vector or array at a user specified index. If the user specifies an index that is out of bounds, the function will return -1, or 1 if successfull.
/param vec A vector or array of type LDble /param new_value The replacement value of type long double /param index The index where a value will be replaced
LDble vec;
init_ldouble_vector(&vec, 5);
ldouble a[5] = {1, 2, 3, 4};
insert_ldouble_vector(&vec, a, 5, 0);
replace_ldouble_vector_index(&vec, 10, 2);
PRINT(vec);
// >> [ 1, 2, 10, 4 ]
free_ldouble_vector(&vec);
Definition at line 4849 of file vector.c.
                                                                                  {
    if (index > vec->active_length || index < 0) {
        fprintf(stderr, "Index out of bounds in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->array[index] = new_value;
    return 1;
}
replace_ldouble_vector_values()
void replace_ldouble_vector_values (LDble * vec, long double old_value, long double new_value)
This function will replace all instances of a scalar value in an LDble struct container.
/param vec A struct container of type LDble /param old_value A long double scalar variable to be replaced /param new_value A long double scalar variable to replace old_value with
LDble vec;
init_ldouble_vector(vec, 5);
push_ldouble_vector(vec, 1);
push_ldouble_vector(vec, 1);
push_ldouble_vector(vec, 2);
push_ldouble_vector(vec, 1);
push_ldouble_vector(vec, 3);
replace_ldouble_vector_values(vec, 1, 5);
PRINT(vec);
//>> [ 5, 5, 2, 5, 3 ]
free_ldouble_vector(&vec);
Definition at line 1643 of file vector.c.
                                                                                             {
    for (size_t i = 0; i < vec->active_length; i++) {
        if (vec->array[i] == old_value) vec->array[i] = new_value;
    }
}
replace_llong_vector_index()
int replace_llong_vector_index (LLInt * vec, long long int new_value, size_t index)
This function will replace the value of a vector or array at a user specified index. If the user specifies an index that is out of bounds, the function will return -1, or 1 if successfull.
/param vec A vector or array of type LLInt /param new_value The replacement value of type long long int /param index The index where a value will be replaced
LLInt vec;
init_llong_vector(&vec, 5);
long long int a[5] = {1, 2, 3, 4};
insert_llong_vector(&vec, a, 5, 0);
replace_llong_vector_index(&vec, 10, 2);
PRINT(vec);
// >> [ 1, 2, 10, 4 ]
free_llong_vector(&vec);
Definition at line 4809 of file vector.c.
                                                                                  {
    if (index > vec->active_length || index < 0) {
        fprintf(stderr, "Index out of bounds in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->array[index] = new_value;
    return 1;
}
replace_llong_vector_values()
void replace_llong_vector_values (LLInt * vec, long long int old_value, long long int new_value)
This function will replace all instances of a scalar value in an LLInt struct container.
/param vec A struct container of type LLInt /param old_value An long long int scalar variable to be replaced /param new_value An long long int scalar variable to replace old_value with
LLInt vec;
init_llong_vector(vec, 5);
push_llong_vector(vec, 1);
push_llong_vector(vec, 1);
push_llong_vector(vec, 2);
push_llong_vector(vec, 1);
push_llong_vector(vec, 3);
replace_llong_vector_values(vec, 1, 5);
PRINT(vec);
//>> [ 5, 5, 2, 5, 3 ]
free_llong_vector(&vec);
Definition at line 1615 of file vector.c.
                                                                                               {
    for (size_t i = 0; i < vec->active_length; i++) {
        if (vec->array[i] == old_value) vec->array[i] = new_value;
    }
}
replace_long_vector_index()
int replace_long_vector_index (LInt * vec, long int new_value, size_t index)
This function will replace the value of a vector or array at a user specified index. If the user specifies an index that is out of bounds, the function will return -1, or 1 if successfull.
/param vec A vector or array of type LInt /param new_value The replacement value of type long int /param index The index where a value will be replaced
LInt vec;
init_long_vector(&vec, 5);
long int a[5] = {1, 2, 3, 4};
insert_long_vector(&vec, a, 5, 0);
replace_long_vector_index(&vec, 10, 2);
PRINT(vec);
// >> [ 1, 2, 10, 4 ]
free_long_vector(&vec);
Definition at line 4789 of file vector.c.
                                                                           {
    if (index > vec->active_length || index < 0) {
        fprintf(stderr, "Index out of bounds in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->array[index] = new_value;
    return 1;
}
replace_long_vector_values()
void replace_long_vector_values (LInt * vec, long int old_value, long int new_value)
This function will replace all instances of a scalar value in an LInt struct container.
/param vec A struct container of type LInt /param old_value An long int scalar variable to be replaced /param new_value An long int scalar variable to replace old_value with
LInt vec;
init_long_vector(vec, 5);
push_long_vector(vec, 1);
push_long_vector(vec, 1);
push_long_vector(vec, 2);
push_long_vector(vec, 1);
push_long_vector(vec, 3);
replace_long_vector_values(vec, 1, 5);
PRINT(vec);
//>> [ 5, 5, 2, 5, 3 ]
free_long_vector(&vec);
Definition at line 1601 of file vector.c.
                                                                                   {
    for (size_t i = 0; i < vec->active_length; i++) {
        if (vec->array[i] == old_value) vec->array[i] = new_value;
    }
}
replace_short_vector_index()
int replace_short_vector_index (Short * vec, short int new_value, size_t index)
This function will replace the value of a vector or array at a user specified index. If the user specifies an index that is out of bounds, the function will return -1, or 1 if successfull.
/param vec A vector or array of type Short /param new_value The replacement value of type short int /param index The index where a value will be replaced
Short vec;
init_short_vector(&vec, 5);
short int a[5] = {1, 2, 3, 4};
insert_short_vector(&vec, a, 5, 0);
replace_short_vector_index(&vec, 10, 2);
PRINT(vec);
// >> [ 1, 2, 10, 4 ]
free_short_vector(&vec);
Definition at line 4749 of file vector.c.
                                                                              {
    if (index > vec->active_length || index < 0) {
        fprintf(stderr, "Index out of bounds in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->array[index] = new_value;
    return 1;
}
replace_short_vector_values()
void replace_short_vector_values (Short * vec, short int old_value, short int new_value)
This function will replace all instances of a scalar value in an Short struct container.
/param vec A struct container of type Short /param old_value An short int scalar variable to be replaced /param new_value An short int scalar variable to replace old_value with
Short vec;
init_short_vector(vec, 5);
push_short_vector(vec, 1);
push_short_vector(vec, 1);
push_short_vector(vec, 2);
push_short_vector(vec, 1);
push_short_vector(vec, 3);
replace_short_vector_values(vec, 1, 5);
PRINT(vec);
//>> [ 5, 5, 2, 5, 3 ]
free_short_vector(&vec);
Definition at line 1573 of file vector.c.
                                                                                       {
    for (size_t i = 0; i < vec->active_length; i++) {
        if (vec->array[i] == old_value) vec->array[i] = new_value;
    }
}
replace_string_vector_index()
int replace_string_vector_index (String * vec, char * new_value, size_t index)
This function will replace the value of a vector or array at a user specified index. If the user specifies an index that is out of bounds, the function will return -1, or 1 if successfull.
/param vec A vector or array of type String /param new_value The replacement value of type char* /param index The index where a value will be replaced
String vec;
init_string_vector(&vec);
push_string_vector(&vec, "One", 0);
push_string_vector(&vec, "Two", 1);
push_string_vector(&vec, "Three", 2);
push_string_vector(&vec, "Four", 3);
replace_ldouble_vector_index(&vec, "Five", 2);
PRINT(vec);
// >> [ One, Two, Five, Four ]
free_string_vector(&vec);
Definition at line 4889 of file vector.c.
                                                                            {
    if (index > vec->active_length || index < 0) {
        fprintf(stderr, "Index out of bounds in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->array[index] = new_value;
    return 1;
}
References String::active_length, and String::array.
replace_string_vector_values()
void replace_string_vector_values (String * vec, char * old_value, char * new_value)
This function will replace all instances of a string within a String vector struct
/param vec A struct container of type String /param old_value The old string value /param new_value The new string value
String vec;
init_string_vector(vec);
push_string_vector(vec, "Hello", 0);
push_string_vector(vec, "Goodbye", 1);
push_string_vector(vec, "Hello", 2);
push_string_vector(vec, "Goodbye", 3);
replace_string_vector_values(vec, "Hello", "Wrong");
PRINT(vec);
// >> [ Wrong, Goodbye, Wrong, Goodbye);
free_string_vector(&vec);
Definition at line 1671 of file vector.c.
                                                                                 {
    int cmp;
    for (size_t i = 0; i < vec->active_length; i++) {
        cmp = strcmp(vec->array[i], old_value);
        if (cmp == 0) {
            pop_string_vector_index(vec, i);
            push_string_vector(vec, new_value, i);
        }
    }
}
References String::active_length, String::array, pop_string_vector_index(), and push_string_vector().
replace_uchar_vector_index()
int replace_uchar_vector_index (UChar * vec, unsigned char new_value, size_t index)
This function will replace the value of a vector or array at a user specified index. If the user specifies an index that is out of bounds, the function will return -1, or 1 if successfull.
/param vec A vector or array of type UChar /param new_value The replacement value of type unsigned char /param index The index where a value will be replaced
UChar vec;
init_uchar_vector(&vec, 5);
unsigned char a[5] = {'a', 'b', 'c', 'd'};
insert_uchar_vector(&vec, a, 5, 0);
replace_uchar_vector_index(&vec, 'q', 2);
PRINT(vec);
// >> [ a, b, q, d ]
free_uchar_vector(&vec);
Definition at line 4869 of file vector.c.
                                                                                  {
    if (index > vec->active_length || index < 0) {
        fprintf(stderr, "Index out of bounds in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->array[index] = new_value;
    return 1;
}
replace_uchar_vector_values()
void replace_uchar_vector_values (UChar * vec, unsigned char old_value, unsigned char new_value)
This function will replace all instances of a scalar value in an Char struct container.
/param vec A struct container of type UChar /param old_value A char scalar variable to be replaced /param new_value A char scalar variable to replace old_value with
UChar vec;
init_uchar_vector(vec, 5);
push_uchar_vector(vec, 1);
push_uchar_vector(vec, 1);
push_uchar_vector(vec, 2);
push_uchar_vector(vec, 1);
push_uchar_vector(vec, 3);
replace_uchar_vector_values(vec, 1, 5);
PRINT(vec);
//>> [ 5, 5, 2, 5, 3 ]
free_uchar_vector(&vec);
Definition at line 1657 of file vector.c.
                                                                                               {
    for (size_t i = 0; i < vec->active_length; i++) {
        if (vec->array[i] == old_value) vec->array[i] = new_value;
    }
}
replace_uint_vector_index()
int replace_uint_vector_index (UInt * vec, unsigned int new_value, size_t index)
This function will replace the value of a vector or array at a user specified index. If the user specifies an index that is out of bounds, the function will return -1, or 1 if successfull.
/param vec A vector or array of type UInt /param new_value The replacement value of type unsigned int /param index The index where a value will be replaced
UInt vec;
init_uint_vector(&vec, 5);
unsigned int a[5] = {1, 2, 3, 4};
insert_uint_vector(&vec, a, 5, 0);
replace_uint_vector_index(&vec, 10, 2);
PRINT(vec);
// >> [ 1, 2, 10, 4 ]
free_uint_vector(&vec);
Definition at line 4779 of file vector.c.
                                                                               {
    if (index > vec->active_length || index < 0) {
        fprintf(stderr, "Index out of bounds in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->array[index] = new_value;
    return 1;
}
replace_uint_vector_values()
void replace_uint_vector_values (UInt * vec, unsigned int old_value, unsigned int new_value)
This function will replace all instances of a scalar value in an UInt struct container.
/param vec A struct container of type UInt /param old_value An unsigned int scalar variable to be replaced /param new_value An unsigned int scalar variable to replace old_value with
UInt vec;
init_uint_vector(vec, 5);
push_uint_vector(vec, 1);
push_uint_vector(vec, 1);
push_uint_vector(vec, 2);
push_uint_vector(vec, 1);
push_uint_vector(vec, 3);
replace_uint_vector_values(vec, 1, 5);
PRINT(vec);
//>> [ 5, 5, 2, 5, 3 ]
free_uint_vector(&vec);
Definition at line 1594 of file vector.c.
                                                                                           {
    for (size_t i = 0; i < vec->active_length; i++) {
        if (vec->array[i] == old_value) vec->array[i] = new_value;
    }
}
replace_ullong_vector_index()
int replace_ullong_vector_index (ULLInt * vec, unsigned long long int new_value, size_t index)
This function will replace the value of a vector or array at a user specified index. If the user specifies an index that is out of bounds, the function will return -1, or 1 if successfull.
/param vec A vector or array of type ULLInt /param new_value The replacement value of type unsigned long long int /param index The index where a value will be replaced
ULLInt vec;
init_ullong_vector(&vec, 5);
unsigned long long int a[5] = {1, 2, 3, 4};
insert_ullong_vector(&vec, a, 5, 0);
replace_ullong_vector_index(&vec, 10, 2);
PRINT(vec);
// >> [ 1, 2, 10, 4 ]
free_ullong_vector(&vec);
Definition at line 4819 of file vector.c.
                                                                                             {
    if (index > vec->active_length || index < 0) {
        fprintf(stderr, "Index out of bounds in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->array[index] = new_value;
    return 1;
}
replace_ullong_vector_values()
void replace_ullong_vector_values (ULLInt * vec, unsigned long long int old_value, unsigned long long int new_value)
This function will replace all instances of a scalar value in an ULLInt struct container.
/param vec A struct container of type ULLInt /param old_value An unsigned long long int scalar variable to be replaced /param new_value An unsigned long long int scalar variable to replace old_value with
ULLInt vec;
init_ullong_vector(vec, 5);
push_ullong_vector(vec, 1);
push_ullong_vector(vec, 1);
push_ullong_vector(vec, 2);
push_ullong_vector(vec, 1);
push_ullong_vector(vec, 3);
replace_ullong_vector_values(vec, 1, 5);
PRINT(vec);
//>> [ 5, 5, 2, 5, 3 ]
free_ullong_vector(&vec);
Definition at line 1622 of file vector.c.
                                                                                                                   {
    for (size_t i = 0; i < vec->active_length; i++) {
        if (vec->array[i] == old_value) vec->array[i] = new_value;
    }
}
replace_ulong_vector_index()
int replace_ulong_vector_index (ULInt * vec, unsigned long int new_value, size_t index)
This function will replace the value of a vector or array at a user specified index. If the user specifies an index that is out of bounds, the function will return -1, or 1 if successfull.
/param vec A vector or array of type ULInt /param new_value The replacement value of type unsigned long int /param index The index where a value will be replaced
ULInt vec;
init_ulong_vector(&vec, 5);
unsigned long int a[5] = {1, 2, 3, 4};
insert_ulong_vector(&vec, a, 5, 0);
replace_ulong_vector_index(&vec, 10, 2);
PRINT(vec);
// >> [ 1, 2, 10, 4 ]
free_ulong_vector(&vec);
Definition at line 4799 of file vector.c.
                                                                                      {
    if (index > vec->active_length || index < 0) {
        fprintf(stderr, "Index out of bounds in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->array[index] = new_value;
    return 1;
}
replace_ulong_vector_values()
void replace_ulong_vector_values (ULInt * vec, unsigned long int old_value, unsigned long int new_value)
This function will replace all instances of a scalar value in an ULInt struct container.
/param vec A struct container of type ULInt /param old_value An unsigned long int scalar variable to be replaced /param new_value An unsigned long int scalar variable to replace old_value with
ULInt vec;
init_ulong_vector(vec, 5);
push_ulong_vector(vec, 1);
push_ulong_vector(vec, 1);
push_ulong_vector(vec, 2);
push_ulong_vector(vec, 1);
push_ulong_vector(vec, 3);
replace_ulong_vector_values(vec, 1, 5);
PRINT(vec);
//>> [ 5, 5, 2, 5, 3 ]
free_ulong_vector(&vec);
Definition at line 1608 of file vector.c.
                                                                                                       {
    for (size_t i = 0; i < vec->active_length; i++) {
        if (vec->array[i] == old_value) vec->array[i] = new_value;
    }
}
replace_ushort_vector_index()
int replace_ushort_vector_index (UShort * vec, unsigned short int new_value, size_t index)
This function will replace the value of a vector or array at a user specified index. If the user specifies an index that is out of bounds, the function will return -1, or 1 if successfull.
/param vec A vector or array of type UShort /param new_value The replacement value of type unsigned short int /param index The index where a value will be replaced
UShort vec;
init_ushort_vector(&vec, 5);
unsigned short int a[5] = {1, 2, 3, 4};
insert_ushort_vector(&vec, a, 5, 0);
replace_ushort_vector_index(&vec, 10, 2);
PRINT(vec);
// >> [ 1, 2, 10, 4 ]
free_ushort_vector(&vec);
Definition at line 4759 of file vector.c.
                                                                                         {
    if (index > vec->active_length || index < 0) {
        fprintf(stderr, "Index out of bounds in file %s on line %d\n", __FILE__, __LINE__);
        return -1;
    }
    vec->array[index] = new_value;
    return 1;
}
replace_ushort_vector_values()
void replace_ushort_vector_values (UShort * vec, unsigned short int old_value, unsigned short int new_value)
This function will replace all instances of a scalar value in an UShort struct container.
/param vec A struct container of type UShort /param old_value An unsigned short int scalar variable to be replaced /param new_value An unsigned short int scalar variable to replace old_value with
UShort vec;
init_ushort_vector(vec, 5);
push_ushort_vector(vec, 1);
push_ushort_vector(vec, 1);
push_ushort_vector(vec, 2);
push_ushort_vector(vec, 1);
push_ushort_vector(vec, 3);
replace_ushort_vector_values(vec, 1, 5);
PRINT(vec);
//>> [ 5, 5, 2, 5, 3 ]
free_ushort_vector(&vec);
Definition at line 1580 of file vector.c.
                                                                                                           {
    for (size_t i = 0; i < vec->active_length; i++) {
        if (vec->array[i] == old_value) vec->array[i] = new_value;
    }
}
reverse_bool_vector()
void reverse_bool_vector (Bool * vec)
This function will reverse the order of the array in a struct of type Bool.
/param vec A vector struct container of type Bool
Bool vec;
init_bool_vector(vec, 4);
bool a[4] = {true, true, false, false};
insert_bool_vector(&vec, a, 4, 0);
reverse_bool_vector(&vec);
PRINT(vec);
[ 4, 3, 2, 1 ]
free_bool_vector(&vec);
Definition at line 2262 of file vector.c.
                                    {
    size_t start = 0;
    size_t end = vec->active_length - 1;
    while (start < end) {
        bool *a = &vec->array[start];
        bool *b = &vec->array[end];
        bool temp= *a;
        *a = *b;
        *b = temp;
        ++start;
        --end;
    }
}
reverse_char_vector()
void reverse_char_vector (Char * vec)
This function will reverse the order of the array in a struct of type Char.
/param vec A vector struct container of type Char
Char vec;
init_char_vector(vec, 4);
char a[4] = {1, 2, 3, 4};
insert_char_vector(&vec, a, 4, 0);
reverse_char_vector(&vec);
PRINT(vec);
[ 4, 3, 2, 1 ]
free_char_vector(&vec);
Definition at line 2232 of file vector.c.
                                    {
    size_t start = 0;
    size_t end = vec->active_length - 1;
    while (start < end) {
        char *a = &vec->array[start];
        char *b = &vec->array[end];
        char temp= *a;
        *a = *b;
        *b = temp;
        ++start;
        --end;
    }
}
reverse_double_vector()
void reverse_double_vector (Dble * vec)
This function will reverse the order of the array in a struct of type Dble.
/param vec A vector struct container of type Dble
Dble vec;
init_double_vector(vec, 4);
double a[4] = {1, 2, 3, 4};
insert_double_vector(vec, a, 4, 0);
reverse_double_vector(vec);
PRINT(vec);
[ 4, 3, 2, 1 ]
free_double_vector(&vec);
Definition at line 2202 of file vector.c.
                                      {
    size_t start = 0;
    size_t end = vec->active_length - 1;
    while (start < end) {
        double *a = &vec->array[start];
        double *b = &vec->array[end];
        double temp= *a;
        *a = *b;
        *b = temp;
        ++start;
        --end;
    }
}
reverse_float_vector()
void reverse_float_vector (Flt * vec)
This function will reverse the order of the array in a struct of type Flt.
/param vec A vector struct container of type Flt
Flt vec;
init_float_vector(vec, 4);
float a[4] = {1, 2, 3, 4};
insert_float_vector(vec, a, 4, 0);
reverse_float_vector(vec);
PRINT(vec);
[ 4, 3, 2, 1 ]
free_float_vector(&vec);
Definition at line 2187 of file vector.c.
                                    {
    size_t start = 0;
    size_t end = vec->active_length - 1;
    while (start < end) {
        float *a = &vec->array[start];
        float *b = &vec->array[end];
        float temp= *a;
        *a = *b;
        *b = temp;
        ++start;
        --end;
    }
}
reverse_int_vector()
void reverse_int_vector (Int * vec)
This function will reverse the order of the array in a struct of type Int.
/param vec A vector struct container of type Int
Int vec;
init_int_vector(vec, 4);
int a[4] = {1, 2, 3, 4};
insert_int_vector(vec, a, 4, 0);
reverse_int_vector(vec);
PRINT(vec);
[ 4, 3, 2, 1 ]
free_int_vector(&vec);
Definition at line 2095 of file vector.c.
                                  {
    size_t start = 0;
    size_t end = vec->active_length - 1;
    while (start < end) {
        int *a = &vec->array[start];
        int *b = &vec->array[end];
        int temp= *a;
        *a = *b;
        *b = temp;
        ++start;
        --end;
    }
}
reverse_ldouble_vector()
void reverse_ldouble_vector (LDble * vec)
This function will reverse the order of the array in a struct of type LDble.
/param vec A vector struct container of type LDble
LDble vec;
init_ldouble_vector(vec, 4);
long double a[4] = {1, 2, 3, 4};
insert_ldouble_vector(vec, a, 4, 0);
reverse_ldouble_vector(vec);
PRINT(vec);
[ 4, 3, 2, 1 ]
free_ldouble_vector(&vec);
Definition at line 2217 of file vector.c.
                                        {
    size_t start = 0;
    size_t end = vec->active_length - 1;
    while (start < end) {
        long double *a = &vec->array[start];
        long double *b = &vec->array[end];
        long double temp= *a;
        *a = *b;
        *b = temp;
        ++start;
        --end;
    }
}
reverse_llong_vector()
void reverse_llong_vector (LLInt * vec)
This function will reverse the order of the array in a struct of type LLInt.
/param vec A vector struct container of type LLInt
LLInt vec;
init_llong_vector(vec, 4);
unsigned long long int a[4] = {1, 2, 3, 4};
insert_llong_vector(vec, a, 4, 0);
reverse_llong_vector(vec);
PRINT(vec);
[ 4, 3, 2, 1 ]
free_llong_vector(&vec);
Definition at line 2157 of file vector.c.
                                      {
    size_t start = 0;
    size_t end = vec->active_length - 1;
    while (start < end) {
        long long int *a = &vec->array[start];
        long long int *b = &vec->array[end];
        long long int temp= *a;
        *a = *b;
        *b = temp;
        ++start;
        --end;
    }
}
reverse_long_vector()
void reverse_long_vector (LInt * vec)
This function will reverse the order of the array in a struct of type LInt.
/param vec A vector struct container of type LInt
LInt vec;
init_long_vector(vec, 4);
long int a[4] = {1, 2, 3, 4};
insert_long_vector(vec, a, 4, 0);
reverse_long_vector(vec);
PRINT(vec);
[ 4, 3, 2, 1 ]
free_long_vector(&vec);
Definition at line 2127 of file vector.c.
                                    {
    size_t start = 0;
    size_t end = vec->active_length - 1;
    while (start < end) {
        long int *a = &vec->array[start];
        long int *b = &vec->array[end];
        long int temp= *a;
        *a = *b;
        *b = temp;
        ++start;
        --end;
    }
}
reverse_short_vector()
void reverse_short_vector (Short * vec)
This function will reverse the order of the array in a struct of type Short.
/param vec A vector struct container of type Short
Short vec;
init_short_vector(vec, 4);
short a[4] = {1, 2, 3, 4};
insert_short_vector(vec, a, 4, 0);
reverse_short_vector(vec);
PRINT(vec);
[ 4, 3, 2, 1 ]
free_short_vector(&vec);
Definition at line 2065 of file vector.c.
                                      {
    size_t start = 0;
    size_t end = vec->active_length - 1;
    while (start < end) {
        short int *a = &vec->array[start];
        short int *b = &vec->array[end];
        short int temp= *a;
        *a = *b;
        *b = temp;
        ++start;
        --end;
    }
}
reverse_string_vector()
void reverse_string_vector (String * vec)
This function will reverse the order of the array in a struct of type String.
/param vec A vector struct container of type String
String vec;
init_string_vector(&vec);
push_string_vec(&vec, "One", vec.active_length)
push_string_vec(&vec, "Two", vec.active_length)
push_string_vec(&vec, "Three", vec.active_length)
push_string_vec(&vec, "Four", vec.active_length)
reverse_string_vector(&vec);
PRINT(vec);
[ Four, Three, Two, One ]
free_string_vector(&vec);
Definition at line 2277 of file vector.c.
                                        {
    size_t start = 0;
    size_t end = vec->active_length - 1;
    while (start < end) {
        push_string_vector(vec, vec->array[end], start);
        push_string_vector(vec, vec->array[start+1], end+1);
        pop_string_vector_index(vec, start+1);
        pop_string_vector_index(vec, end+1);
        ++start;
        --end;
    }
}
References String::active_length, String::array, pop_string_vector_index(), and push_string_vector().
reverse_uchar_vector()
void reverse_uchar_vector (UChar * vec)
This function will reverse the order of the array in a struct of type UChar.
/param vec A vector struct container of type Char
UChar vec;
init_uchar_vector(vec, 4);
unsigned char a[4] = {1, 2, 3, 4};
insert_uchar_vector(&vec, a, 4, 0);
reverse_uchar_vector(&vec);
PRINT(vec);
[ 4, 3, 2, 1 ]
free_uchar_vector(&vec);
Definition at line 2247 of file vector.c.
                                      {
    size_t start = 0;
    size_t end = vec->active_length - 1;
    while (start < end) {
        unsigned char *a = &vec->array[start];
        unsigned char *b = &vec->array[end];
        unsigned char temp= *a;
        *a = *b;
        *b = temp;
        ++start;
        --end;
    }
}
reverse_uint_vector()
void reverse_uint_vector (UInt * vec)
This function will reverse the order of the array in a struct of type UInt.
/param vec A vector struct container of type UInt
UInt vec;
init_uint_vector(vec, 4);
uint a[4] = {1, 2, 3, 4};
insert_uint_vector(vec, a, 4, 0);
reverse_uint_vector(vec);
PRINT(vec);
[ 4, 3, 2, 1 ]
free_uint_vector(&vec);
Definition at line 2110 of file vector.c.
                                    {
    size_t start = 0;
    size_t end = vec->active_length - 1;
    //unsigned int *a = &vec->array[start];
    //unsigned int *b = &vec->array[end];
    while (start < end) {
        unsigned int *a = &vec->array[start];
        unsigned int *b = &vec->array[end];
        unsigned int temp= *a;
        *a = *b;
        *b = temp;
        ++start;
        --end;
    }
}
reverse_ullong_vector()
void reverse_ullong_vector (ULLInt * vec)
This function will reverse the order of the array in a struct of type ULLInt.
/param vec A vector struct container of type ULLInt
LLInt vec;
init_llong_vector(vec, 4);
unsigned long long int a[4] = {1, 2, 3, 4};
insert_llong_vector(vec, a, 4, 0);
reverse_llong_vector(vec);
PRINT(vec);
[ 4, 3, 2, 1 ]
free_ullong_vector(&vec);
Definition at line 2172 of file vector.c.
                                        {
    size_t start = 0;
    size_t end = vec->active_length - 1;
    while (start < end) {
        unsigned long long int *a = &vec->array[start];
        unsigned long long int *b = &vec->array[end];
        unsigned long long int temp= *a;
        *a = *b;
        *b = temp;
        ++start;
        --end;
    }
}
reverse_ulong_vector()
void reverse_ulong_vector (ULInt * vec)
This function will reverse the order of the array in a struct of type ULInt.
/param vec A vector struct container of type ULInt
ULInt vec;
init_ulong_vector(vec, 4);
unsigned long int a[4] = {1, 2, 3, 4};
insert_ulong_vector(vec, a, 4, 0);
reverse_ulong_vector(vec);
PRINT(vec);
[ 4, 3, 2, 1 ]
free_ulong_vector(&vec);
Definition at line 2142 of file vector.c.
                                      {
    size_t start = 0;
    size_t end = vec->active_length - 1;
    while (start < end) {
        unsigned long int *a = &vec->array[start];
        unsigned long int *b = &vec->array[end];
        unsigned long int temp= *a;
        *a = *b;
        *b = temp;
        ++start;
        --end;
    }
}
reverse_ushort_vector()
void reverse_ushort_vector (UShort * vec)
This function will reverse the order of the array in a struct of type UShort.
/param A vector struct container of type UShort
UShort vec;
init_ushort_vector(vec, 4);
ushort a[4] = {1, 2, 3, 4};
insert_ushort_vector(vec, a, 4, 0);
reverse_ushort_vector(vec);
PRINT(vec);
[ 4, 3, 2, 1 ]
free_ushort_vector(&vec);
Definition at line 2080 of file vector.c.
                                        {
    size_t start = 0;
    size_t end = vec->active_length - 1;
    while (start < end) {
        unsigned short int *a = &vec->array[start];
        unsigned short int *b = &vec->array[end];
        unsigned short int temp= *a;
        *a = *b;
        *b = temp;
        ++start;
        --end;
    }
}
short_vector_data()
short short_vector_data (Short * vec, size_t index)
This function will retireve the data from a user specified index in a vector or array of type Short
/param vec A linked list struct of type Short /param index The index from where data will be retrieved /return dat An unsigned bool data point
Short vec;
init_short_vector(&vec);
short int a[5] = {1, 2, 3, 4, 5};
insert_short_vector(&vec, a, 5, 0);
PRINT(short_vector_data(&vec, 2));
// >> 3
free_short_vector(&vec);
Definition at line 4419 of file vector.c.
{ return vec->array[index]; }
sort_bool_vector()
void sort_bool_vector (Bool * vec, size_t low, size_t high, sort_order order)
This function will sort a vector data structure of type Bool in forward or reverse order
/param vec A vector data structure of type Bool /param low The lowest indice for partitioning, recommended to be 0 /param high The highest indice for sorting, recommended to be the last index in the data structure /param order FORWARD for a forward sort, REVERSE for a reverse sort
Bool vec;
init_bool_vector(vec, 5);
bool a[5] = {true, false, true, false, true};
insert_bool_vector(&vec, a, 5, 0);
sort_bool_vector(&vec, 0, 5, FORWARD);
PRINT(vec);
// >> [ true, true, true, false, false ]
sort_bool_vector(&vec, 0, 5, REVERSE);
PRINT(vec);
// >> [ false, false, true, true, true ]
free_bool_vector(&vec);
FREE(vec);
Definition at line 2803 of file vector.c.
                                                                            {
    if (low < high)
    {
        size_t pivot = partition_bool_vec(vec->array, low, high, order);
        sort_bool_vector(vec, low, pivot - 1, order);
        sort_bool_vector(vec, pivot + 1, high, order);
    }
}
References partition_bool_vec(), and sort_bool_vector().
Referenced by sort_bool_vector().
sort_char_vector()
void sort_char_vector (Char * vec, size_t low, size_t high, sort_order order)
This function will sort a vector data structure of type Char in forward or reverse order
/param vec A vector data structure of type Char /param low The lowest indice for partitioning, recommended to be 0 /param high The highest indice for sorting, recommended to be the last index in the data structure /param order FORWARD for a forward sort, REVERSE for a reverse sort
Char vec;
init_char_vector(vec, 5);
char a[5] = {'e', 'b', 'a', 'c', 'e'};
insert_char_vector(&vec, a, 5, 0);
sort_char_vector(&vec, 0, 5, FORWARD);
PRINT(vec);
// >> [ a, b, c, d, e ]
sort_ldouble_vector(&vec, 0, 5, REVERSE);
PRINT(vec);
// >> [ e, d, c, b, a ]
free_char_vector(&vec);
FREE(vec);
Definition at line 2763 of file vector.c.
                                                                            {
    if (low < high)
    {
        size_t pivot = partition_char_vec(vec->array, low, high, order);
        sort_char_vector(vec, low, pivot - 1, order);
        sort_char_vector(vec, pivot + 1, high, order);
    }
}
References partition_char_vec(), and sort_char_vector().
Referenced by sort_char_vector().
sort_double_vector()
void sort_double_vector (Dble * vec, size_t low, size_t high, sort_order order)
This function will sort a vector data structure of type Dble in forward or reverse order
/param vec A vector data structure of type Dble /param low The lowest indice for partitioning, recommended to be 0 /param high The highest indice for sorting, recommended to be the last index in the data structure /param order FORWARD for a forward sort, REVERSE for a reverse sort
Dble vec;
init_double_vector(vec, 5);
double a[5] = {4., 2., 1., 3., 5.};
insert_double_vector(&vec, a, 5, 0);
sort_double_vector(&vec, 0, 5, FORWARD);
PRINT(vec);
// >> [ 1., 2., 3., 4., 5. ]
sort_double_vector(&vec, 0, 5, REVERSE);
PRINT(vec);
// >> [ 5., 4., 3., 2., 1. ]
free_double_vector(&vec);
Definition at line 2683 of file vector.c.
                                                                              {
    if (low < high)
    {
        size_t pivot = partition_double_vec(vec->array, low, high, order);
        sort_double_vector(vec, low, pivot - 1, order);
        sort_double_vector(vec, pivot + 1, high, order);
    }
}
References partition_double_vec(), and sort_double_vector().
Referenced by sort_double_vector().
sort_float_vector()
void sort_float_vector (Flt * vec, size_t low, size_t high, sort_order order)
This function will sort a vector data structure of type Flt in forward or reverse order
/param vec A vector data structure of type Flt /param low The lowest indice for partitioning, recommended to be 0 /param high The highest indice for sorting, recommended to be the last index in the data structure /param order FORWARD for a forward sort, REVERSE for a reverse sort
Flt vec;
init_float_vector(vec, 5);
float a[5] = {4., 2., 1., 3., 5.};
insert_float_vector(&vec, a, 5, 0);
sort_float_vector(&vec, 0, 5, FORWARD);
PRINT(vec);
// >> [ 1., 2., 3., 4., 5. ]
sort_float_vector(&vec, 0, 5, REVERSE);
PRINT(vec);
// >> [ 5., 4., 3., 2., 1. ]
free_float_vector(&vec);
Definition at line 2643 of file vector.c.
                                                                            {
    if (low < high)
    {
        size_t pivot = partition_float_vec(vec->array, low, high, order);
        sort_float_vector(vec, low, pivot - 1, order);
        sort_float_vector(vec, pivot + 1, high, order);
    }
}
References partition_float_vec(), and sort_float_vector().
Referenced by sort_float_vector().
sort_int_vector()
void sort_int_vector (Int * vec, size_t low, size_t high, sort_order order)
This function will sort a vector data structure of type Int in forward or reverse order
/param vec A vector data structure of type Int /param low The lowest indice for partitioning, recommended to be 0 /param high The highest indice for sorting, recommended to be the last index in the data structure /param order FORWARD for a forward sort, REVERSE for a reverse sort
Int vec;
init_int_vector(vec, 5);
int a[5] = {4, 2, 1, 3, 5};
insert_int_vector(&vec, a, 5, 0);
sort_int_vector(&vec, 0, 5, FORWARD);
PRINT(vec);
// >> [ 1, 2, 3, 4, 5 ]
sort_int_vector(&vec, 0, 5, REVERSE);
PRINT(vec);
// >> [ 5, 4, 3, 2, 1 ]
free_int_vector(&vec);
Definition at line 2403 of file vector.c.
                                                                          {
    if (low < high)
    {
        size_t pivot = partition_int_vec(vec->array, low, high, order);
        sort_int_vector(vec, low, pivot - 1, order);
        sort_int_vector(vec, pivot + 1, high, order);
    }
}
References partition_int_vec(), and sort_int_vector().
Referenced by sort_int_vector().
sort_ldouble_vector()
void sort_ldouble_vector (LDble * vec, size_t low, size_t high, sort_order order)
This function will sort a vector data structure of type LDble in forward or reverse order
/param vec A vector data structure of type LDble /param low The lowest indice for partitioning, recommended to be 0 /param high The highest indice for sorting, recommended to be the last index in the data structure /param order FORWARD for a forward sort, REVERSE for a reverse sort
LDble vec;
init_ldouble_vector(vec, 5);
long double a[5] = {4., 2., 1., 3., 5.};
insert_ldouble_vector(&vec, a, 5, 0);
sort_ldouble_vector(&vec, 0, 5, FORWARD);
PRINT(vec);
// >> [ 1., 2., 3., 4., 5. ]
sort_ldouble_vector(&vec, 0, 5, REVERSE);
PRINT(vec);
// >> [ 5., 4., 3., 2., 1. ]
free_ldouble_vector(&vec);
Definition at line 2723 of file vector.c.
                                                                                {
    if (low < high)
    {
        size_t pivot = partition_ldouble_vec(vec->array, low, high, order);
        sort_ldouble_vector(vec, low, pivot - 1, order);
        sort_ldouble_vector(vec, pivot + 1, high, order);
    }
}
References partition_ldouble_vec(), and sort_ldouble_vector().
Referenced by sort_ldouble_vector().
sort_llong_vector()
void sort_llong_vector (LLInt * vec, size_t low, size_t high, sort_order order)
This function will sort a vector data structure of type LLInt in forward or reverse order
/param vec A vector data structure of type LLInt /param low The lowest indice for partitioning, recommended to be 0 /param high The highest indice for sorting, recommended to be the last index in the data structure /param order FORWARD for a forward sort, REVERSE for a reverse sort
LLInt vec;
init_llong_vector(vec, 5);
long long int a[5] = {4, 2, 1, 3, 5};
insert_llong_vector(&vec, a, 5, 0);
sort_llong_vector(&vec, 0, 5, FORWARD);
PRINT(vec);
// >> [ 1, 2, 3, 4, 5 ]
sort_llong_vector(&vec, 0, 5, REVERSE);
PRINT(vec);
// >> [ 5, 4, 3, 2, 1 ]
free_llong_vector(&vec);
Definition at line 2563 of file vector.c.
                                                                              {
    if (low < high)
    {
        size_t pivot = partition_llong_vec(vec->array, low, high, order);
        sort_llong_vector(vec, low, pivot - 1, order);
        sort_llong_vector(vec, pivot + 1, high, order);
    }
}
References partition_llong_vec(), and sort_llong_vector().
Referenced by sort_llong_vector().
sort_long_vector()
void sort_long_vector (LInt * vec, size_t low, size_t high, sort_order order)
This function will sort a vector data structure of type LInt in forward or reverse order
/param vec A vector data structure of type LInt /param low The lowest indice for partitioning, recommended to be 0 /param high The highest indice for sorting, recommended to be the last index in the data structure /param order FORWARD for a forward sort, REVERSE for a reverse sort
LInt vec;
init_long_vector(vec, 5);
long int a[5] = {4, 2, 1, 3, 5};
insert_long_vector(&vec, a, 5, 0);
sort_long_vector(&vec, 0, 5, FORWARD);
PRINT(vec);
// >> [ 1, 2, 3, 4, 5 ]
sort_long_vector(&vec, 0, 5, REVERSE);
PRINT(vec);
// >> [ 5, 4, 3, 2, 1 ]
free_long_vector(&vec);
Definition at line 2483 of file vector.c.
                                                                            {
    if (low < high)
    {
        size_t pivot = partition_long_vec(vec->array, low, high, order);
        sort_long_vector(vec, low, pivot - 1, order);
        sort_long_vector(vec, pivot + 1, high, order);
    }
}
References partition_long_vec(), and sort_long_vector().
Referenced by sort_long_vector().
sort_short_vector()
void sort_short_vector (Short * vec, size_t low, size_t high, sort_order order)
This function will sort a vector data structure of type Short in forward or reverse order
/param vec A vector data structure of type Short /param low The lowest indice for partitioning, recommended to be 0 /param high The highest indice for sorting, recommended to be the last index in the data structure /param order FORWARD for a forward sort, REVERSE for a reverse sort
Short vec;
init_short_vector(vec, 5);
short int a[5] = {4, 2, 1, 3, 5};
insert_short_vector(&vec, a, 5, 0);
sort_short_vector(&vec, 0, 5, FORWARD);
PRINT(vec);
// >> [ 1, 2, 3, 4, 5 ]
sort_short_vector(&vec, 0, 5, REVERSE);
PRINT(vec);
// >> [ 5, 4, 3, 2, 1 ]
free_short_vector(&vec);
Definition at line 2323 of file vector.c.
                                                                              {
    if (low < high)
    {
        size_t pivot = partition_short_vec(vec->array, low, high, order);
        sort_short_vector(vec, low, pivot - 1, order);
        sort_short_vector(vec, pivot + 1, high, order);
    }
}
References partition_short_vec(), and sort_short_vector().
Referenced by sort_short_vector().
sort_string_vector()
void sort_string_vector (String * vec, size_t low, size_t high, sort_order order)
This function will sort a vector structure of type String in forward or reverse order
/param vec A vector data structure of type String /param low the lowest indice for parittioning, recommended to be 0 /param high The highest indice for sorting, recommended to be the last index /param order FORWARD for a forward sort, REVERSE for a reverse sort
String vec;
init_string_vector(vec);
push_string_vector(&vec, "Xylaphone", 0);
push_string_vector(&vec, "Apple", 1);
push_string_vector(&vec, "Cucumber", 2);
push_string_vector(&vec, "Banana", 3);
sort_string_vector(&vec, 0, vec.active_length, FORWARD);
PRINT(vec);
[ Apple, Banana, Cucumber, Xylaphone ]
free_string_vector(&vec);
Definition at line 2867 of file vector.c.
                                                                                {
    if (order == FORWARD)
        qsort(vec->array, vec->active_length, sizeof(const char*), forward_comparator);
    else
        qsort(vec->array, vec->active_length, sizeof(const char*), reverse_comparator);
}
References String::active_length, String::array, FORWARD, forward_comparator(), and reverse_comparator().
sort_uchar_vector()
void sort_uchar_vector (UChar * vec, size_t low, size_t high, sort_order order)
This function will sort a vector data structure of type UChar in forward or reverse order
/param vec A vector data structure of type UChar /param low The lowest indice for partitioning, recommended to be 0 /param high The highest indice for sorting, recommended to be the last index in the data structure /param order FORWARD for a forward sort, REVERSE for a reverse sort
UChar vec;
init_uchar_vector(vec, 5);
unsigned char a[5] = {'e', 'b', 'a', 'c', 'e'};
insert_uchar_vector(&vec, a, 5, 0);
sort_uchar_vector(&vec, 0, 5, FORWARD);
PRINT(vec);
// >> [ a, b, c, d, e ]
sort_uchar_vector(&vec, 0, 5, REVERSE);
PRINT(vec);
// >> [ e, d, c, b, a ]
free_uchar_vector(&vec);
FREE(vec);
Definition at line 2843 of file vector.c.
                                                                              {
    if (low < high)
    {
        size_t pivot = partition_uchar_vec(vec->array, low, high, order);
        sort_uchar_vector(vec, low, pivot - 1, order);
        sort_uchar_vector(vec, pivot + 1, high, order);
    }
}
References partition_uchar_vec(), and sort_uchar_vector().
Referenced by sort_uchar_vector().
sort_uint_vector()
void sort_uint_vector (UInt * vec, size_t low, size_t high, sort_order order)
This function will sort a vector data structure of type UInt in forward or reverse order
/param vec A vector data structure of type UInt /param low The lowest indice for partitioning, recommended to be 0 /param high The highest indice for sorting, recommended to be the last index in the data structure /param order FORWARD for a forward sort, REVERSE for a reverse sort
UInt vec;
init_uint_vector(vec, 5);
unsigned int a[5] = {4, 2, 1, 3, 5};
insert_uint_vector(&vec, a, 5, 0);
sort_uint_vector(&vec, 0, 5, FORWARD);
PRINT(vec);
// >> [ 1, 2, 3, 4, 5 ]
sort_uint_vector(&vec, 0, 5, REVERSE);
PRINT(vec);
// >> [ 5, 4, 3, 2, 1 ]
free_uint_vector(&vec);
Definition at line 2443 of file vector.c.
                                                                            {
    if (low < high)
    {
        size_t pivot = partition_uint_vec(vec->array, low, high, order);
        sort_uint_vector(vec, low, pivot - 1, order);
        sort_uint_vector(vec, pivot + 1, high, order);
    }
}
References partition_uint_vec(), and sort_uint_vector().
Referenced by sort_uint_vector().
sort_ullong_vector()
void sort_ullong_vector (ULLInt * vec, size_t low, size_t high, sort_order order)
This function will sort a vector data structure of type ULLInt in forward or reverse order
/param vec A vector data structure of type ULLInt /param low The lowest indice for partitioning, recommended to be 0 /param high The highest indice for sorting, recommended to be the last index in the data structure /param order FORWARD for a forward sort, REVERSE for a reverse sort
ULLInt vec;
init_ullong_vector(vec, 5);
unsigned long long int a[5] = {4, 2, 1, 3, 5};
insert_ullong_vector(&vec, a, 5, 0);
sort_ullong_vector(&vec, 0, 5, FORWARD);
PRINT(vec);
// >> [ 1, 2, 3, 4, 5 ]
sort_ullong_vector(&vec, 0, 5, REVERSE);
PRINT(vec);
// >> [ 5, 4, 3, 2, 1 ]
free_ullong_vector(&vec);
Definition at line 2603 of file vector.c.
                                                                                {
    if (low < high)
    {
        size_t pivot = partition_ullong_vec(vec->array, low, high, order);
        sort_ullong_vector(vec, low, pivot - 1, order);
        sort_ullong_vector(vec, pivot + 1, high, order);
    }
}
References partition_ullong_vec(), and sort_ullong_vector().
Referenced by sort_ullong_vector().
sort_ulong_vector()
void sort_ulong_vector (ULInt * vec, size_t low, size_t high, sort_order order)
This function will sort a vector data structure of type ULInt in forward or reverse order
/param vec A vector data structure of type ULInt /param low The lowest indice for partitioning, recommended to be 0 /param high The highest indice for sorting, recommended to be the last index in the data structure /param order FORWARD for a forward sort, REVERSE for a reverse sort
ULInt vec;
init_ulong_vector(vec, 5);
unsigned long int a[5] = {4, 2, 1, 3, 5};
insert_ulong_vector(&vec, a, 5, 0);
sort_ulong_vector(&vec, 0, 5, FORWARD);
PRINT(vec);
// >> [ 1, 2, 3, 4, 5 ]
sort_ulong_vector(&vec, 0, 5, REVERSE);
PRINT(vec);
// >> [ 5, 4, 3, 2, 1 ]
free_ulong_vector(&vec);
Definition at line 2523 of file vector.c.
                                                                              {
    if (low < high)
    {
        size_t pivot = partition_ulong_vec(vec->array, low, high, order);
        sort_ulong_vector(vec, low, pivot - 1, order);
        sort_ulong_vector(vec, pivot + 1, high, order);
    }
}
References partition_ulong_vec(), and sort_ulong_vector().
Referenced by sort_ulong_vector().
sort_ushort_vector()
void sort_ushort_vector (UShort * vec, size_t low, size_t high, sort_order order)
This function will sort a vector data structure of type UShort in forward or reverse order
/param vec A vector data structure of type UShort /param low The lowest indice for partitioning, recommended to be 0 /param high The highest indice for sorting, recommended to be the last index in the data structure /param order FORWARD for a forward sort, REVERSE for a reverse sort
UShort vec;
init_ushort_vector(vec, 5);
unsigned short int a[5] = {4, 2, 1, 3, 5};
insert_ushort_vector(&vec, a, 5, 0);
sort_ushort_vector(&vec, 0, 5, FORWARD);
PRINT(vec);
// >> [ 1, 2, 3, 4, 5 ]
sort_ushort_vector(&vec, 0, 5, REVERSE);
PRINT(vec);
// >> [ 5, 4, 3, 2, 1 ]
free_ushort_vector(&vec);
Definition at line 2363 of file vector.c.
                                                                                {
    if (low < high)
    {
        size_t pivot = partition_ushort_vec(vec->array, low, high, order);
        sort_ushort_vector(vec, low, pivot - 1, order);
        sort_ushort_vector(vec, pivot + 1, high, order);
    }
}
References partition_ushort_vec(), and sort_ushort_vector().
Referenced by sort_ushort_vector().
stdev_char_vector()
char stdev_char_vector (Char * vec)
This function wil calculate the standard deviation for the values in a vector container.
/param vec A vector data structure of type Char
Char vec;
init_char_vector(&vec, 10);
char a[10] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
insert_char_vector(&vec, a, 10, 0);
char stdev = stdev_char_vector(&vec);
PRINT(stdev);
// >> 3.2076
free_char_vector(&vec);
Definition at line 3246 of file vector.c.
                                  {
    char average = average_char_vector(vec);
    char var = 0.0;
    char value;
    for (size_t i = 0; i < vec->active_length; i++) {
        value = (float)vec->array[i];
        var += ((value - average) * (value - average));
    }
    char interm = (1.0f / ((float)vec->active_length - 1.0f)) * var;
    char number = interm;
    char start = 0.0f, end = number;
    char mid;
    // To store the answer
    char ans = 0.;
    // To find integral part of square
    // root of number
    while (start <= end) {
        // Find mid
        mid = (start + end) / 2;
        // If number is perfect square
        // then break
        if (mid * mid == number) {
            ans = mid;
            break;
        }
        // Increment start if integral
        // part lies on right side
        // of the mid
        if (mid * mid < number) {
          //first start value should be added to answer
            ans=start;
          //then start should be changed
            start = mid + 1.f;
        }
        // Decrement end if integral part
        // lies on the left side of the mid
        else {
            end = mid - 1.f;
        }
    }
    // To find the fractional part
    // of square root upto 5 decimal
    float increment = 0.1f;
    for (int i = 0; i < 5; i++) {
        while (ans * ans <= number) {
            ans += increment;
        }
        // Loop terminates,
        // when ans * ans > number
        ans = ans - increment;
        increment = increment / 10;
    }
    return ans;
}
References average_char_vector().
stdev_double_vector()
double stdev_double_vector (Dble * vec)
This function wil calculate the standard deviation for the values in a vector container.
/param vec A vector data structure of type Dble
Dble vec;
init_double_vector(&vec, 10);
double a[10] = {1., 2., 3., 4., 5., 6., 7., 8., 9., 10.};
insert_double_vector(&vec, a, 10, 0);
double stdev = stdev_double_vector(&vec);
PRINT(stdev);
// >> 3.2076
free_double_vector(&vec);
Definition at line 3884 of file vector.c.
                                      {
    double average = average_double_vector(vec);
    double var = 0.0;
    double value;
    for (size_t i = 0; i < vec->active_length; i++) {
        value = (double)vec->array[i];
        var += ((value - average) * (value - average));
    }
    double interm = (1.0 / ((double)vec->active_length - 1.0)) * var;
    double number = interm;
    double start = 0.0, end = number;
    double mid;
    // To store the answer
    double ans = 0.;
    // To find integral part of square
    // root of number
    while (start <= end) {
        // Find mid
        mid = (start + end) / 2;
        // If number is perfect square
        // then break
        if (mid * mid == number) {
            ans = mid;
            break;
        }
        // Increment start if integral
        // part lies on right side
        // of the mid
        if (mid * mid < number) {
          //first start value should be added to answer
            ans=start;
          //then start should be changed
            start = mid + 1.;
        }
        // Decrement end if integral part
        // lies on the left side of the mid
        else {
            end = mid - 1.;
        }
    }
    // To find the fractional part
    // of square root upto 5 decimal
    double increment = 0.1;
    for (int i = 0; i < 5; i++) {
        while (ans * ans <= number) {
            ans += increment;
        }
        // Loop terminates,
        // when ans * ans > number
        ans = ans - increment;
        increment = increment / 10;
    }
    return ans;
}
References average_double_vector().
stdev_float_vector()
float stdev_float_vector (Flt * vec)
This function wil calculate the standard deviation for the values in a vector container.
/param vec A vector data structure of type Flt
Flt vec;
init_float_vector(&vec, 10);
float a[10] = {1., 2., 3., 4., 5., 6., 7., 8., 9., 10.};
insert_float_vector(&vec, a, 10, 0);
float stdev = stdev_float_vector(&vec);
PRINT(stdev);
// >> 3.2076
free_float_vector(&vec);
Definition at line 3826 of file vector.c.
                                   {
    float average = average_float_vector(vec);
    float var = 0.0;
    float value;
    for (size_t i = 0; i < vec->active_length; i++) {
        value = (float)vec->array[i];
        var += ((value - average) * (value - average));
    }
    float interm = (1.0f / ((float)vec->active_length - 1.0f)) * var;
    float number = interm;
    float start = 0.0, end = number;
    float mid;
    // To store the answer
    float ans = 0.;
    // To find integral part of square
    // root of number
    while (start <= end) {
        // Find mid
        mid = (start + end) / 2;
        // If number is perfect square
        // then break
        if (mid * mid == number) {
            ans = mid;
            break;
        }
        // Increment start if integral
        // part lies on right side
        // of the mid
        if (mid * mid < number) {
          //first start value should be added to answer
            ans=start;
          //then start should be changed
            start = mid + 1.f;
        }
        // Decrement end if integral part
        // lies on the left side of the mid
        else {
            end = mid - 1.f;
        }
    }
    // To find the fractional part
    // of square root upto 5 decimal
    float increment = 0.1;
    for (int i = 0; i < 5; i++) {
        while (ans * ans <= number) {
            ans += increment;
        }
        // Loop terminates,
        // when ans * ans > number
        ans = ans - increment;
        increment = increment / 10;
    }
    return ans;
}
References average_float_vector().
stdev_int_vector()
float stdev_int_vector (Int * vec)
This function wil calculate the standard deviation for the values in a vector container.
/param vec A vector data structure of type Int
Int vec;
init_int_vector(&vec, 10);
int a[10] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
insert_int_vector(&vec, a, 10, 0);
float stdev = stdev_int_vector(&vec);
PRINT(stdev);
// >> 3.2076
free_int_vector(&vec);
Definition at line 3478 of file vector.c.
                                 {
    float average = average_int_vector(vec);
    float var = 0.0;
    float value;
    for (size_t i = 0; i < vec->active_length; i++) {
        value = (float)vec->array[i];
        var += ((value - average) * (value - average));
    }
    float interm = (1.0f / ((float)vec->active_length - 1.0f)) * var;
    float number = interm;
    float start = 0.0f, end = number;
    float mid;
    // To store the answer
    float ans = 0.;
    // To find integral part of square
    // root of number
    while (start <= end) {
        // Find mid
        mid = (start + end) / 2;
        // If number is perfect square
        // then break
        if (mid * mid == number) {
            ans = mid;
            break;
        }
        // Increment start if integral
        // part lies on right side
        // of the mid
        if (mid * mid < number) {
          //first start value should be added to answer
            ans=start;
          //then start should be changed
            start = mid + 1.f;
        }
        // Decrement end if integral part
        // lies on the left side of the mid
        else {
            end = mid - 1.f;
        }
    }
    // To find the fractional part
    // of square root upto 5 decimal
    float increment = 0.1;
    for (int i = 0; i < 5; i++) {
        while (ans * ans <= number) {
            ans += increment;
        }
        // Loop terminates,
        // when ans * ans > number
        ans = ans - increment;
        increment = increment / 10;
    }
    return ans;
}
References average_int_vector().
stdev_ldouble_vector()
long double stdev_ldouble_vector (LDble * vec)
This function wil calculate the standard deviation for the values in a vector container.
/param vec A vector data structure of type LDble
LDble vec;
init_ldouble_vector(&vec, 10);
long double a[10] = {1., 2., 3., 4., 5., 6., 7., 8., 9., 10.};
insert_ldouble_vector(&vec, a, 10, 0);
long double stdev = stdev_ldouble_vector(&vec);
PRINT(stdev);
// >> 3.2076
free_ldouble_vector(&vec);
Definition at line 3942 of file vector.c.
                                             {
    long double average = average_ldouble_vector(vec);
    long double var = 0.0;
    long double value;
    for (size_t i = 0; i < vec->active_length; i++) {
        value = (long double)vec->array[i];
        var += ((value - average) * (value - average));
    }
    long double interm = (1.0 / ((long double)vec->active_length - 1.0)) * var;
    long double number = interm;
    long double start = 0.0, end = number;
    long double mid;
    // To store the answer
    long double ans = 0.;
    // To find integral part of square
    // root of number
    while (start <= end) {
        // Find mid
        mid = (start + end) / 2;
        // If number is perfect square
        // then break
        if (mid * mid == number) {
            ans = mid;
            break;
        }
        // Increment start if integral
        // part lies on right side
        // of the mid
        if (mid * mid < number) {
          //first start value should be added to answer
            ans=start;
          //then start should be changed
            start = mid + 1.;
        }
        // Decrement end if integral part
        // lies on the left side of the mid
        else {
            end = mid - 1.;
        }
    }
    // To find the fractional part
    // of square root upto 5 decimal
    long double increment = 0.1;
    for (int i = 0; i < 5; i++) {
        while (ans * ans <= number) {
            ans += increment;
        }
        // Loop terminates,
        // when ans * ans > number
        ans = ans - increment;
        increment = increment / 10;
    }
    return ans;
}
References average_ldouble_vector().
stdev_llong_vector()
long double stdev_llong_vector (LLInt * vec)
This function wil calculate the standard deviation for the values in a vector container.
/param vec A vector data structure of type LLInt
LLInt vec;
init_llong_vector(&vec, 10);
long long int a[10] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
insert_llong_vector(&vec, a, 10, 0);
long double stdev = stdev_llong_vector(&vec);
PRINT(stdev);
// >> 3.2076
free_llong_vector(&vec);
Definition at line 3710 of file vector.c.
                                           {
    long double average = average_llong_vector(vec);
    long double var = 0.0;
    long double value;
    for (size_t i = 0; i < vec->active_length; i++) {
        value = (long double)vec->array[i];
        var += ((value - average) * (value - average));
    }
    long double interm = (1.0 / ((long double)vec->active_length - 1.0)) * var;
    long double number = interm;
    long double start = 0.0, end = number;
    long double mid;
    // To store the answer
    long double ans = 0.;
    // To find integral part of square
    // root of number
    while (start <= end) {
        // Find mid
        mid = (start + end) / 2;
        // If number is perfect square
        // then break
        if (mid * mid == number) {
            ans = mid;
            break;
        }
        // Increment start if integral
        // part lies on right side
        // of the mid
        if (mid * mid < number) {
          //first start value should be added to answer
            ans=start;
          //then start should be changed
            start = mid + 1.;
        }
        // Decrement end if integral part
        // lies on the left side of the mid
        else {
            end = mid - 1.;
        }
    }
    // To find the fractional part
    // of square root upto 5 decimal
    long double increment = 0.1;
    for (int i = 0; i < 5; i++) {
        while (ans * ans <= number) {
            ans += increment;
        }
        // Loop terminates,
        // when ans * ans > number
        ans = ans - increment;
        increment = increment / 10;
    }
    return ans;
}
References average_llong_vector().
stdev_long_vector()
double stdev_long_vector (LInt * vec)
This function wil calculate the standard deviation for the values in a vector container.
/param vec A vector data structure of type LInt
LInt vec;
init_long_vector(&vec, 10);
long int a[10] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
insert_long_vector(&vec, a, 10, 0);
double stdev = stdev_long_vector(&vec);
PRINT(stdev);
// >> 3.2076
free_long_vector(&vec);
Definition at line 3594 of file vector.c.
                                    {
    double average = average_long_vector(vec);
    double var = 0.0;
    double value;
    for (size_t i = 0; i < vec->active_length; i++) {
        value = (double)vec->array[i];
        var += ((value - average) * (value - average));
    }
    double interm = (1.0 / ((double)vec->active_length - 1.0)) * var;
    double number = interm;
    double start = 0.0, end = number;
    double mid;
    // To store the answer
    double ans = 0.;
    // To find integral part of square
    // root of number
    while (start <= end) {
        // Find mid
        mid = (start + end) / 2;
        // If number is perfect square
        // then break
        if (mid * mid == number) {
            ans = mid;
            break;
        }
        // Increment start if integral
        // part lies on right side
        // of the mid
        if (mid * mid < number) {
          //first start value should be added to answer
            ans=start;
          //then start should be changed
            start = mid + 1.;
        }
        // Decrement end if integral part
        // lies on the left side of the mid
        else {
            end = mid - 1.;
        }
    }
    // To find the fractional part
    // of square root upto 5 decimal
    double increment = 0.1;
    for (int i = 0; i < 5; i++) {
        while (ans * ans <= number) {
            ans += increment;
        }
        // Loop terminates,
        // when ans * ans > number
        ans = ans - increment;
        increment = increment / 10;
    }
    return ans;
}
References average_long_vector().
stdev_short_vector()
float stdev_short_vector (Short * vec)
This function wil calculate the standard deviation for the values in a vector container.
/param vec A vector data structure of type Short
Short vec;
init_short_vector(&vec, 10);
short int a[10] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
insert_short_vector(&vec, a, 10, 0);
float stdev = stdev_short_vector(&vec);
PRINT(stdev);
// >> 3.2076
free_short_vector(&vec);
Definition at line 3362 of file vector.c.
                                     {
    float average = average_short_vector(vec);
    float var = 0.0;
    float value;
    for (size_t i = 0; i < vec->active_length; i++) {
        value = (float)vec->array[i];
        var += ((value - average) * (value - average));
    }
    float interm = (1.0f / ((float)vec->active_length - 1.0f)) * var;
    float number = interm;
    float start = 0.0f, end = number;
    float mid;
    // To store the answer
    float ans = 0.;
    // To find integral part of square
    // root of number
    while (start <= end) {
        // Find mid
        mid = (start + end) / 2;
        // If number is perfect square
        // then break
        if (mid * mid == number) {
            ans = mid;
            break;
        }
        // Increment start if integral
        // part lies on right side
        // of the mid
        if (mid * mid < number) {
          //first start value should be added to answer
            ans=start;
          //then start should be changed
            start = mid + 1.f;
        }
        // Decrement end if integral part
        // lies on the left side of the mid
        else {
            end = mid - 1.f;
        }
    }
    // To find the fractional part
    // of square root upto 5 decimal
    float increment = 0.1f;
    for (int i = 0; i < 5; i++) {
        while (ans * ans <= number) {
            ans += increment;
        }
        // Loop terminates,
        // when ans * ans > number
        ans = ans - increment;
        increment = increment / 10;
    }
    return ans;
}
References average_short_vector().
stdev_uchar_vector()
char stdev_uchar_vector (UChar * vec)
This function wil calculate the standard deviation for the values in a vector container.
/param vec A vector data structure of type UChar
UChar vec;
init_uchar_vector(&vec, 10);
unsigned char a[10] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
insert_uchar_vector(&vec, a, 10, 0);
unsigned char stdev = stdev_uchar_vector(&vec);
PRINT(stdev);
// >> 3.2076
free_uchar_vector(&vec);
Definition at line 3304 of file vector.c.
                                    {
    char average = average_uchar_vector(vec);
    char var = 0.0;
    char value;
    for (size_t i = 0; i < vec->active_length; i++) {
        value = (float)vec->array[i];
        var += ((value - average) * (value - average));
    }
    char interm = (1.0f / ((float)vec->active_length - 1.0f)) * var;
    char number = interm;
    char start = 0.0f, end = number;
    char mid;
    // To store the answer
    char ans = 0.;
    // To find integral part of square
    // root of number
    while (start <= end) {
        // Find mid
        mid = (start + end) / 2;
        // If number is perfect square
        // then break
        if (mid * mid == number) {
            ans = mid;
            break;
        }
        // Increment start if integral
        // part lies on right side
        // of the mid
        if (mid * mid < number) {
          //first start value should be added to answer
            ans=start;
          //then start should be changed
            start = mid + 1.f;
        }
        // Decrement end if integral part
        // lies on the left side of the mid
        else {
            end = mid - 1.f;
        }
    }
    // To find the fractional part
    // of square root upto 5 decimal
    float increment = 0.1f;
    for (int i = 0; i < 5; i++) {
        while (ans * ans <= number) {
            ans += increment;
        }
        // Loop terminates,
        // when ans * ans > number
        ans = ans - increment;
        increment = increment / 10;
    }
    return ans;
}
References average_uchar_vector().
stdev_uint_vector()
float stdev_uint_vector (UInt * vec)
This function wil calculate the standard deviation for the values in a vector container.
/param vec A vector data structure of type UInt
UInt vec;
init_uint_vector(&vec, 10);
unsigned int a[10] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
insert_uint_vector(&vec, a, 10, 0);
float stdev = stdev_uint_vector(&vec);
PRINT(stdev);
// >> 3.2076
free_uint_vector(&vec);
Definition at line 3536 of file vector.c.
                                   {
    float average = average_uint_vector(vec);
    float var = 0.0;
    float value;
    for (size_t i = 0; i < vec->active_length; i++) {
        value = (float)vec->array[i];
        var += ((value - average) * (value - average));
    }
    float interm = (1.0f / ((float)vec->active_length - 1.0f)) * var;
    float number = interm;
    float start = 0.0f, end = number;
    float mid;
    // To store the answer
    float ans = 0.;
    // To find integral part of square
    // root of number
    while (start <= end) {
        // Find mid
        mid = (start + end) / 2;
        // If number is perfect square
        // then break
        if (mid * mid == number) {
            ans = mid;
            break;
        }
        // Increment start if integral
        // part lies on right side
        // of the mid
        if (mid * mid < number) {
          //first start value should be added to answer
            ans=start;
          //then start should be changed
            start = mid + 1.f;
        }
        // Decrement end if integral part
        // lies on the left side of the mid
        else {
            end = mid - 1.f;
        }
    }
    // To find the fractional part
    // of square root upto 5 decimal
    float increment = 0.1;
    for (int i = 0; i < 5; i++) {
        while (ans * ans <= number) {
            ans += increment;
        }
        // Loop terminates,
        // when ans * ans > number
        ans = ans - increment;
        increment = increment / 10;
    }
    return ans;
}
References average_uint_vector().
stdev_ullong_vector()
long double stdev_ullong_vector (ULLInt * vec)
This function wil calculate the standard deviation for the values in a vector container.
/param vec A vector data structure of type ULLInt
ULLInt vec;
init_ullong_vector(&vec, 10);
unsigned long long int a[10] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
insert_ullong_vector(&vec, a, 10, 0);
long double stdev = stdev_ullong_vector(&vec);
PRINT(stdev);
// >> 3.2076
free_ullong_vector(&vec);
Definition at line 3768 of file vector.c.
                                             {
    long double average = average_ullong_vector(vec);
    long double var = 0.0;
    long double value;
    for (size_t i = 0; i < vec->active_length; i++) {
        value = (long double)vec->array[i];
        var += ((value - average) * (value - average));
    }
    long double interm = (1.0 / ((long double)vec->active_length - 1.0)) * var;
    long double number = interm;
    long double start = 0.0, end = number;
    long double mid;
    // To store the answer
    long double ans = 0.;
    // To find integral part of square
    // root of number
    while (start <= end) {
        // Find mid
        mid = (start + end) / 2;
        // If number is perfect square
        // then break
        if (mid * mid == number) {
            ans = mid;
            break;
        }
        // Increment start if integral
        // part lies on right side
        // of the mid
        if (mid * mid < number) {
          //first start value should be added to answer
            ans=start;
          //then start should be changed
            start = mid + 1.;
        }
        // Decrement end if integral part
        // lies on the left side of the mid
        else {
            end = mid - 1.;
        }
    }
    // To find the fractional part
    // of square root upto 5 decimal
    long double increment = 0.1;
    for (int i = 0; i < 5; i++) {
        while (ans * ans <= number) {
            ans += increment;
        }
        // Loop terminates,
        // when ans * ans > number
        ans = ans - increment;
        increment = increment / 10;
    }
    return ans;
}
References average_ullong_vector().
stdev_ulong_vector()
double stdev_ulong_vector (ULInt * vec)
This function wil calculate the standard deviation for the values in a vector container.
/param vec A vector data structure of type ULInt
ULInt vec;
init_ulong_vector(&vec, 10);
unsigned long int a[10] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
insert_ulong_vector(&vec, a, 10, 0);
double stdev = stdev_ulong_vector(&vec);
PRINT(stdev);
// >> 3.2076
free_ulong_vector(&vec);
Definition at line 3652 of file vector.c.
                                      {
    double average = average_ulong_vector(vec);
    double var = 0.0;
    double value;
    for (size_t i = 0; i < vec->active_length; i++) {
        value = (double)vec->array[i];
        var += ((value - average) * (value - average));
    }
    double interm = (1.0 / ((double)vec->active_length - 1.0)) * var;
    double number = interm;
    double start = 0.0, end = number;
    double mid;
    // To store the answer
    double ans = 0.;
    // To find integral part of square
    // root of number
    while (start <= end) {
        // Find mid
        mid = (start + end) / 2;
        // If number is perfect square
        // then break
        if (mid * mid == number) {
            ans = mid;
            break;
        }
        // Increment start if integral
        // part lies on right side
        // of the mid
        if (mid * mid < number) {
          //first start value should be added to answer
            ans=start;
          //then start should be changed
            start = mid + 1.;
        }
        // Decrement end if integral part
        // lies on the left side of the mid
        else {
            end = mid - 1.;
        }
    }
    // To find the fractional part
    // of square root upto 5 decimal
    double increment = 0.1;
    for (int i = 0; i < 5; i++) {
        while (ans * ans <= number) {
            ans += increment;
        }
        // Loop terminates,
        // when ans * ans > number
        ans = ans - increment;
        increment = increment / 10;
    }
    return ans;
}
References average_ulong_vector().
stdev_ushort_vector()
float stdev_ushort_vector (UShort * vec)
This function wil calculate the standard deviation for the values in a vector container.
/param vec A vector data structure of type UShort
UShort vec;
init_ushort_vector(&vec, 10);
unsigned short int a[10] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
insert_ushort_vector(&vec, a, 10, 0);
float stdev = stdev_ushort_vector(&vec);
PRINT(stdev);
// >> 3.2076
free_ushort_vector(&vec);
Definition at line 3420 of file vector.c.
                                       {
    float average = average_ushort_vector(vec);
    float var = 0.0;
    float value;
    for (size_t i = 0; i < vec->active_length; i++) {
        value = (float)vec->array[i];
        var += ((value - average) * (value - average));
    }
    float interm = (1.0f / ((float)vec->active_length - 1.0f)) * var;
    float number = interm;
    float start = 0.0f, end = number;
    float mid;
    // To store the answer
    float ans = 0.;
    // To find integral part of square
    // root of number
    while (start <= end) {
        // Find mid
        mid = (start + end) / 2;
        // If number is perfect square
        // then break
        if (mid * mid == number) {
            ans = mid;
            break;
        }
        // Increment start if integral
        // part lies on right side
        // of the mid
        if (mid * mid < number) {
          //first start value should be added to answer
            ans=start;
          //then start should be changed
            start = mid + 1.f;
        }
        // Decrement end if integral part
        // lies on the left side of the mid
        else {
            end = mid - 1.f;
        }
    }
    // To find the fractional part
    // of square root upto 5 decimal
    float increment = 0.1;
    for (int i = 0; i < 5; i++) {
        while (ans * ans <= number) {
            ans += increment;
        }
        // Loop terminates,
        // when ans * ans > number
        ans = ans - increment;
        increment = increment / 10;
    }
    return ans;
}
References average_ushort_vector().
string_vector_data()
char * string_vector_data (String * vec, size_t index)
This function will retireve the data from a user specified index in a vector or array of type String
/param vec A linked list struct of type String /param index The index from where data will be retrieved /return dat An unsigned bool data point
String vec;
init_string_vector(&vec);
push_string_vector(&vec, "One", 0);
push_string_vector(&vec, "Two", 1);
push_string_vector(&vec, "Three", 2);
PRINT(string_vector_data(&vec, 2));
// >> Three
free_string_vector(&vec);
Definition at line 4458 of file vector.c.
{ return vec->array[index]; }
References String::array.
sum_char_vector()
char sum_char_vector (Char * vec)
This function will calculate the sum of the values in a vector data structure of type Short
/param vec A vector data structure of type Short
Char vec;
init_short_vector(vec, 5);
char a[5] = {1, 2, 3, 4, 5};
insert_char_vector(&vec, a, 5, 0);
char sum_value = sum_char_vector(vec);
PRINT(vec);
// >> 15
free_char_vector(&vec);
Definition at line 2877 of file vector.c.
                                {
    char sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
    }
    return sum;
}
Referenced by average_char_vector().
sum_double_vector()
double sum_double_vector (Dble * vec)
This function will calculate the sum of the values in a vector data structure of type Dble
/param vec A vector data structure of type Dble
Dble vec;
init_double_vector(vec, 5);
double a[5] = {1., 2., 3., 4., 5.};
insert_double_vector(&vec, a, 5, 0);
double sum_value = sum_double_vector(vec);
PRINT(vec);
// >> 15
free_double_vector(&vec);
Definition at line 2976 of file vector.c.
                                    {
    double sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
    }
    return sum;
}
Referenced by average_double_vector().
sum_float_vector()
float sum_float_vector (Flt * vec)
This function will calculate the sum of the values in a vector data structure of type Flt
/param vec A vector data structure of type Flt
Flt vec;
init_float_vector(vec, 5);
float a[5] = {1., 2., 3., 4., 5.};
insert_float_vector(&vec, a, 5, 0);
float sum_value = sum_float_vector(vec);
PRINT(vec);
// >> 15
free_float_vector(&vec);
Definition at line 2967 of file vector.c.
                                 {
    float sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
    }
    return sum;
}
Referenced by average_float_vector().
sum_int_vector()
int sum_int_vector (Int * vec)
This function will calculate the sum of the values in a vector data structure of type Int
/param vec A vector data structure of type Int
Int vec;
init_int_vector(vec, 5);
int a[5] = {1, 2, 3, 4, 5};
insert_int_vector(&vec, a, 5, 0);
int sum_value = sum_int_vector(vec);
PRINT(vec);
// >> 15
free_int_vector(&vec);
Definition at line 2913 of file vector.c.
                             {
    int sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
    }
    return sum;
}
Referenced by average_int_vector().
sum_ldouble_vector()
long double sum_ldouble_vector (LDble * vec)
This function will calculate the sum of the values in a vector data structure of type LDble
/param vec A vector data structure of type LDble
LDble vec;
init_ldouble_vector(vec, 5);
long double a[5] = {1., 2., 3., 4., 5.};
insert_ldouble_vector(&vec, a, 5, 0);
long double sum_value = sum_ldouble_vector(vec);
PRINT(vec);
// >> 15
free_ldouble_vector(&vec)
Definition at line 2985 of file vector.c.
                                           {
    long double sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
    }
    return sum;
}
Referenced by average_ldouble_vector().
sum_llong_vector()
long long int sum_llong_vector (LLInt * vec)
This function will calculate the sum of the values in a vector data structure of type LLInt
/param vec A vector data structure of type LLInt
LLInt vec;
init_llong_vector(vec, 5);
long long int a[5] = {1, 2, 3, 4, 5};
insert_llong_vector(&vec, a, 5, 0);
long long int sum_value = sum_llong_vector(vec);
PRINT(vec);
// >> 15
free_llong_vector(&vec);
Definition at line 2949 of file vector.c.
                                           {
    long long int sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
    }
    return sum;
}
Referenced by average_llong_vector().
sum_long_vector()
long int sum_long_vector (LInt * vec)
This function will calculate the sum of the values in a vector data structure of type LInt
/param vec A vector data structure of type LInt
LInt vec;
init_long_vector(vec, 5);
long int a[5] = {1, 2, 3, 4, 5};
insert_long_vector(&vec, a, 5, 0);
long int sum_value = sum_long_vector(vec);
PRINT(vec);
// >> 15
free_long_vector(&vec);
Definition at line 2931 of file vector.c.
                                    {
    long int sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
    }
    return sum;
}
Referenced by average_long_vector().
sum_short_vector()
short int sum_short_vector (Short * vec)
This function will calculate the sum of the values in a vector data structure of type Short
/param vec A vector data structure of type Short
Short vec;
init_short_vector(vec, 5);
short int a[5] = {1, 2, 3, 4, 5};
insert_short_vector(&vec, a, 5, 0);
short int sum_value = sum_short_vector(vec);
PRINT(vec);
// >> 15
free_short_vector(&vec);
Definition at line 2895 of file vector.c.
                                       {
    short int sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
    }
    return sum;
}
Referenced by average_short_vector().
sum_uchar_vector()
unsigned char sum_uchar_vector (UChar * vec)
This function will calculate the sum of the values in a vector data structure of type Short
/param vec A vector data structure of type Short
UChar vec;
init_uchar_vector(vec, 5);
unsgined char a[5] = {1, 2, 3, 4, 5};
insert_uchar_vector(&vec, a, 5, 0);
unsigned char sum_value = sum_uchar_vector(vec);
PRINT(vec);
// >> 15
free_uchar_vector(&vec);
Definition at line 2886 of file vector.c.
                                           {
    unsigned char sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
    }
    return sum;
}
Referenced by average_uchar_vector().
sum_uint_vector()
unsigned int sum_uint_vector (UInt * vec)
This function will calculate the sum of the values in a vector data structure of type UInt
/param vec A vector data structure of type UInt
UInt vec;
init_uint_vector(vec, 5);
unsigned int a[5] = {1, 2, 3, 4, 5};
insert_uint_vector(&vec, a, 5, 0);
unsigned int sum_value = sum_uint_vector(vec);
PRINT(vec);
// >> 15
free_uint_vector(&vec);
Definition at line 2922 of file vector.c.
                                        {
    unsigned int sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
    }
    return sum;
}
Referenced by average_uint_vector().
sum_ullong_vector()
unsigned long long int sum_ullong_vector (ULLInt * vec)
This function will calculate the sum of the values in a vector data structure of type ULLInt
/param vec A vector data structure of type ULLInt
ULLInt vec;
init_ullong_vector(vec, 5);
unsigned long long int a[5] = {1, 2, 3, 4, 5};
insert_ullong_vector(&vec, a, 5, 0);
unsigned long long int sum_value = sum_ullong_vector(vec);
PRINT(vec);
// >> 15
free_ullong_vector(&vec);
Definition at line 2958 of file vector.c.
                                                      {
    unsigned long long int sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
    }
    return sum;
}
Referenced by average_ullong_vector().
sum_ulong_vector()
unsigned long int sum_ulong_vector (ULInt * vec)
This function will calculate the sum of the values in a vector data structure of type ULInt
/param vec A vector data structure of type ULInt
ULInt vec;
init_ulong_vector(vec, 5);
unsigned long int a[5] = {1, 2, 3, 4, 5};
insert_ulong_vector(&vec, a, 5, 0);
unsigned long int sum_value = sum_ulong_vector(vec);
PRINT(vec);
// >> 15
free_ulong_vector(&vec);
Definition at line 2940 of file vector.c.
                                               {
    unsigned long int sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
    }
    return sum;
}
Referenced by average_ulong_vector().
sum_ushort_vector()
unsigned short int sum_ushort_vector (UShort * vec)
This function will calculate the sum of the values in a vector data structure of type UShort
/param vec A vector data structure of type UShort
UShort vec;
init_ushort_vector(vec, 5);
unsigned short int a[5] = {1, 2, 3, 4, 5};
insert_ushort_vector(&vec, a, 5, 0);
unsigned short int sum_value = sum_ushort_vector(vec);
PRINT(vec);
// >> 15
free_ushort_vector(&vec);
Definition at line 2904 of file vector.c.
                                                  {
    unsigned short int sum = 0;
    for (size_t i = 0; i < vec->active_length; i++) {
        sum += vec->array[i];
    }
    return sum;
}
Referenced by average_ushort_vector().
trim_bool_vector()
void trim_bool_vector (Bool * vec)
This function will resize the memory allocated to a dynamically allocated vector to the minimum necessary size.
/param vec A vector struct of type Bool
Definition at line 4735 of file vector.c.
                                 {
    bool *ptr = (bool *)realloc(vec->array, vec->active_length * sizeof(bool));
    // Verify that sufficient memory exists
    if (ptr == NULL) {
        fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
    }
    // allocate memory
    vec->array = ptr;
    vec->allocated_length = vec->active_length;
}
trim_char_vector()
void trim_char_vector (Char * vec)
This function will resize the memory allocated to a dynamically allocated vector to the minimum necessary size.
/param vec A vector struct of type Char
Definition at line 4711 of file vector.c.
                                 {
    char *ptr = (char *)realloc(vec->array, vec->active_length * sizeof(char));
    // Verify that sufficient memory exists
    if (ptr == NULL) {
        fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
    }
    // allocate memory
    vec->array = ptr;
    vec->allocated_length = vec->active_length;
}
trim_double_vector()
void trim_double_vector (Dble * vec)
This function will resize the memory allocated to a dynamically allocated vector to the minimum necessary size.
/param vec A vector struct of type Dble
Definition at line 4687 of file vector.c.
                                   {
    double *ptr = (double *)realloc(vec->array, vec->active_length * sizeof(double));
    // Verify that sufficient memory exists
    if (ptr == NULL) {
        fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
    }
    // allocate memory
    vec->array = ptr;
    vec->allocated_length = vec->active_length;
}
trim_float_vector()
void trim_float_vector (Flt * vec)
This function will resize the memory allocated to a dynamically allocated vector to the minimum necessary size.
/param vec A vector struct of type Flt
Definition at line 4675 of file vector.c.
                                 {
    float *ptr = (float *)realloc(vec->array, vec->active_length * sizeof(float));
    // Verify that sufficient memory exists
    if (ptr == NULL) {
        fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
    }
    // allocate memory
    vec->array = ptr;
    vec->allocated_length = vec->active_length;
}
trim_int_vector()
void trim_int_vector (Int * vec)
This function will resize the memory allocated to a dynamically allocated vector to the minimum necessary size.
/param vec A vector struct of type Int
Definition at line 4603 of file vector.c.
                               {
    int *ptr = (int *)realloc(vec->array, vec->active_length * sizeof(int));
    // Verify that sufficient memory exists
    if (ptr == NULL) {
        fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
    }
    // allocate memory
    vec->array = ptr;
    vec->allocated_length = vec->active_length;
}
trim_ldouble_vector()
void trim_ldouble_vector (LDble * vec)
This function will resize the memory allocated to a dynamically allocated vector to the minimum necessary size.
/param vec A vector struct of type LDble
Definition at line 4699 of file vector.c.
                                     {
    long double *ptr = (long double *)realloc(vec->array, vec->active_length * sizeof(long double));
    // Verify that sufficient memory exists
    if (ptr == NULL) {
        fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
    }
    // allocate memory
    vec->array = ptr;
    vec->allocated_length = vec->active_length;
}
trim_llong_vector()
void trim_llong_vector (LLInt * vec)
This function will resize the memory allocated to a dynamically allocated vector to the minimum necessary size.
/param vec A vector struct of type LLInt
Definition at line 4651 of file vector.c.
                                   {
    long long *ptr = (long long *)realloc(vec->array, vec->active_length * sizeof(long long));
    // Verify that sufficient memory exists
    if (ptr == NULL) {
        fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
    }
    // allocate memory
    vec->array = ptr;
    vec->allocated_length = vec->active_length;
}
trim_long_vector()
void trim_long_vector (LInt * vec)
This function will resize the memory allocated to a dynamically allocated vector to the minimum necessary size.
/param vec A vector struct of type LInt
Definition at line 4627 of file vector.c.
                                 {
    long *ptr = (long *)realloc(vec->array, vec->active_length * sizeof(long));
    // Verify that sufficient memory exists
    if (ptr == NULL) {
        fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
    }
    // allocate memory
    vec->array = ptr;
    vec->allocated_length = vec->active_length;
}
trim_short_vector()
void trim_short_vector (Short * vec)
This function will resize the memory allocated to a dynamically allocated vector to the minimum necessary size.
/param vec A vector struct of type Short
Definition at line 4579 of file vector.c.
                                   {
    short *ptr = (short *)realloc(vec->array, vec->active_length * sizeof(short));
    // Verify that sufficient memory exists
    if (ptr == NULL) {
        fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
    }
    // allocate memory
    vec->array = ptr;
    vec->allocated_length = vec->active_length;
}
trim_uchar_vector()
void trim_uchar_vector (UChar * vec)
This function will resize the memory allocated to a dynamically allocated vector to the minimum necessary size.
/param vec A vector struct of type UChar
Definition at line 4723 of file vector.c.
                                   {
    unsigned char *ptr = (unsigned char *)realloc(vec->array, vec->active_length * sizeof(unsigned char));
    // Verify that sufficient memory exists
    if (ptr == NULL) {
        fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
    }
    // allocate memory
    vec->array = ptr;
    vec->allocated_length = vec->active_length;
}
trim_uint_vector()
void trim_uint_vector (UInt * vec)
This function will resize the memory allocated to a dynamically allocated vector to the minimum necessary size.
/param vec A vector struct of type UInt
Definition at line 4615 of file vector.c.
                                 {
    unsigned int *ptr = (unsigned int *)realloc(vec->array, vec->active_length * sizeof(unsigned int));
    // Verify that sufficient memory exists
    if (ptr == NULL) {
        fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
    }
    // allocate memory
    vec->array = ptr;
    vec->allocated_length = vec->active_length;
}
trim_ullong_vector()
void trim_ullong_vector (ULLInt * vec)
This function will resize the memory allocated to a dynamically allocated vector to the minimum necessary size.
/param vec A vector struct of type ULLInt
Definition at line 4663 of file vector.c.
                                     {
    unsigned long long *ptr = (unsigned long long *)realloc(vec->array, vec->active_length * sizeof(unsigned long long));
    // Verify that sufficient memory exists
    if (ptr == NULL) {
        fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
    }
    // allocate memory
    vec->array = ptr;
    vec->allocated_length = vec->active_length;
}
trim_ulong_vector()
void trim_ulong_vector (ULInt * vec)
This function will resize the memory allocated to a dynamically allocated vector to the minimum necessary size.
/param vec A vector struct of type ULInt
Definition at line 4639 of file vector.c.
                                   {
    unsigned long *ptr = (unsigned long *)realloc(vec->array, vec->active_length * sizeof(unsigned long));
    // Verify that sufficient memory exists
    if (ptr == NULL) {
        fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
    }
    // allocate memory
    vec->array = ptr;
    vec->allocated_length = vec->active_length;
}
trim_ushort_vector()
void trim_ushort_vector (UShort * vec)
This function will resize the memory allocated to a dynamically allocated vector to the minimum necessary size.
/param vec A vector struct of type UShort
Definition at line 4591 of file vector.c.
                                     {
    unsigned short *ptr = (unsigned short *)realloc(vec->array, vec->active_length * sizeof(unsigned short));
    // Verify that sufficient memory exists
    if (ptr == NULL) {
        fprintf(stderr, "Realloc failed in file %s on line %d\n", __FILE__, __LINE__);
    }
    // allocate memory
    vec->array = ptr;
    vec->allocated_length = vec->active_length;
}
uint_vector_data()
unsigned int uint_vector_data (UInt * vec, size_t index)
This function will retireve the data from a user specified index in a vector or array of type UInt
/param vec A linked list struct of type UInt /param index The index from where data will be retrieved /return dat An unsigned bool data point
UInt vec;
init_uint_vector(&vec);
unsigned int a[5] = {1, 2, 3, 4, 5};
insert_uint_vector(&vec, a, 5, 0);
PRINT(uint_vector_data(&vec, 2));
// >> 3
free_uint_vector(&vec);
Definition at line 4428 of file vector.c.
{ return vec->array[index]; }
ullong_vector_data()
unsigned long long int ullong_vector_data (ULLInt * vec, size_t index)
This function will retireve the data from a user specified index in a vector or array of type ULLInt
/param vec A linked list struct of type ULLInt /param index The index from where data will be retrieved /return dat An unsigned bool data point
ULLInt vec;
init_ullong_vector(&vec);
unsigned long long int a[5] = {1, 2, 3, 4, 5};
insert_ullong_vector(&vec, a, 5, 0);
PRINT(ullong_vector_data(&vec, 2));
// >> 3
free_ullong_vector(&vec);
Definition at line 4440 of file vector.c.
{ return vec->array[index]; }
ulong_vector_data()
unsigned long int ulong_vector_data (ULInt * vec, size_t index)
This function will retireve the data from a user specified index in a vector or array of type ULInt
/param vec A linked list struct of type ULInt /param index The index from where data will be retrieved /return dat An unsigned bool data point
ULInt vec;
init_ulong_vector(&vec);
unsigned long int a[5] = {1, 2, 3, 4, 5};
insert_ulong_vector(&vec, a, 5, 0);
PRINT(ulong_vector_data(&vec, 2));
// >> 3
free_ulong_vector(&vec);
Definition at line 4434 of file vector.c.
{ return vec->array[index]; }
ushort_vector_data()
unsigned short int ushort_vector_data (UShort * vec, size_t index)
This function will retireve the data from a user specified index in a vector or array of type UShort
/param vec A linked list struct of type UShort /param index The index from where data will be retrieved /return dat An unsigned bool data point
UShort vec;
init_ushort_vector(&vec);
unsigned short int a[5] = {1, 2, 3, 4, 5};
insert_ushort_vector(&vec, a, 5, 0);
PRINT(ushort_vector_data(&vec, 2));
// >> 3
free_ushort_vector(&vec);
Definition at line 4422 of file vector.c.
{ return vec->array[index]; }
VECTOR_STRUCT() [1/14]
VECTOR_STRUCT (bool , Bool)
VECTOR_STRUCT() [2/14]
VECTOR_STRUCT (char , Char)
VECTOR_STRUCT() [3/14]
VECTOR_STRUCT (double , Dble)
VECTOR_STRUCT() [4/14]
VECTOR_STRUCT (float , Flt)
VECTOR_STRUCT() [5/14]
VECTOR_STRUCT (int , Int)
VECTOR_STRUCT() [6/14]
VECTOR_STRUCT (long double , LDble)
VECTOR_STRUCT() [7/14]
VECTOR_STRUCT (long long int , LLInt)
VECTOR_STRUCT() [8/14]
VECTOR_STRUCT (long , LInt)
VECTOR_STRUCT() [9/14]
VECTOR_STRUCT (short , Short)
VECTOR_STRUCT() [10/14]
VECTOR_STRUCT (unsigned char , UChar)
VECTOR_STRUCT() [11/14]
VECTOR_STRUCT (unsigned long int , ULInt)
VECTOR_STRUCT() [12/14]
VECTOR_STRUCT (unsigned long long int , ULLInt)
VECTOR_STRUCT() [13/14]
VECTOR_STRUCT (unsigned short int , UShort)
VECTOR_STRUCT() [14/14]
VECTOR_STRUCT (unsigned , UInt)