/home/jonwebb/Code_Dev/C/c_libs/c_libs/include/print.h File Reference
#include <stdio.h>
#include <stdbool.h>
#include "vector.h"
Macros
#define PRNT_LENGTH 20
#define IS_ITYPE_VALID(T)
#define ITYPE_FORMAT(T)
#define PRINT1(a)
#define PRINT2(a, b)
#define PRINT3(a, b, c)
#define PRINT4(a, b, c, d)
#define PRINT5(a, b, c, d, e)
#define PRINT6(a, b, c, d, e, f)
#define PRINT7(a, b, c, d, e, f, g)
#define PRINT8(a, b, c, d, e, f, g, h)
#define GET_MACRO(_1, _2, _3, _4, _5, _6, _7, _8, NAME, ...) NAME
#define PRINT(...) GET_MACRO(__VA_ARGS__, PRINT8, PRINT7, PRINT6, PRINT5, PRINT4, PRINT3, PRINT2, PRINT1)(__VA_ARGS__)
Functions
void print_short (short x)
void print_ushort (unsigned short x)
void print_int (int x)
void print_uint (unsigned int x)
void print_long (long int x)
void print_ulong (unsigned long int x)
void print_llong (long long int x)
void print_ullong (unsigned long long int x)
void print_float (float x)
void print_double (double x)
void print_longdouble (long double x)
void print_char (char x)
void print_uchar (unsigned char x)
void print_bool (bool x)
void print_string (char *x)
void print_vshort (Short x)
void print_vushort (UShort x)
void print_vint (Int x)
void print_vuint (UInt x)
void print_vlint (LInt x)
void print_vulint (ULInt x)
void print_vllint (LLInt x)
void print_vullint (ULLInt x)
void print_vfloat (Flt x)
void print_vdble (Dble x)
void print_vldble (LDble x)
void print_achar (Char x)
void print_uachar (UChar x)
void print_vbool (Bool x)
void print_vstring (String x)
Macro Definition Documentation
GET_MACRO
#define GET_MACRO(_1, _2, _3, _4, _5, _6, _7, _8, NAME, ...) NAME
Definition at line 200 of file print.h.
IS_ITYPE_VALID
#define IS_ITYPE_VALID(T)
Value:
                                         _Generic((T), long int: true, \
                                         unsigned long int: true, \
                                         long long int: true, \
                                         unsigned long long int: true, \
                                         float: true, \
                                         double: true, \
                                         long double: true, \
                                         char: true, \
                                         bool: true, \
                                         unsigned char: true, \
                                         char*: true, \
                                         Flt: true, \
                                         Dble: true, \
                                         LDble: true, \
                                         Int: true, \
                                         UInt: true, \
                                         Short: true, \
                                         UShort: true, \
                                         LInt: true, \
                                         ULInt: true, \
                                         LLInt: true, \
                                         ULLInt: true, \
                                         Char: true, \
                                         Bool: true, \
                                         String: true, \
                                         default: false)
Definition at line 29 of file print.h.
                                                 : true, \
                                         unsigned long int: true, \
                                         long long int: true, \
                                         unsigned long long int: true, \
                                         float: true, \
                                         double: true, \
                                         long double: true, \
                                         char: true, \
                                         bool: true, \
                                         unsigned char: true, \
                                         char*: true, \
                                         Flt: true, \
                                         Dble: true, \
                                         LDble: true, \
                                         Int: true, \
                                         UInt: true, \
                                         Short: true, \
                                         UShort: true, \
                                         LInt: true, \
                                         ULInt: true, \
                                         LLInt: true, \
                                         ULLInt: true, \
                                         Char: true, \
                                         Bool: true, \
                                         String: true, \
                                         default: false)
ITYPE_FORMAT
#define ITYPE_FORMAT(T)
Value:
                                       _Generic((T), unsigned char: print_uachar, \
                                       long int: print_long, \
                                       unsigned long int: print_ullong, \
                                       long long int: print_llong, \
                                       unsigned long long int: print_ullong, \
                                       float: print_float, \
                                       double: print_double, \
                                       long double: print_longdouble, \
                                       char: print_char, \
                                       bool: print_bool, \
                                       char*: print_string, \
                                       Int: print_vint, \
                                       UInt: print_vuint, \
                                       Short: print_vshort, \
                                       UShort: print_vushort, \
                                       LInt: print_vlint, \
                                       ULInt: print_vulint, \
                                       LLInt: print_vllint, \
                                       ULLInt: print_vullint, \
                                       Flt: print_vfloat, \
                                       Dble: print_vdble, \
                                       Char: print_achar, \
                                       UChar: print_uachar, \
                                       Bool: print_vbool, \
                                       LDble: print_vldble, \
                                       String: print_vstring)(T)
Definition at line 96 of file print.h.
                                                    : print_uachar, \
                                       long int: print_long, \
                                       unsigned long int: print_ullong, \
                                       long long int: print_llong, \
                                       unsigned long long int: print_ullong, \
                                       float: print_float, \
                                       double: print_double, \
                                       long double: print_longdouble, \
                                       char: print_char, \
                                       bool: print_bool, \
                                       char*: print_string, \
                                       Int: print_vint, \
                                       UInt: print_vuint, \
                                       Short: print_vshort, \
                                       UShort: print_vushort, \
                                       LInt: print_vlint, \
                                       ULInt: print_vulint, \
                                       LLInt: print_vllint, \
                                       ULLInt: print_vullint, \
                                       Flt: print_vfloat, \
                                       Dble: print_vdble, \
                                       Char: print_achar, \
                                       UChar: print_uachar, \
                                       Bool: print_vbool, \
                                       LDble: print_vldble, \
                                       String: print_vstring)(T)
PRINT
#define PRINT(...) GET_MACRO(__VA_ARGS__, PRINT8, PRINT7, PRINT6, PRINT5, PRINT4, PRINT3, PRINT2, PRINT1)(__VA_ARGS__)
This function will print up to 8 arguments of any data type without requiring the user implement a specific format. Unfortunately the present version of this Macro does not allow a user to tailor the format of the print function
float p = 3.14;
PRINT("The value of pi is ", pi);
// >> The value of pi is 3.14000
Definition at line 214 of file print.h.
PRINT1
#define PRINT1(a)
Value:
    do { \
    if (IS_ITYPE_VALID(a)) ITYPE_FORMAT(a); \
    printf("\n"); \
} while (0)
Definition at line 124 of file print.h.
                     { \
    if (IS_ITYPE_VALID(a)) ITYPE_FORMAT(a); \
    printf("\n"); \
} while (0)
PRINT2
#define PRINT2(a, b)
Value:
    do { \
    if (IS_ITYPE_VALID(a)) ITYPE_FORMAT(a); \
    if (IS_ITYPE_VALID(b)) ITYPE_FORMAT(b); \
    printf("\n"); \
} while (0)
Definition at line 130 of file print.h.
                        { \
    if (IS_ITYPE_VALID(a)) ITYPE_FORMAT(a); \
    if (IS_ITYPE_VALID(b)) ITYPE_FORMAT(b); \
    printf("\n"); \
} while (0)
PRINT3
#define PRINT3(a, b, c)
Value:
    do { \
    if (IS_ITYPE_VALID(a)) ITYPE_FORMAT(a); \
    if (IS_ITYPE_VALID(b)) ITYPE_FORMAT(b); \
    if (IS_ITYPE_VALID(c)) ITYPE_FORMAT(c); \
    printf("\n"); \
} while (0)
Definition at line 137 of file print.h.
                           { \
    if (IS_ITYPE_VALID(a)) ITYPE_FORMAT(a); \
    if (IS_ITYPE_VALID(b)) ITYPE_FORMAT(b); \
    if (IS_ITYPE_VALID(c)) ITYPE_FORMAT(c); \
    printf("\n"); \
} while (0)
PRINT4
#define PRINT4(a, b, c, d)
Value:
    do { \
    if (IS_ITYPE_VALID(a)) ITYPE_FORMAT(a); \
    if (IS_ITYPE_VALID(b)) ITYPE_FORMAT(b); \
    if (IS_ITYPE_VALID(c)) ITYPE_FORMAT(c); \
    if (IS_ITYPE_VALID(d)) ITYPE_FORMAT(d); \
    printf("\n"); \
} while (0)
Definition at line 145 of file print.h.
                              { \
    if (IS_ITYPE_VALID(a)) ITYPE_FORMAT(a); \
    if (IS_ITYPE_VALID(b)) ITYPE_FORMAT(b); \
    if (IS_ITYPE_VALID(c)) ITYPE_FORMAT(c); \
    if (IS_ITYPE_VALID(d)) ITYPE_FORMAT(d); \
    printf("\n"); \
} while (0)
PRINT5
#define PRINT5(a, b, c, d, e)
Value:
    do { \
    if (IS_ITYPE_VALID(a)) ITYPE_FORMAT(a); \
    if (IS_ITYPE_VALID(b)) ITYPE_FORMAT(b); \
    if (IS_ITYPE_VALID(c)) ITYPE_FORMAT(c); \
    if (IS_ITYPE_VALID(d)) ITYPE_FORMAT(d); \
    if (IS_ITYPE_VALID(e)) ITYPE_FORMAT(e); \
    printf("\n"); \
} while (0)
Definition at line 154 of file print.h.
                                 { \
    if (IS_ITYPE_VALID(a)) ITYPE_FORMAT(a); \
    if (IS_ITYPE_VALID(b)) ITYPE_FORMAT(b); \
    if (IS_ITYPE_VALID(c)) ITYPE_FORMAT(c); \
    if (IS_ITYPE_VALID(d)) ITYPE_FORMAT(d); \
    if (IS_ITYPE_VALID(e)) ITYPE_FORMAT(e); \
    printf("\n"); \
} while (0)
PRINT6
#define PRINT6(a, b, c, d, e, f)
Value:
    do { \
    if (IS_ITYPE_VALID(a)) ITYPE_FORMAT(a); \
    if (IS_ITYPE_VALID(b)) ITYPE_FORMAT(b); \
    if (IS_ITYPE_VALID(c)) ITYPE_FORMAT(c); \
    if (IS_ITYPE_VALID(d)) ITYPE_FORMAT(d); \
    if (IS_ITYPE_VALID(e)) ITYPE_FORMAT(e); \
    if (IS_ITYPE_VALID(f)) ITYPE_FORMAT(f); \
    printf("\n"); \
} while (0)
Definition at line 164 of file print.h.
                                    { \
    if (IS_ITYPE_VALID(a)) ITYPE_FORMAT(a); \
    if (IS_ITYPE_VALID(b)) ITYPE_FORMAT(b); \
    if (IS_ITYPE_VALID(c)) ITYPE_FORMAT(c); \
    if (IS_ITYPE_VALID(d)) ITYPE_FORMAT(d); \
    if (IS_ITYPE_VALID(e)) ITYPE_FORMAT(e); \
    if (IS_ITYPE_VALID(f)) ITYPE_FORMAT(f); \
    printf("\n"); \
} while (0)
PRINT7
#define PRINT7(a, b, c, d, e, f, g)
Value:
    do { \
    if (IS_ITYPE_VALID(a)) ITYPE_FORMAT(a); \
    if (IS_ITYPE_VALID(b)) ITYPE_FORMAT(b); \
    if (IS_ITYPE_VALID(c)) ITYPE_FORMAT(c); \
    if (IS_ITYPE_VALID(d)) ITYPE_FORMAT(d); \
    if (IS_ITYPE_VALID(e)) ITYPE_FORMAT(e); \
    if (IS_ITYPE_VALID(f)) ITYPE_FORMAT(f); \
    if (IS_ITYPE_VALID(g)) ITYPE_FORMAT(g); \
    printf("\n"); \
} while (0)
Definition at line 175 of file print.h.
                                       { \
    if (IS_ITYPE_VALID(a)) ITYPE_FORMAT(a); \
    if (IS_ITYPE_VALID(b)) ITYPE_FORMAT(b); \
    if (IS_ITYPE_VALID(c)) ITYPE_FORMAT(c); \
    if (IS_ITYPE_VALID(d)) ITYPE_FORMAT(d); \
    if (IS_ITYPE_VALID(e)) ITYPE_FORMAT(e); \
    if (IS_ITYPE_VALID(f)) ITYPE_FORMAT(f); \
    if (IS_ITYPE_VALID(g)) ITYPE_FORMAT(g); \
    printf("\n"); \
} while (0)
PRINT8
#define PRINT8(a, b, c, d, e, f, g, h)
Value:
    do { \
    if (IS_ITYPE_VALID(a)) ITYPE_FORMAT(a); \
    if (IS_ITYPE_VALID(b)) ITYPE_FORMAT(b); \
    if (IS_ITYPE_VALID(c)) ITYPE_FORMAT(c); \
    if (IS_ITYPE_VALID(d)) ITYPE_FORMAT(d); \
    if (IS_ITYPE_VALID(e)) ITYPE_FORMAT(e); \
    if (IS_ITYPE_VALID(f)) ITYPE_FORMAT(f); \
    if (IS_ITYPE_VALID(g)) ITYPE_FORMAT(g); \
    if (IS_ITYPE_VALID(h)) ITYPE_FORMAT(h); \
    printf("\n"); \
} while (0)
Definition at line 187 of file print.h.
                                          { \
    if (IS_ITYPE_VALID(a)) ITYPE_FORMAT(a); \
    if (IS_ITYPE_VALID(b)) ITYPE_FORMAT(b); \
    if (IS_ITYPE_VALID(c)) ITYPE_FORMAT(c); \
    if (IS_ITYPE_VALID(d)) ITYPE_FORMAT(d); \
    if (IS_ITYPE_VALID(e)) ITYPE_FORMAT(e); \
    if (IS_ITYPE_VALID(f)) ITYPE_FORMAT(f); \
    if (IS_ITYPE_VALID(g)) ITYPE_FORMAT(g); \
    if (IS_ITYPE_VALID(h)) ITYPE_FORMAT(h); \
    printf("\n"); \
} while (0)
PRNT_LENGTH
#define PRNT_LENGTH 20
Definition at line 23 of file print.h.
Function Documentation
print_achar()
void print_achar (Char x)
Definition at line 275 of file print.c.
                         {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_char(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_char(x.array[x.active_length - 1]);
    printf(" ]");
}
References Char::active_length, Char::array, print_char(), and PRNT_LENGTH.
print_bool()
void print_bool (bool x)
Definition at line 31 of file print.c.
{ printf(x ? "true" : "false"); }
Referenced by print_vbool().
print_char()
void print_char (char x)
Definition at line 29 of file print.c.
{ printf("%c", x); }
Referenced by print_achar().
print_double()
void print_double (double x)
Definition at line 27 of file print.c.
{ printf("%lf", x); }
Referenced by print_vdble().
print_float()
void print_float (float x)
Definition at line 26 of file print.c.
{ printf("%f", x); }
Referenced by print_vfloat().
print_int()
void print_int (int x)
Definition at line 20 of file print.c.
{ printf("%d", x); }
Referenced by print_vint().
print_llong()
void print_llong (long long int x)
Definition at line 24 of file print.c.
{ printf("%lld", x); }
Referenced by print_vllint().
print_long()
void print_long (long int x)
Definition at line 22 of file print.c.
{ printf("%ld", x); }
Referenced by print_vlint().
print_longdouble()
void print_longdouble (long double x)
Definition at line 28 of file print.c.
{ printf("%Lf", x); }
Referenced by print_vldble().
print_short()
void print_short (short x)
Definition at line 18 of file print.c.
{ printf("%hd", x); }
Referenced by print_vshort().
print_string()
void print_string (char * x)
Definition at line 32 of file print.c.
{ printf("%s", x); }
Referenced by print_vstring().
print_uachar()
void print_uachar (UChar x)
print_uchar()
void print_uchar (unsigned char x)
Definition at line 30 of file print.c.
{ printf("%hhu", x); }
print_uint()
void print_uint (unsigned int x)
Definition at line 21 of file print.c.
{ printf("%u", x); }
Referenced by print_vuint().
print_ullong()
void print_ullong (unsigned long long int x)
Definition at line 25 of file print.c.
{ printf("%llu", x); }
Referenced by print_vullint().
print_ulong()
void print_ulong (unsigned long int x)
Definition at line 23 of file print.c.
{ printf("%lu", x); }
Referenced by print_vulint().
print_ushort()
void print_ushort (unsigned short x)
Definition at line 19 of file print.c.
{ printf("%hu", x); }
Referenced by print_vushort().
print_vbool()
void print_vbool (Bool x)
Definition at line 297 of file print.c.
                         {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_bool(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_bool(x.array[x.active_length - 1]);
    printf(" ]");
}
References Bool::active_length, Bool::array, print_bool(), and PRNT_LENGTH.
print_vdble()
void print_vdble (Dble x)
Definition at line 231 of file print.c.
                         {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_double(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_double(x.array[x.active_length - 1]);
    printf(" ]");
}
References Dble::active_length, Dble::array, print_double(), and PRNT_LENGTH.
print_vfloat()
void print_vfloat (Flt x)
Definition at line 209 of file print.c.
                         {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_float(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_float(x.array[x.active_length - 1]);
    printf(" ]");
}
References Flt::active_length, Flt::array, print_float(), and PRNT_LENGTH.
print_vint()
void print_vint (Int x)
Definition at line 81 of file print.c.
                       {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_int(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_int(x.array[x.active_length - 1]);
    printf(" ]");
}
References Int::active_length, Int::array, print_int(), and PRNT_LENGTH.
print_vldble()
void print_vldble (LDble x)
Definition at line 253 of file print.c.
                           {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_longdouble(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_longdouble(x.array[x.active_length - 1]);
    printf(" ]");
}
References LDble::active_length, LDble::array, print_longdouble(), and PRNT_LENGTH.
print_vlint()
void print_vlint (LInt x)
Definition at line 121 of file print.c.
                         {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_long(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_long(x.array[x.active_length - 1]);
    printf(" ]");
}
References LInt::active_length, LInt::array, print_long(), and PRNT_LENGTH.
print_vllint()
void print_vllint (LLInt x)
Definition at line 165 of file print.c.
                           {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_llong(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_llong(x.array[x.active_length - 1]);
    printf(" ]");
}
References LLInt::active_length, LLInt::array, print_llong(), and PRNT_LENGTH.
print_vshort()
void print_vshort (Short x)
Definition at line 37 of file print.c.
                           {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_short(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_short(x.array[x.active_length - 1]);
    printf(" ]");
}
References Short::active_length, Short::array, print_short(), and PRNT_LENGTH.
print_vstring()
void print_vstring (String x)
Definition at line 319 of file print.c.
                             {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_string(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_string(x.array[x.active_length - 1]);
    printf(" ]");
}
References String::active_length, String::array, print_string(), and PRNT_LENGTH.
print_vuint()
void print_vuint (UInt x)
Definition at line 103 of file print.c.
                         {
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_uint(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_uint(x.array[x.active_length - 1]);
    printf(" ]");
}
References UInt::active_length, UInt::array, print_uint(), and PRNT_LENGTH.
print_vulint()
void print_vulint (ULInt x)
Definition at line 143 of file print.c.
                           {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_ulong(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_ulong(x.array[x.active_length - 1]);
    printf(" ]");
}
References ULInt::active_length, ULInt::array, print_ulong(), and PRNT_LENGTH.
print_vullint()
void print_vullint (ULLInt x)
Definition at line 187 of file print.c.
                             {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_ullong(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_ullong(x.array[x.active_length - 1]);
    printf(" ]");
}
References ULLInt::active_length, ULLInt::array, print_ullong(), and PRNT_LENGTH.
print_vushort()
void print_vushort (UShort x)
Definition at line 59 of file print.c.
                             {
    if (x.active_length == 0) {
        printf("[ NULL ]");
        return;
    }
    printf("[ ");
    size_t j = 0;
    for(size_t i = 0; i < x.active_length - 1; i++) {
        print_ushort(x.array[i]);
        printf(", ");
        j++;
        if (j == PRNT_LENGTH) {
            printf("\n");
            printf(" ");
            j = 0;
        }
    }
    print_ushort(x.array[x.active_length - 1]);
    printf(" ]");
}
References UShort::active_length, UShort::array, print_ushort(), and PRNT_LENGTH.